/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b03(clock, reset, request1, request2, request3, request4, grant_o);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  input clock;
  wire clock;
  wire \coda0[0] ;
  wire \coda0[1] ;
  wire \coda0[2] ;
  wire \coda1[0] ;
  wire \coda1[1] ;
  wire \coda1[2] ;
  wire \coda2[0] ;
  wire \coda2[1] ;
  wire \coda2[2] ;
  wire \coda3[0] ;
  wire \coda3[1] ;
  wire \coda3[2] ;
  wire fu1;
  wire fu2;
  wire fu3;
  wire fu4;
  wire \grant[0] ;
  wire \grant[1] ;
  wire \grant[2] ;
  wire \grant[3] ;
  output [3:0] grant_o;
  wire [3:0] grant_o;
  input request1;
  wire request1;
  input request2;
  wire request2;
  input request3;
  wire request3;
  input request4;
  wire request4;
  input reset;
  wire reset;
  wire ru1;
  wire ru2;
  wire ru3;
  wire ru4;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  sky130_fd_sc_hd__mux2_2 _122_ (
    .A0(fu4),
    .A1(ru4),
    .S(\stato[2] ),
    .X(_119_)
  );
  sky130_fd_sc_hd__buf_1 _123_ (
    .A(_119_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_2 _124_ (
    .A0(fu3),
    .A1(ru3),
    .S(\stato[2] ),
    .X(_120_)
  );
  sky130_fd_sc_hd__buf_1 _125_ (
    .A(_120_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_2 _126_ (
    .A0(fu2),
    .A1(ru2),
    .S(\stato[2] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__buf_1 _127_ (
    .A(_060_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_2 _128_ (
    .A0(fu1),
    .A1(ru1),
    .S(\stato[2] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__buf_1 _129_ (
    .A(_061_),
    .X(_056_)
  );
  sky130_fd_sc_hd__buf_1 _130_ (
    .A(\stato[1] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__or2_2 _131_ (
    .A(_062_),
    .B(\stato[0] ),
    .X(_063_)
  );
  sky130_fd_sc_hd__buf_1 _132_ (
    .A(_063_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_2 _133_ (
    .A0(ru4),
    .A1(request4),
    .S(_000_),
    .X(_064_)
  );
  sky130_fd_sc_hd__buf_1 _134_ (
    .A(_064_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_2 _135_ (
    .A0(ru3),
    .A1(request3),
    .S(_000_),
    .X(_065_)
  );
  sky130_fd_sc_hd__buf_1 _136_ (
    .A(_065_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_2 _137_ (
    .A0(ru2),
    .A1(request2),
    .S(_000_),
    .X(_066_)
  );
  sky130_fd_sc_hd__buf_1 _138_ (
    .A(_066_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_2 _139_ (
    .A0(ru1),
    .A1(request1),
    .S(_000_),
    .X(_067_)
  );
  sky130_fd_sc_hd__buf_1 _140_ (
    .A(_067_),
    .X(_052_)
  );
  sky130_fd_sc_hd__inv_2 _141_ (
    .A(\coda3[2] ),
    .Y(_068_)
  );
  sky130_fd_sc_hd__and2b_2 _142_ (
    .A_N(fu4),
    .B(ru4),
    .X(_069_)
  );
  sky130_fd_sc_hd__nor2_2 _143_ (
    .A(ru2),
    .B(ru1),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_2 _144_ (
    .A(fu3),
    .B(ru3),
    .Y(_071_)
  );
  sky130_fd_sc_hd__o211ai_2 _145_ (
    .A1(ru3),
    .A2(_069_),
    .B1(_070_),
    .C1(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__inv_2 _146_ (
    .A(ru2),
    .Y(_073_)
  );
  sky130_fd_sc_hd__or2b_2 _147_ (
    .A(fu1),
    .B_N(ru1),
    .X(_074_)
  );
  sky130_fd_sc_hd__o311a_2 _148_ (
    .A1(fu2),
    .A2(_073_),
    .A3(ru1),
    .B1(_074_),
    .C1(\stato[2] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__o41a_2 _149_ (
    .A1(fu4),
    .A2(fu3),
    .A3(fu2),
    .A4(fu1),
    .B1(_062_),
    .X(_076_)
  );
  sky130_fd_sc_hd__inv_2 _150_ (
    .A(\stato[1] ),
    .Y(_077_)
  );
  sky130_fd_sc_hd__and2_2 _151_ (
    .A(\stato[2] ),
    .B(_077_),
    .X(_078_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _152_ (
    .A1_N(_072_),
    .A2_N(_075_),
    .B1(_076_),
    .B2(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__buf_1 _153_ (
    .A(_079_),
    .X(_080_)
  );
  sky130_fd_sc_hd__a21boi_2 _154_ (
    .A1(_072_),
    .A2(_075_),
    .B1_N(_078_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _155_ (
    .A1_N(_068_),
    .A2_N(_080_),
    .B1(_081_),
    .B2(\coda2[2] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__inv_2 _156_ (
    .A(\coda3[1] ),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _157_ (
    .A1_N(_082_),
    .A2_N(_080_),
    .B1(_081_),
    .B2(\coda2[1] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__inv_2 _158_ (
    .A(\coda3[0] ),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _159_ (
    .A1_N(_083_),
    .A2_N(_080_),
    .B1(_081_),
    .B2(\coda2[0] ),
    .X(_049_)
  );
  sky130_fd_sc_hd__nor3b_2 _160_ (
    .A(\coda0[1] ),
    .B(\coda0[0] ),
    .C_N(\coda0[2] ),
    .Y(_084_)
  );
  sky130_fd_sc_hd__mux2_2 _161_ (
    .A0(\grant[3] ),
    .A1(_084_),
    .S(_076_),
    .X(_085_)
  );
  sky130_fd_sc_hd__buf_1 _162_ (
    .A(_085_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor3b_2 _163_ (
    .A(\coda0[2] ),
    .B(\coda0[0] ),
    .C_N(\coda0[1] ),
    .Y(_086_)
  );
  sky130_fd_sc_hd__mux2_2 _164_ (
    .A0(\grant[2] ),
    .A1(_086_),
    .S(_076_),
    .X(_087_)
  );
  sky130_fd_sc_hd__buf_1 _165_ (
    .A(_087_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor3b_2 _166_ (
    .A(\coda0[2] ),
    .B(\coda0[1] ),
    .C_N(\coda0[0] ),
    .Y(_088_)
  );
  sky130_fd_sc_hd__mux2_2 _167_ (
    .A0(\grant[1] ),
    .A1(_088_),
    .S(_076_),
    .X(_089_)
  );
  sky130_fd_sc_hd__buf_1 _168_ (
    .A(_089_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and3_2 _169_ (
    .A(\coda0[2] ),
    .B(\coda0[1] ),
    .C(\coda0[0] ),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_2 _170_ (
    .A0(\grant[0] ),
    .A1(_090_),
    .S(_076_),
    .X(_091_)
  );
  sky130_fd_sc_hd__buf_1 _171_ (
    .A(_091_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_2 _172_ (
    .A0(\coda1[2] ),
    .A1(\coda3[2] ),
    .S(_062_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_2 _173_ (
    .A0(\coda2[2] ),
    .A1(_092_),
    .S(_080_),
    .X(_093_)
  );
  sky130_fd_sc_hd__buf_1 _174_ (
    .A(_093_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_2 _175_ (
    .A0(\coda1[1] ),
    .A1(\coda3[1] ),
    .S(_062_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_2 _176_ (
    .A0(\coda2[1] ),
    .A1(_094_),
    .S(_080_),
    .X(_095_)
  );
  sky130_fd_sc_hd__buf_1 _177_ (
    .A(_095_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_2 _178_ (
    .A0(\coda1[0] ),
    .A1(\coda3[0] ),
    .S(_062_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_2 _179_ (
    .A0(\coda2[0] ),
    .A1(_096_),
    .S(_080_),
    .X(_097_)
  );
  sky130_fd_sc_hd__buf_1 _180_ (
    .A(_097_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_2 _181_ (
    .A0(\coda0[2] ),
    .A1(\coda2[2] ),
    .S(_062_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_2 _182_ (
    .A0(\coda1[2] ),
    .A1(_098_),
    .S(_080_),
    .X(_099_)
  );
  sky130_fd_sc_hd__buf_1 _183_ (
    .A(_099_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_2 _184_ (
    .A0(\coda0[1] ),
    .A1(\coda2[1] ),
    .S(_062_),
    .X(_100_)
  );
  sky130_fd_sc_hd__mux2_2 _185_ (
    .A0(\coda1[1] ),
    .A1(_100_),
    .S(_080_),
    .X(_101_)
  );
  sky130_fd_sc_hd__buf_1 _186_ (
    .A(_101_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_2 _187_ (
    .A0(\coda0[0] ),
    .A1(\coda2[0] ),
    .S(_062_),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_2 _188_ (
    .A0(\coda1[0] ),
    .A1(_102_),
    .S(_080_),
    .X(_103_)
  );
  sky130_fd_sc_hd__buf_1 _189_ (
    .A(_103_),
    .X(_039_)
  );
  sky130_fd_sc_hd__o21ai_2 _190_ (
    .A1(ru3),
    .A2(ru2),
    .B1(_077_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__o22a_2 _191_ (
    .A1(\coda1[2] ),
    .A2(_077_),
    .B1(_104_),
    .B2(ru1),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_2 _192_ (
    .A0(\coda0[2] ),
    .A1(_105_),
    .S(_080_),
    .X(_106_)
  );
  sky130_fd_sc_hd__buf_1 _193_ (
    .A(_106_),
    .X(_038_)
  );
  sky130_fd_sc_hd__a211o_2 _194_ (
    .A1(ru3),
    .A2(_073_),
    .B1(ru1),
    .C1(_062_),
    .X(_107_)
  );
  sky130_fd_sc_hd__a21bo_2 _195_ (
    .A1(\coda1[1] ),
    .A2(_062_),
    .B1_N(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_2 _196_ (
    .A0(\coda0[1] ),
    .A1(_108_),
    .S(_079_),
    .X(_109_)
  );
  sky130_fd_sc_hd__buf_1 _197_ (
    .A(_109_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_2 _198_ (
    .A0(\coda1[0] ),
    .A1(_070_),
    .S(_077_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_2 _199_ (
    .A0(\coda0[0] ),
    .A1(_110_),
    .S(_079_),
    .X(_111_)
  );
  sky130_fd_sc_hd__buf_1 _200_ (
    .A(_111_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_2 _201_ (
    .A0(grant_o[3]),
    .A1(\grant[3] ),
    .S(\stato[2] ),
    .X(_112_)
  );
  sky130_fd_sc_hd__buf_1 _202_ (
    .A(_112_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_2 _203_ (
    .A0(grant_o[2]),
    .A1(\grant[2] ),
    .S(\stato[2] ),
    .X(_113_)
  );
  sky130_fd_sc_hd__buf_1 _204_ (
    .A(_113_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_2 _205_ (
    .A0(grant_o[1]),
    .A1(\grant[1] ),
    .S(\stato[2] ),
    .X(_114_)
  );
  sky130_fd_sc_hd__buf_1 _206_ (
    .A(_114_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_2 _207_ (
    .A0(grant_o[0]),
    .A1(\grant[0] ),
    .S(\stato[2] ),
    .X(_115_)
  );
  sky130_fd_sc_hd__buf_1 _208_ (
    .A(_115_),
    .X(_032_)
  );
  sky130_fd_sc_hd__buf_1 _209_ (
    .A(reset),
    .X(_116_)
  );
  sky130_fd_sc_hd__inv_2 _210_ (
    .A(_116_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_2 _211_ (
    .A(_116_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_2 _212_ (
    .A(_116_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _213_ (
    .A(_116_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _214_ (
    .A(_116_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _215_ (
    .A(_116_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _216_ (
    .A(_116_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_2 _217_ (
    .A(_116_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _218_ (
    .A(_116_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _219_ (
    .A(_116_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__buf_1 _220_ (
    .A(reset),
    .X(_117_)
  );
  sky130_fd_sc_hd__inv_2 _221_ (
    .A(_117_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _222_ (
    .A(_117_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _223_ (
    .A(_117_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _224_ (
    .A(_117_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _225_ (
    .A(_117_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _226_ (
    .A(_117_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _227_ (
    .A(_117_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _228_ (
    .A(_117_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _229_ (
    .A(_117_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _230_ (
    .A(_117_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__buf_1 _231_ (
    .A(reset),
    .X(_118_)
  );
  sky130_fd_sc_hd__inv_2 _232_ (
    .A(_118_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _233_ (
    .A(_118_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _234_ (
    .A(_118_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _235_ (
    .A(_118_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _236_ (
    .A(_118_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _237_ (
    .A(_118_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _238_ (
    .A(_118_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _239_ (
    .A(_118_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _240_ (
    .A(_118_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _241_ (
    .A(_118_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _242_ (
    .A(reset),
    .Y(_031_)
  );
  sky130_fd_sc_hd__dfstp_2 _243_ (
    .CLK(clock),
    .D(_121_),
    .Q(\stato[0] ),
    .SET_B(_001_)
  );
  sky130_fd_sc_hd__dfrtp_2 _244_ (
    .CLK(clock),
    .D(\stato[2] ),
    .Q(\stato[1] ),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_2 _245_ (
    .CLK(clock),
    .D(_000_),
    .Q(\stato[2] ),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_2 _246_ (
    .CLK(clock),
    .D(_032_),
    .Q(grant_o[0]),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_2 _247_ (
    .CLK(clock),
    .D(_033_),
    .Q(grant_o[1]),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_2 _248_ (
    .CLK(clock),
    .D(_034_),
    .Q(grant_o[2]),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_2 _249_ (
    .CLK(clock),
    .D(_035_),
    .Q(grant_o[3]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_2 _250_ (
    .CLK(clock),
    .D(_036_),
    .Q(\coda0[0] ),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_2 _251_ (
    .CLK(clock),
    .D(_037_),
    .Q(\coda0[1] ),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_2 _252_ (
    .CLK(clock),
    .D(_038_),
    .Q(\coda0[2] ),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfrtp_2 _253_ (
    .CLK(clock),
    .D(_039_),
    .Q(\coda1[0] ),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_2 _254_ (
    .CLK(clock),
    .D(_040_),
    .Q(\coda1[1] ),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_2 _255_ (
    .CLK(clock),
    .D(_041_),
    .Q(\coda1[2] ),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_2 _256_ (
    .CLK(clock),
    .D(_042_),
    .Q(\coda2[0] ),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_2 _257_ (
    .CLK(clock),
    .D(_043_),
    .Q(\coda2[1] ),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_2 _258_ (
    .CLK(clock),
    .D(_044_),
    .Q(\coda2[2] ),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_2 _259_ (
    .CLK(clock),
    .D(_045_),
    .Q(\grant[0] ),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_2 _260_ (
    .CLK(clock),
    .D(_046_),
    .Q(\grant[1] ),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _261_ (
    .CLK(clock),
    .D(_047_),
    .Q(\grant[2] ),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_2 _262_ (
    .CLK(clock),
    .D(_048_),
    .Q(\grant[3] ),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_2 _263_ (
    .CLK(clock),
    .D(_049_),
    .Q(\coda3[0] ),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_2 _264_ (
    .CLK(clock),
    .D(_050_),
    .Q(\coda3[1] ),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_2 _265_ (
    .CLK(clock),
    .D(_051_),
    .Q(\coda3[2] ),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_2 _266_ (
    .CLK(clock),
    .D(_052_),
    .Q(ru1),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_2 _267_ (
    .CLK(clock),
    .D(_053_),
    .Q(ru2),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_2 _268_ (
    .CLK(clock),
    .D(_054_),
    .Q(ru3),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_2 _269_ (
    .CLK(clock),
    .D(_055_),
    .Q(ru4),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_2 _270_ (
    .CLK(clock),
    .D(_056_),
    .Q(fu1),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_2 _271_ (
    .CLK(clock),
    .D(_057_),
    .Q(fu2),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_2 _272_ (
    .CLK(clock),
    .D(_058_),
    .Q(fu3),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_2 _273_ (
    .CLK(clock),
    .D(_059_),
    .Q(fu4),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__conb_1 _274_ (
    .LO(_121_)
  );
endmodule
