// Auto-generated mapped fault enables:
//   fault_en[0] -> _1276_ -> STATO[0] (RTL)
//   fault_en[1] -> _1277_ -> STATO[1] (RTL)
//   fault_en[2] -> _1278_ -> STATO[2] (RTL)
//   fault_en[3] -> _1279_ -> NUM[0] (RTL)
//   fault_en[4] -> _1280_ -> NUM[1] (RTL)
//   fault_en[5] -> _1281_ -> NUM[2] (RTL)
//   fault_en[6] -> _1282_ -> NUM[3] (RTL)
//   fault_en[7] -> _1283_ -> NUM[4] (RTL)
//   fault_en[8] -> _1284_ -> NUM[5] (RTL)
//   fault_en[9] -> _1285_ -> NUM[6] (RTL)
//   fault_en[10] -> _1286_ -> NUM[7] (RTL)
//   fault_en[11] -> _1287_ -> NUM[8] (RTL)
//   fault_en[12] -> _1288_ -> NUM[9] (RTL)
//   fault_en[13] -> _1289_ -> NUM[10] (RTL)
//   fault_en[14] -> _1290_ -> NUM[11] (RTL)
//   fault_en[15] -> _1291_ -> NUM[12] (RTL)
//   fault_en[16] -> _1292_ -> NUM[13] (RTL)
//   fault_en[17] -> _1293_ -> NUM[14] (RTL)
//   fault_en[18] -> _1294_ -> NUM[15] (RTL)
//   fault_en[19] -> _1295_ -> NUM[16] (RTL)
//   fault_en[20] -> _1296_ -> NUM[17] (RTL)
//   fault_en[21] -> _1297_ -> NUM[18] (RTL)
//   fault_en[22] -> _1298_ -> NUM[19] (RTL)
//   fault_en[23] -> _1299_ -> NUM[20] (RTL)
//   fault_en[24] -> _1300_ -> NUM[21] (RTL)
//   fault_en[25] -> _1301_ -> NUM[22] (RTL)
//   fault_en[26] -> _1302_ -> NUM[23] (RTL)
//   fault_en[27] -> _1303_ -> NUM[24] (RTL)
//   fault_en[28] -> _1304_ -> NUM[25] (RTL)
//   fault_en[29] -> _1305_ -> NUM[26] (RTL)
//   fault_en[30] -> _1306_ -> NUM[27] (RTL)
//   fault_en[31] -> _1307_ -> NUM[28] (RTL)
//   fault_en[32] -> _1308_ -> NUM[29] (RTL)
//   fault_en[33] -> _1309_ -> NUM[30] (RTL)
//   fault_en[34] -> _1310_ -> NUM[31] (RTL)
//   fault_en[35] -> _1311_ -> MAR[0] (RTL)
//   fault_en[36] -> _1312_ -> MAR[1] (RTL)
//   fault_en[37] -> _1313_ -> MAR[2] (RTL)
//   fault_en[38] -> _1314_ -> MAR[3] (RTL)
//   fault_en[39] -> _1315_ -> MAR[4] (RTL)
//   fault_en[40] -> _1316_ -> MAR[5] (RTL)
//   fault_en[41] -> _1317_ -> MAR[6] (RTL)
//   fault_en[42] -> _1318_ -> MAR[7] (RTL)
//   fault_en[43] -> _1319_ -> MAR[8] (RTL)
//   fault_en[44] -> _1320_ -> MAR[9] (RTL)
//   fault_en[45] -> _1321_ -> MAR[10] (RTL)
//   fault_en[46] -> _1322_ -> MAR[11] (RTL)
//   fault_en[47] -> _1323_ -> MAR[12] (RTL)
//   fault_en[48] -> _1324_ -> MAR[13] (RTL)
//   fault_en[49] -> _1325_ -> MAR[14] (RTL)
//   fault_en[50] -> _1326_ -> MAR[15] (RTL)
//   fault_en[51] -> _1327_ -> MAR[16] (RTL)
//   fault_en[52] -> _1328_ -> MAR[17] (RTL)
//   fault_en[53] -> _1329_ -> MAR[18] (RTL)
//   fault_en[54] -> _1330_ -> MAR[19] (RTL)
//   fault_en[55] -> _1331_ -> MAR[20] (RTL)
//   fault_en[56] -> _1332_ -> MAR[21] (RTL)
//   fault_en[57] -> _1333_ -> MAR[22] (RTL)
//   fault_en[58] -> _1334_ -> MAR[23] (RTL)
//   fault_en[59] -> _1335_ -> MAR[24] (RTL)
//   fault_en[60] -> _1336_ -> MAR[25] (RTL)
//   fault_en[61] -> _1337_ -> MAR[26] (RTL)
//   fault_en[62] -> _1338_ -> MAR[27] (RTL)
//   fault_en[63] -> _1339_ -> MAR[28] (RTL)
//   fault_en[64] -> _1340_ -> MAR[29] (RTL)
//   fault_en[65] -> _1341_ -> MAR[30] (RTL)
//   fault_en[66] -> _1342_ -> MAR[31] (RTL)
//   fault_en[67] -> _1343_ -> TEMP[0] (RTL)
//   fault_en[68] -> _1344_ -> TEMP[1] (RTL)
//   fault_en[69] -> _1345_ -> TEMP[2] (RTL)
//   fault_en[70] -> _1346_ -> TEMP[3] (RTL)
//   fault_en[71] -> _1347_ -> TEMP[4] (RTL)
//   fault_en[72] -> _1348_ -> TEMP[5] (RTL)
//   fault_en[73] -> _1349_ -> TEMP[6] (RTL)
//   fault_en[74] -> _1350_ -> TEMP[7] (RTL)
//   fault_en[75] -> _1351_ -> TEMP[10] (RTL)
//   fault_en[76] -> _1352_ -> MAX[0] (RTL)
//   fault_en[77] -> _1353_ -> MAX[1] (RTL)
//   fault_en[78] -> _1354_ -> MAX[2] (RTL)
//   fault_en[79] -> _1355_ -> MAX[3] (RTL)
//   fault_en[80] -> _1356_ -> MAX[4] (RTL)
//   fault_en[81] -> _1357_ -> MAX[5] (RTL)
//   fault_en[82] -> _1358_ -> MAX[6] (RTL)
//   fault_en[83] -> _1359_ -> MAX[7] (RTL)
//   fault_en[84] -> _1360_ -> MAX[10] (RTL)
//   fault_en[85] -> _1361_ -> FLAG[0] (RTL)
//   fault_en[86] -> _1362_ -> EN_DISP[0] (RTL)
//   fault_en[87] -> _1363_ -> RES_DISP[0] (RTL)

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b05(CLOCK, RESET, START, SIGN, DISPMAX1, DISPMAX2, DISPMAX3, DISPNUM1, DISPNUM2, fault_en);
  input [87:0] fault_en;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  input CLOCK;
  wire CLOCK;
  output [6:0] DISPMAX1;
  wire [6:0] DISPMAX1;
  output [6:0] DISPMAX2;
  wire [6:0] DISPMAX2;
  output [6:0] DISPMAX3;
  wire [6:0] DISPMAX3;
  output [6:0] DISPNUM1;
  wire [6:0] DISPNUM1;
  output [6:0] DISPNUM2;
  wire [6:0] DISPNUM2;
  wire EN_DISP;
  wire FLAG;
  wire \MAR[0] ;
  wire \MAR[10] ;
  wire \MAR[11] ;
  wire \MAR[12] ;
  wire \MAR[13] ;
  wire \MAR[14] ;
  wire \MAR[15] ;
  wire \MAR[16] ;
  wire \MAR[17] ;
  wire \MAR[18] ;
  wire \MAR[19] ;
  wire \MAR[1] ;
  wire \MAR[20] ;
  wire \MAR[21] ;
  wire \MAR[22] ;
  wire \MAR[23] ;
  wire \MAR[24] ;
  wire \MAR[25] ;
  wire \MAR[26] ;
  wire \MAR[27] ;
  wire \MAR[28] ;
  wire \MAR[29] ;
  wire \MAR[2] ;
  wire \MAR[30] ;
  wire \MAR[31] ;
  wire \MAR[3] ;
  wire \MAR[4] ;
  wire \MAR[5] ;
  wire \MAR[6] ;
  wire \MAR[7] ;
  wire \MAR[8] ;
  wire \MAR[9] ;
  wire \MAX[0] ;
  wire \MAX[10] ;
  wire \MAX[1] ;
  wire \MAX[2] ;
  wire \MAX[3] ;
  wire \MAX[4] ;
  wire \MAX[5] ;
  wire \MAX[6] ;
  wire \MAX[7] ;
  wire \NUM[0] ;
  wire \NUM[10] ;
  wire \NUM[11] ;
  wire \NUM[12] ;
  wire \NUM[13] ;
  wire \NUM[14] ;
  wire \NUM[15] ;
  wire \NUM[16] ;
  wire \NUM[17] ;
  wire \NUM[18] ;
  wire \NUM[19] ;
  wire \NUM[1] ;
  wire \NUM[20] ;
  wire \NUM[21] ;
  wire \NUM[22] ;
  wire \NUM[23] ;
  wire \NUM[24] ;
  wire \NUM[25] ;
  wire \NUM[26] ;
  wire \NUM[27] ;
  wire \NUM[28] ;
  wire \NUM[29] ;
  wire \NUM[2] ;
  wire \NUM[30] ;
  wire \NUM[31] ;
  wire \NUM[3] ;
  wire \NUM[4] ;
  wire \NUM[5] ;
  wire \NUM[6] ;
  wire \NUM[7] ;
  wire \NUM[8] ;
  wire \NUM[9] ;
  input RESET;
  wire RESET;
  wire RES_DISP;
  output SIGN;
  wire SIGN;
  input START;
  wire START;
  wire \STATO[0] ;
  wire \STATO[1] ;
  wire \STATO[2] ;
  wire \TEMP[0] ;
  wire \TEMP[10] ;
  wire \TEMP[1] ;
  wire \TEMP[2] ;
  wire \TEMP[3] ;
  wire \TEMP[4] ;
  wire \TEMP[5] ;
  wire \TEMP[6] ;
  wire \TEMP[7] ;
  sky130_fd_sc_hd__inv_2 _0626_ (
    .A(START),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__inv_2 _0627_ (
    .A(\STATO[2] ),
    .Y(_0177_)
  );
  sky130_fd_sc_hd__nand2_2 _0628_ (
    .A(_0177_),
    .B(\STATO[0] ),
    .Y(_0178_)
  );
  sky130_fd_sc_hd__nor3_2 _0629_ (
    .A(\STATO[1] ),
    .B(_0176_),
    .C(_0178_),
    .Y(_0179_)
  );
  sky130_fd_sc_hd__buf_1 _0630_ (
    .A(_0179_),
    .X(_0180_)
  );
  sky130_fd_sc_hd__buf_1 _0631_ (
    .A(\STATO[1] ),
    .X(_0181_)
  );
  sky130_fd_sc_hd__o31a_2 _0632_ (
    .A1(\STATO[2] ),
    .A2(_0181_),
    .A3(\STATO[0] ),
    .B1(RES_DISP),
    .X(_0182_)
  );
  sky130_fd_sc_hd__or2_2 _0633_ (
    .A(_0180_),
    .B(_0182_),
    .X(_0183_)
  );
  sky130_fd_sc_hd__buf_1 _0634_ (
    .A(_0183_),
    .X(_0175_)
  );
  sky130_fd_sc_hd__inv_2 _0635_ (
    .A(\MAR[4] ),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__or3_2 _0636_ (
    .A(\MAR[7] ),
    .B(\MAR[6] ),
    .C(\MAR[5] ),
    .X(_0185_)
  );
  sky130_fd_sc_hd__or4_2 _0637_ (
    .A(\MAR[17] ),
    .B(\MAR[16] ),
    .C(\MAR[9] ),
    .D(\MAR[8] ),
    .X(_0186_)
  );
  sky130_fd_sc_hd__or4_2 _0638_ (
    .A(\MAR[21] ),
    .B(\MAR[20] ),
    .C(\MAR[19] ),
    .D(\MAR[18] ),
    .X(_0187_)
  );
  sky130_fd_sc_hd__or4_2 _0639_ (
    .A(_0184_),
    .B(_0185_),
    .C(_0186_),
    .D(_0187_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__and3_2 _0640_ (
    .A(\MAR[2] ),
    .B(\MAR[1] ),
    .C(\MAR[0] ),
    .X(_0189_)
  );
  sky130_fd_sc_hd__nand2_2 _0641_ (
    .A(\MAR[3] ),
    .B(_0189_),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__or4_2 _0642_ (
    .A(\MAR[27] ),
    .B(\MAR[24] ),
    .C(\MAR[23] ),
    .D(\MAR[22] ),
    .X(_0191_)
  );
  sky130_fd_sc_hd__or4_2 _0643_ (
    .A(\MAR[31] ),
    .B(\MAR[30] ),
    .C(\MAR[29] ),
    .D(\MAR[28] ),
    .X(_0192_)
  );
  sky130_fd_sc_hd__or2_2 _0644_ (
    .A(\MAR[13] ),
    .B(\MAR[12] ),
    .X(_0193_)
  );
  sky130_fd_sc_hd__or2_2 _0645_ (
    .A(\MAR[15] ),
    .B(\MAR[14] ),
    .X(_0194_)
  );
  sky130_fd_sc_hd__or2_2 _0646_ (
    .A(\MAR[11] ),
    .B(\MAR[10] ),
    .X(_0195_)
  );
  sky130_fd_sc_hd__or2_2 _0647_ (
    .A(\MAR[26] ),
    .B(\MAR[25] ),
    .X(_0196_)
  );
  sky130_fd_sc_hd__or4_2 _0648_ (
    .A(_0193_),
    .B(_0194_),
    .C(_0195_),
    .D(_0196_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__or4_2 _0649_ (
    .A(_0190_),
    .B(_0191_),
    .C(_0192_),
    .D(_0197_),
    .X(_0198_)
  );
  sky130_fd_sc_hd__or2_2 _0650_ (
    .A(_0177_),
    .B(\STATO[0] ),
    .X(_0199_)
  );
  sky130_fd_sc_hd__buf_1 _0651_ (
    .A(_0199_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__nor2_2 _0652_ (
    .A(\STATO[1] ),
    .B(_0200_),
    .Y(_0201_)
  );
  sky130_fd_sc_hd__o21a_2 _0653_ (
    .A1(_0188_),
    .A2(_0198_),
    .B1(_0201_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__buf_1 _0654_ (
    .A(_0202_),
    .X(_0203_)
  );
  sky130_fd_sc_hd__a2111oi_2 _0655_ (
    .A1(\STATO[2] ),
    .A2(\STATO[0] ),
    .B1(_0176_),
    .C1(_0203_),
    .D1(_0181_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__o32a_2 _0656_ (
    .A1(_0181_),
    .A2(\STATO[0] ),
    .A3(_0203_),
    .B1(_0204_),
    .B2(EN_DISP),
    .X(_0174_)
  );
  sky130_fd_sc_hd__buf_1 _0657_ (
    .A(\MAR[3] ),
    .X(_0205_)
  );
  sky130_fd_sc_hd__buf_1 _0658_ (
    .A(\MAR[1] ),
    .X(_0206_)
  );
  sky130_fd_sc_hd__buf_1 _0659_ (
    .A(\MAR[0] ),
    .X(_0207_)
  );
  sky130_fd_sc_hd__a21oi_2 _0660_ (
    .A1(_0206_),
    .A2(_0207_),
    .B1(\MAR[2] ),
    .Y(_0208_)
  );
  sky130_fd_sc_hd__and2b_2 _0661_ (
    .A_N(_0206_),
    .B(_0207_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__a21o_2 _0662_ (
    .A1(_0205_),
    .A2(_0208_),
    .B1(_0209_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__or4bb_2 _0663_ (
    .A(\MAR[2] ),
    .B(_0206_),
    .C_N(_0207_),
    .D_N(\MAR[3] ),
    .X(_0211_)
  );
  sky130_fd_sc_hd__inv_2 _0664_ (
    .A(\MAR[2] ),
    .Y(_0212_)
  );
  sky130_fd_sc_hd__or2b_2 _0665_ (
    .A(_0207_),
    .B_N(_0206_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__inv_2 _0666_ (
    .A(\MAR[3] ),
    .Y(_0214_)
  );
  sky130_fd_sc_hd__a211o_2 _0667_ (
    .A1(_0212_),
    .A2(_0213_),
    .B1(_0209_),
    .C1(_0214_),
    .X(_0215_)
  );
  sky130_fd_sc_hd__and2_2 _0668_ (
    .A(\MAR[2] ),
    .B(_0206_),
    .X(_0216_)
  );
  sky130_fd_sc_hd__buf_1 _0669_ (
    .A(\MAR[2] ),
    .X(_0217_)
  );
  sky130_fd_sc_hd__buf_1 _0670_ (
    .A(_0207_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__nor3_2 _0671_ (
    .A(_0217_),
    .B(_0206_),
    .C(_0218_),
    .Y(_0219_)
  );
  sky130_fd_sc_hd__buf_1 _0672_ (
    .A(\MAR[4] ),
    .X(_0220_)
  );
  sky130_fd_sc_hd__o31a_2 _0673_ (
    .A1(_0205_),
    .A2(_0216_),
    .A3(_0219_),
    .B1(_0220_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__a32oi_2 _0674_ (
    .A1(_0184_),
    .A2(_0210_),
    .A3(_0211_),
    .B1(_0215_),
    .B2(_0221_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__or2_2 _0675_ (
    .A(\TEMP[3] ),
    .B(_0222_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__and2_2 _0676_ (
    .A(_0206_),
    .B(_0207_),
    .X(_0224_)
  );
  sky130_fd_sc_hd__and2b_2 _0677_ (
    .A_N(_0207_),
    .B(\MAR[2] ),
    .X(_0225_)
  );
  sky130_fd_sc_hd__o31a_2 _0678_ (
    .A1(_0205_),
    .A2(_0224_),
    .A3(_0225_),
    .B1(_0184_),
    .X(_0226_)
  );
  sky130_fd_sc_hd__buf_1 _0679_ (
    .A(\MAR[3] ),
    .X(_0227_)
  );
  sky130_fd_sc_hd__or2b_2 _0680_ (
    .A(\MAR[2] ),
    .B_N(_0207_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__nand2_2 _0681_ (
    .A(_0227_),
    .B(_0228_),
    .Y(_0229_)
  );
  sky130_fd_sc_hd__buf_1 _0682_ (
    .A(_0206_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__a31o_2 _0683_ (
    .A1(_0217_),
    .A2(_0230_),
    .A3(_0218_),
    .B1(_0205_),
    .X(_0231_)
  );
  sky130_fd_sc_hd__a21oi_2 _0684_ (
    .A1(_0231_),
    .A2(_0211_),
    .B1(_0184_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__a21oi_2 _0685_ (
    .A1(_0226_),
    .A2(_0229_),
    .B1(_0232_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__xnor2_2 _0686_ (
    .A(\TEMP[2] ),
    .B(_0233_),
    .Y(_0234_)
  );
  sky130_fd_sc_hd__xnor2_2 _0687_ (
    .A(\TEMP[3] ),
    .B(_0222_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__a21o_2 _0688_ (
    .A1(_0212_),
    .A2(_0213_),
    .B1(_0216_),
    .X(_0236_)
  );
  sky130_fd_sc_hd__nor2_2 _0689_ (
    .A(_0230_),
    .B(_0218_),
    .Y(_0237_)
  );
  sky130_fd_sc_hd__o31a_2 _0690_ (
    .A1(_0205_),
    .A2(_0224_),
    .A3(_0237_),
    .B1(_0220_),
    .X(_0238_)
  );
  sky130_fd_sc_hd__inv_2 _0691_ (
    .A(_0230_),
    .Y(_0239_)
  );
  sky130_fd_sc_hd__nand3b_2 _0692_ (
    .A_N(_0230_),
    .B(_0217_),
    .C(_0205_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__o2111a_2 _0693_ (
    .A1(_0227_),
    .A2(_0239_),
    .B1(_0228_),
    .C1(_0240_),
    .D1(_0184_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__a21oi_2 _0694_ (
    .A1(_0236_),
    .A2(_0238_),
    .B1(_0241_),
    .Y(_0242_)
  );
  sky130_fd_sc_hd__and2_2 _0695_ (
    .A(\TEMP[1] ),
    .B(_0242_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__nand2_2 _0696_ (
    .A(_0206_),
    .B(_0207_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__a21o_2 _0697_ (
    .A1(_0244_),
    .A2(_0228_),
    .B1(_0214_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__or3_2 _0698_ (
    .A(_0205_),
    .B(_0208_),
    .C(_0237_),
    .X(_0246_)
  );
  sky130_fd_sc_hd__a211o_2 _0699_ (
    .A1(_0217_),
    .A2(_0218_),
    .B1(_0219_),
    .C1(_0227_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__a21oi_2 _0700_ (
    .A1(_0227_),
    .A2(_0219_),
    .B1(_0184_),
    .Y(_0248_)
  );
  sky130_fd_sc_hd__a32o_2 _0701_ (
    .A1(_0184_),
    .A2(_0245_),
    .A3(_0246_),
    .B1(_0247_),
    .B2(_0248_),
    .X(_0249_)
  );
  sky130_fd_sc_hd__o211a_2 _0702_ (
    .A1(\TEMP[1] ),
    .A2(_0242_),
    .B1(_0249_),
    .C1(\TEMP[0] ),
    .X(_0250_)
  );
  sky130_fd_sc_hd__a211o_2 _0703_ (
    .A1(\TEMP[3] ),
    .A2(_0222_),
    .B1(_0233_),
    .C1(\TEMP[2] ),
    .X(_0251_)
  );
  sky130_fd_sc_hd__o41a_2 _0704_ (
    .A1(_0234_),
    .A2(_0235_),
    .A3(_0243_),
    .A4(_0250_),
    .B1(_0251_),
    .X(_0252_)
  );
  sky130_fd_sc_hd__nand2_2 _0705_ (
    .A(_0217_),
    .B(_0230_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__nand2_2 _0706_ (
    .A(_0212_),
    .B(_0213_),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__a21oi_2 _0707_ (
    .A1(_0239_),
    .A2(_0225_),
    .B1(_0227_),
    .Y(_0255_)
  );
  sky130_fd_sc_hd__nor2_2 _0708_ (
    .A(_0218_),
    .B(_0240_),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__a31o_2 _0709_ (
    .A1(_0253_),
    .A2(_0254_),
    .A3(_0255_),
    .B1(_0256_),
    .X(_0257_)
  );
  sky130_fd_sc_hd__nand3b_2 _0710_ (
    .A_N(_0205_),
    .B(_0230_),
    .C(_0218_),
    .Y(_0258_)
  );
  sky130_fd_sc_hd__o21ai_2 _0711_ (
    .A1(_0208_),
    .A2(_0237_),
    .B1(_0227_),
    .Y(_0259_)
  );
  sky130_fd_sc_hd__and3_2 _0712_ (
    .A(_0220_),
    .B(_0258_),
    .C(_0259_),
    .X(_0260_)
  );
  sky130_fd_sc_hd__o21ba_2 _0713_ (
    .A1(_0220_),
    .A2(_0257_),
    .B1_N(_0260_),
    .X(_0261_)
  );
  sky130_fd_sc_hd__or2_2 _0714_ (
    .A(_0189_),
    .B(_0208_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__and2_2 _0715_ (
    .A(_0244_),
    .B(_0228_),
    .X(_0263_)
  );
  sky130_fd_sc_hd__mux4_2 _0716_ (
    .A0(_0224_),
    .A1(_0262_),
    .A2(_0254_),
    .A3(_0263_),
    .S0(_0184_),
    .S1(_0227_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__and2_2 _0717_ (
    .A(\TEMP[6] ),
    .B(_0264_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__o21ai_2 _0718_ (
    .A1(_0230_),
    .A2(_0218_),
    .B1(_0217_),
    .Y(_0266_)
  );
  sky130_fd_sc_hd__a21boi_2 _0719_ (
    .A1(_0230_),
    .A2(_0218_),
    .B1_N(_0205_),
    .Y(_0267_)
  );
  sky130_fd_sc_hd__nand2_2 _0720_ (
    .A(_0217_),
    .B(_0267_),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__a32oi_2 _0721_ (
    .A1(_0220_),
    .A2(_0266_),
    .A3(_0229_),
    .B1(_0268_),
    .B2(_0226_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__o22ai_2 _0722_ (
    .A1(\TEMP[6] ),
    .A2(_0264_),
    .B1(_0269_),
    .B2(\TEMP[7] ),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__and2_2 _0723_ (
    .A(\TEMP[7] ),
    .B(_0269_),
    .X(_0271_)
  );
  sky130_fd_sc_hd__a2111o_2 _0724_ (
    .A1(\TEMP[5] ),
    .A2(_0261_),
    .B1(_0265_),
    .C1(_0270_),
    .D1(_0271_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__nor2_2 _0725_ (
    .A(_0231_),
    .B(_0237_),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__o211a_2 _0726_ (
    .A1(_0217_),
    .A2(_0209_),
    .B1(_0213_),
    .C1(_0227_),
    .X(_0274_)
  );
  sky130_fd_sc_hd__and4b_2 _0727_ (
    .A_N(_0205_),
    .B(_0217_),
    .C(_0230_),
    .D(_0218_),
    .X(_0275_)
  );
  sky130_fd_sc_hd__a211o_2 _0728_ (
    .A1(_0253_),
    .A2(_0258_),
    .B1(_0275_),
    .C1(_0184_),
    .X(_0276_)
  );
  sky130_fd_sc_hd__o31a_2 _0729_ (
    .A1(_0220_),
    .A2(_0273_),
    .A3(_0274_),
    .B1(_0276_),
    .X(_0277_)
  );
  sky130_fd_sc_hd__or2_2 _0730_ (
    .A(\TEMP[4] ),
    .B(_0277_),
    .X(_0278_)
  );
  sky130_fd_sc_hd__nand2_2 _0731_ (
    .A(\TEMP[4] ),
    .B(_0277_),
    .Y(_0279_)
  );
  sky130_fd_sc_hd__o211ai_2 _0732_ (
    .A1(\TEMP[5] ),
    .A2(_0261_),
    .B1(_0278_),
    .C1(_0279_),
    .Y(_0280_)
  );
  sky130_fd_sc_hd__a211o_2 _0733_ (
    .A1(_0223_),
    .A2(_0252_),
    .B1(_0272_),
    .C1(_0280_),
    .X(_0281_)
  );
  sky130_fd_sc_hd__inv_2 _0734_ (
    .A(_0270_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__o21a_2 _0735_ (
    .A1(\TEMP[5] ),
    .A2(_0261_),
    .B1(_0278_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__o22a_2 _0736_ (
    .A1(_0282_),
    .A2(_0271_),
    .B1(_0272_),
    .B2(_0283_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__nor2_2 _0737_ (
    .A(_0227_),
    .B(_0219_),
    .Y(_0285_)
  );
  sky130_fd_sc_hd__nand2_2 _0738_ (
    .A(_0220_),
    .B(_0229_),
    .Y(_0286_)
  );
  sky130_fd_sc_hd__o32a_2 _0739_ (
    .A1(_0220_),
    .A2(_0267_),
    .A3(_0255_),
    .B1(_0285_),
    .B2(_0286_),
    .X(_0287_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _0740_ (
    .A1_N(_0281_),
    .A2_N(_0284_),
    .B1(_0287_),
    .B2(\TEMP[10] ),
    .X(_0288_)
  );
  sky130_fd_sc_hd__nand2_2 _0741_ (
    .A(\TEMP[10] ),
    .B(_0287_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__inv_2 _0742_ (
    .A(_0289_),
    .Y(_0290_)
  );
  sky130_fd_sc_hd__and2_2 _0743_ (
    .A(_0177_),
    .B(_0181_),
    .X(_0291_)
  );
  sky130_fd_sc_hd__o211ai_2 _0744_ (
    .A1(_0288_),
    .A2(_0290_),
    .B1(_0291_),
    .C1(\STATO[0] ),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__inv_2 _0745_ (
    .A(_0292_),
    .Y(_0293_)
  );
  sky130_fd_sc_hd__o22ai_2 _0746_ (
    .A1(\TEMP[1] ),
    .A2(_0242_),
    .B1(_0249_),
    .B2(\TEMP[0] ),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__a211o_2 _0747_ (
    .A1(\TEMP[0] ),
    .A2(_0249_),
    .B1(_0294_),
    .C1(_0243_),
    .X(_0295_)
  );
  sky130_fd_sc_hd__nor2_2 _0748_ (
    .A(_0272_),
    .B(_0280_),
    .Y(_0296_)
  );
  sky130_fd_sc_hd__nor2_2 _0749_ (
    .A(_0234_),
    .B(_0235_),
    .Y(_0297_)
  );
  sky130_fd_sc_hd__and4bb_2 _0750_ (
    .A_N(_0290_),
    .B_N(_0295_),
    .C(_0296_),
    .D(_0297_),
    .X(_0298_)
  );
  sky130_fd_sc_hd__nor2_2 _0751_ (
    .A(_0181_),
    .B(START),
    .Y(_0299_)
  );
  sky130_fd_sc_hd__a311o_2 _0752_ (
    .A1(_0181_),
    .A2(_0288_),
    .A3(_0298_),
    .B1(_0299_),
    .C1(_0178_),
    .X(_0300_)
  );
  sky130_fd_sc_hd__mux2_2 _0753_ (
    .A0(_0293_),
    .A1(FLAG),
    .S(_0300_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__buf_1 _0754_ (
    .A(_0301_),
    .X(_0173_)
  );
  sky130_fd_sc_hd__inv_2 _0755_ (
    .A(_0287_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__nor2_2 _0756_ (
    .A(\MAX[7] ),
    .B(_0269_),
    .Y(_0303_)
  );
  sky130_fd_sc_hd__or2_2 _0757_ (
    .A(\MAX[4] ),
    .B(_0277_),
    .X(_0304_)
  );
  sky130_fd_sc_hd__buf_1 _0758_ (
    .A(\MAX[0] ),
    .X(_0305_)
  );
  sky130_fd_sc_hd__o211a_2 _0759_ (
    .A1(\MAX[1] ),
    .A2(_0242_),
    .B1(_0249_),
    .C1(_0305_),
    .X(_0306_)
  );
  sky130_fd_sc_hd__a22o_2 _0760_ (
    .A1(\MAX[2] ),
    .A2(_0233_),
    .B1(_0242_),
    .B2(\MAX[1] ),
    .X(_0307_)
  );
  sky130_fd_sc_hd__or2_2 _0761_ (
    .A(\MAX[3] ),
    .B(_0222_),
    .X(_0308_)
  );
  sky130_fd_sc_hd__o221a_2 _0762_ (
    .A1(\MAX[2] ),
    .A2(_0233_),
    .B1(_0306_),
    .B2(_0307_),
    .C1(_0308_),
    .X(_0309_)
  );
  sky130_fd_sc_hd__a221o_2 _0763_ (
    .A1(\MAX[4] ),
    .A2(_0277_),
    .B1(_0222_),
    .B2(\MAX[3] ),
    .C1(_0309_),
    .X(_0310_)
  );
  sky130_fd_sc_hd__a22o_2 _0764_ (
    .A1(\MAX[5] ),
    .A2(_0261_),
    .B1(_0304_),
    .B2(_0310_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__o22a_2 _0765_ (
    .A1(\MAX[6] ),
    .A2(_0264_),
    .B1(_0261_),
    .B2(\MAX[5] ),
    .X(_0312_)
  );
  sky130_fd_sc_hd__a22o_2 _0766_ (
    .A1(\MAX[6] ),
    .A2(_0264_),
    .B1(_0269_),
    .B2(\MAX[7] ),
    .X(_0313_)
  );
  sky130_fd_sc_hd__a21oi_2 _0767_ (
    .A1(_0311_),
    .A2(_0312_),
    .B1(_0313_),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__o22a_2 _0768_ (
    .A1(\MAX[10] ),
    .A2(_0287_),
    .B1(_0303_),
    .B2(_0314_),
    .X(_0315_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _0769_ (
    .A1_N(_0288_),
    .A2_N(_0290_),
    .B1(\MAX[10] ),
    .B2(_0287_),
    .X(_0316_)
  );
  sky130_fd_sc_hd__or3_2 _0770_ (
    .A(_0298_),
    .B(_0315_),
    .C(_0316_),
    .X(_0317_)
  );
  sky130_fd_sc_hd__a21boi_2 _0771_ (
    .A1(\STATO[0] ),
    .A2(_0317_),
    .B1_N(_0291_),
    .Y(_0318_)
  );
  sky130_fd_sc_hd__mux2_2 _0772_ (
    .A0(\MAX[10] ),
    .A1(_0302_),
    .S(_0318_),
    .X(_0319_)
  );
  sky130_fd_sc_hd__buf_1 _0773_ (
    .A(_0319_),
    .X(_0172_)
  );
  sky130_fd_sc_hd__inv_2 _0774_ (
    .A(_0269_),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__mux2_2 _0775_ (
    .A0(\MAX[7] ),
    .A1(_0320_),
    .S(_0318_),
    .X(_0321_)
  );
  sky130_fd_sc_hd__buf_1 _0776_ (
    .A(_0321_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__inv_2 _0777_ (
    .A(_0264_),
    .Y(_0322_)
  );
  sky130_fd_sc_hd__mux2_2 _0778_ (
    .A0(\MAX[6] ),
    .A1(_0322_),
    .S(_0318_),
    .X(_0323_)
  );
  sky130_fd_sc_hd__buf_1 _0779_ (
    .A(_0323_),
    .X(_0170_)
  );
  sky130_fd_sc_hd__inv_2 _0780_ (
    .A(_0261_),
    .Y(_0324_)
  );
  sky130_fd_sc_hd__mux2_2 _0781_ (
    .A0(\MAX[5] ),
    .A1(_0324_),
    .S(_0318_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__buf_1 _0782_ (
    .A(_0325_),
    .X(_0169_)
  );
  sky130_fd_sc_hd__inv_2 _0783_ (
    .A(_0277_),
    .Y(_0326_)
  );
  sky130_fd_sc_hd__mux2_2 _0784_ (
    .A0(\MAX[4] ),
    .A1(_0326_),
    .S(_0318_),
    .X(_0327_)
  );
  sky130_fd_sc_hd__buf_1 _0785_ (
    .A(_0327_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__inv_2 _0786_ (
    .A(_0222_),
    .Y(_0328_)
  );
  sky130_fd_sc_hd__mux2_2 _0787_ (
    .A0(\MAX[3] ),
    .A1(_0328_),
    .S(_0318_),
    .X(_0329_)
  );
  sky130_fd_sc_hd__buf_1 _0788_ (
    .A(_0329_),
    .X(_0167_)
  );
  sky130_fd_sc_hd__inv_2 _0789_ (
    .A(_0233_),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__mux2_2 _0790_ (
    .A0(\MAX[2] ),
    .A1(_0330_),
    .S(_0318_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__buf_1 _0791_ (
    .A(_0331_),
    .X(_0166_)
  );
  sky130_fd_sc_hd__inv_2 _0792_ (
    .A(_0242_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__mux2_2 _0793_ (
    .A0(\MAX[1] ),
    .A1(_0332_),
    .S(_0318_),
    .X(_0333_)
  );
  sky130_fd_sc_hd__buf_1 _0794_ (
    .A(_0333_),
    .X(_0165_)
  );
  sky130_fd_sc_hd__inv_2 _0795_ (
    .A(_0249_),
    .Y(_0334_)
  );
  sky130_fd_sc_hd__mux2_2 _0796_ (
    .A0(_0305_),
    .A1(_0334_),
    .S(_0318_),
    .X(_0335_)
  );
  sky130_fd_sc_hd__buf_1 _0797_ (
    .A(_0335_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__buf_1 _0798_ (
    .A(_0291_),
    .X(_0336_)
  );
  sky130_fd_sc_hd__mux2_2 _0799_ (
    .A0(\TEMP[10] ),
    .A1(_0302_),
    .S(_0336_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__buf_1 _0800_ (
    .A(_0337_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__mux2_2 _0801_ (
    .A0(\TEMP[7] ),
    .A1(_0320_),
    .S(_0336_),
    .X(_0338_)
  );
  sky130_fd_sc_hd__buf_1 _0802_ (
    .A(_0338_),
    .X(_0162_)
  );
  sky130_fd_sc_hd__mux2_2 _0803_ (
    .A0(\TEMP[6] ),
    .A1(_0322_),
    .S(_0336_),
    .X(_0339_)
  );
  sky130_fd_sc_hd__buf_1 _0804_ (
    .A(_0339_),
    .X(_0161_)
  );
  sky130_fd_sc_hd__mux2_2 _0805_ (
    .A0(\TEMP[5] ),
    .A1(_0324_),
    .S(_0336_),
    .X(_0340_)
  );
  sky130_fd_sc_hd__buf_1 _0806_ (
    .A(_0340_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__mux2_2 _0807_ (
    .A0(\TEMP[4] ),
    .A1(_0326_),
    .S(_0336_),
    .X(_0341_)
  );
  sky130_fd_sc_hd__buf_1 _0808_ (
    .A(_0341_),
    .X(_0159_)
  );
  sky130_fd_sc_hd__mux2_2 _0809_ (
    .A0(\TEMP[3] ),
    .A1(_0328_),
    .S(_0336_),
    .X(_0342_)
  );
  sky130_fd_sc_hd__buf_1 _0810_ (
    .A(_0342_),
    .X(_0158_)
  );
  sky130_fd_sc_hd__mux2_2 _0811_ (
    .A0(\TEMP[2] ),
    .A1(_0330_),
    .S(_0336_),
    .X(_0343_)
  );
  sky130_fd_sc_hd__buf_1 _0812_ (
    .A(_0343_),
    .X(_0157_)
  );
  sky130_fd_sc_hd__mux2_2 _0813_ (
    .A0(\TEMP[1] ),
    .A1(_0332_),
    .S(_0336_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__buf_1 _0814_ (
    .A(_0344_),
    .X(_0156_)
  );
  sky130_fd_sc_hd__mux2_2 _0815_ (
    .A0(\TEMP[0] ),
    .A1(_0334_),
    .S(_0336_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__buf_1 _0816_ (
    .A(_0345_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__or3_2 _0817_ (
    .A(_0181_),
    .B(_0176_),
    .C(_0178_),
    .X(_0346_)
  );
  sky130_fd_sc_hd__buf_1 _0818_ (
    .A(_0346_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__buf_1 _0819_ (
    .A(_0347_),
    .X(_0348_)
  );
  sky130_fd_sc_hd__and3_2 _0820_ (
    .A(\MAR[29] ),
    .B(\MAR[28] ),
    .C(\MAR[27] ),
    .X(_0349_)
  );
  sky130_fd_sc_hd__or2_2 _0821_ (
    .A(_0179_),
    .B(_0202_),
    .X(_0350_)
  );
  sky130_fd_sc_hd__buf_1 _0822_ (
    .A(_0350_),
    .X(_0351_)
  );
  sky130_fd_sc_hd__and2_2 _0823_ (
    .A(\MAR[15] ),
    .B(\MAR[14] ),
    .X(_0352_)
  );
  sky130_fd_sc_hd__and3_2 _0824_ (
    .A(\MAR[19] ),
    .B(\MAR[18] ),
    .C(\MAR[17] ),
    .X(_0353_)
  );
  sky130_fd_sc_hd__and2_2 _0825_ (
    .A(\MAR[13] ),
    .B(\MAR[12] ),
    .X(_0354_)
  );
  sky130_fd_sc_hd__and4_2 _0826_ (
    .A(\MAR[3] ),
    .B(\MAR[2] ),
    .C(_0206_),
    .D(_0207_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__and3_2 _0827_ (
    .A(\MAR[6] ),
    .B(\MAR[5] ),
    .C(\MAR[4] ),
    .X(_0356_)
  );
  sky130_fd_sc_hd__and3_2 _0828_ (
    .A(\MAR[7] ),
    .B(_0355_),
    .C(_0356_),
    .X(_0357_)
  );
  sky130_fd_sc_hd__and3_2 _0829_ (
    .A(\MAR[9] ),
    .B(\MAR[8] ),
    .C(_0357_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__and4_2 _0830_ (
    .A(\MAR[11] ),
    .B(\MAR[10] ),
    .C(_0354_),
    .D(_0358_),
    .X(_0359_)
  );
  sky130_fd_sc_hd__and4_2 _0831_ (
    .A(\MAR[16] ),
    .B(_0352_),
    .C(_0353_),
    .D(_0359_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__and4_2 _0832_ (
    .A(\MAR[21] ),
    .B(\MAR[20] ),
    .C(_0351_),
    .D(_0360_),
    .X(_0361_)
  );
  sky130_fd_sc_hd__and3_2 _0833_ (
    .A(\MAR[23] ),
    .B(\MAR[22] ),
    .C(_0361_),
    .X(_0362_)
  );
  sky130_fd_sc_hd__and2_2 _0834_ (
    .A(\MAR[24] ),
    .B(_0362_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__and3_2 _0835_ (
    .A(\MAR[26] ),
    .B(\MAR[25] ),
    .C(_0363_),
    .X(_0364_)
  );
  sky130_fd_sc_hd__and2_2 _0836_ (
    .A(_0349_),
    .B(_0364_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__nand2_2 _0837_ (
    .A(\MAR[30] ),
    .B(_0365_),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__and2b_2 _0838_ (
    .A_N(_0200_),
    .B(_0364_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__and4b_2 _0839_ (
    .A_N(\MAR[31] ),
    .B(\MAR[30] ),
    .C(_0349_),
    .D(_0367_),
    .X(_0368_)
  );
  sky130_fd_sc_hd__a31o_2 _0840_ (
    .A1(\MAR[31] ),
    .A2(_0348_),
    .A3(_0366_),
    .B1(_0368_),
    .X(_0154_)
  );
  sky130_fd_sc_hd__buf_1 _0841_ (
    .A(_0347_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__or2_2 _0842_ (
    .A(\MAR[30] ),
    .B(_0365_),
    .X(_0370_)
  );
  sky130_fd_sc_hd__and3_2 _0843_ (
    .A(_0369_),
    .B(_0366_),
    .C(_0370_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__buf_1 _0844_ (
    .A(_0371_),
    .X(_0153_)
  );
  sky130_fd_sc_hd__inv_2 _0845_ (
    .A(_0365_),
    .Y(_0372_)
  );
  sky130_fd_sc_hd__a31o_2 _0846_ (
    .A1(\MAR[28] ),
    .A2(\MAR[27] ),
    .A3(_0364_),
    .B1(\MAR[29] ),
    .X(_0373_)
  );
  sky130_fd_sc_hd__and3_2 _0847_ (
    .A(_0369_),
    .B(_0372_),
    .C(_0373_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__buf_1 _0848_ (
    .A(_0374_),
    .X(_0152_)
  );
  sky130_fd_sc_hd__a21oi_2 _0849_ (
    .A1(\MAR[27] ),
    .A2(_0364_),
    .B1(\MAR[28] ),
    .Y(_0375_)
  );
  sky130_fd_sc_hd__a31o_2 _0850_ (
    .A1(\MAR[28] ),
    .A2(\MAR[27] ),
    .A3(_0364_),
    .B1(_0180_),
    .X(_0376_)
  );
  sky130_fd_sc_hd__nor2_2 _0851_ (
    .A(_0375_),
    .B(_0376_),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__nor2_2 _0852_ (
    .A(_0179_),
    .B(_0364_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__mux2_2 _0853_ (
    .A0(_0367_),
    .A1(_0377_),
    .S(\MAR[27] ),
    .X(_0378_)
  );
  sky130_fd_sc_hd__buf_1 _0854_ (
    .A(_0378_),
    .X(_0150_)
  );
  sky130_fd_sc_hd__o211a_2 _0855_ (
    .A1(\MAR[26] ),
    .A2(_0363_),
    .B1(_0377_),
    .C1(_0196_),
    .X(_0149_)
  );
  sky130_fd_sc_hd__inv_2 _0856_ (
    .A(_0363_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__nor3_2 _0857_ (
    .A(\MAR[25] ),
    .B(_0200_),
    .C(_0379_),
    .Y(_0380_)
  );
  sky130_fd_sc_hd__a31o_2 _0858_ (
    .A1(\MAR[25] ),
    .A2(_0348_),
    .A3(_0379_),
    .B1(_0380_),
    .X(_0148_)
  );
  sky130_fd_sc_hd__or2_2 _0859_ (
    .A(\MAR[24] ),
    .B(_0362_),
    .X(_0381_)
  );
  sky130_fd_sc_hd__and3_2 _0860_ (
    .A(_0369_),
    .B(_0379_),
    .C(_0381_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__buf_1 _0861_ (
    .A(_0382_),
    .X(_0147_)
  );
  sky130_fd_sc_hd__buf_1 _0862_ (
    .A(_0179_),
    .X(_0383_)
  );
  sky130_fd_sc_hd__a21oi_2 _0863_ (
    .A1(\MAR[22] ),
    .A2(_0361_),
    .B1(\MAR[23] ),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__nor3_2 _0864_ (
    .A(_0383_),
    .B(_0362_),
    .C(_0384_),
    .Y(_0146_)
  );
  sky130_fd_sc_hd__nor2_2 _0865_ (
    .A(_0179_),
    .B(_0361_),
    .Y(_0385_)
  );
  sky130_fd_sc_hd__and2_2 _0866_ (
    .A(\MAR[21] ),
    .B(\MAR[20] ),
    .X(_0386_)
  );
  sky130_fd_sc_hd__and4b_2 _0867_ (
    .A_N(\MAR[22] ),
    .B(_0203_),
    .C(_0360_),
    .D(_0386_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__a21o_2 _0868_ (
    .A1(\MAR[22] ),
    .A2(_0385_),
    .B1(_0387_),
    .X(_0145_)
  );
  sky130_fd_sc_hd__a31o_2 _0869_ (
    .A1(\MAR[20] ),
    .A2(_0351_),
    .A3(_0360_),
    .B1(\MAR[21] ),
    .X(_0388_)
  );
  sky130_fd_sc_hd__and2_2 _0870_ (
    .A(_0385_),
    .B(_0388_),
    .X(_0389_)
  );
  sky130_fd_sc_hd__buf_1 _0871_ (
    .A(_0389_),
    .X(_0144_)
  );
  sky130_fd_sc_hd__and3_2 _0872_ (
    .A(\MAR[16] ),
    .B(_0352_),
    .C(_0353_),
    .X(_0390_)
  );
  sky130_fd_sc_hd__and4_2 _0873_ (
    .A(\MAR[11] ),
    .B(\MAR[9] ),
    .C(\MAR[8] ),
    .D(_0357_),
    .X(_0391_)
  );
  sky130_fd_sc_hd__and4_2 _0874_ (
    .A(\MAR[13] ),
    .B(\MAR[12] ),
    .C(\MAR[10] ),
    .D(_0391_),
    .X(_0392_)
  );
  sky130_fd_sc_hd__and3_2 _0875_ (
    .A(_0202_),
    .B(_0390_),
    .C(_0392_),
    .X(_0393_)
  );
  sky130_fd_sc_hd__nor2_2 _0876_ (
    .A(_0179_),
    .B(_0393_),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__mux2_2 _0877_ (
    .A0(_0393_),
    .A1(_0394_),
    .S(\MAR[20] ),
    .X(_0395_)
  );
  sky130_fd_sc_hd__buf_1 _0878_ (
    .A(_0395_),
    .X(_0143_)
  );
  sky130_fd_sc_hd__nand2_2 _0879_ (
    .A(_0351_),
    .B(_0392_),
    .Y(_0396_)
  );
  sky130_fd_sc_hd__inv_2 _0880_ (
    .A(_0396_),
    .Y(_0397_)
  );
  sky130_fd_sc_hd__and3_2 _0881_ (
    .A(\MAR[16] ),
    .B(_0352_),
    .C(_0397_),
    .X(_0398_)
  );
  sky130_fd_sc_hd__a31o_2 _0882_ (
    .A1(\MAR[18] ),
    .A2(\MAR[17] ),
    .A3(_0398_),
    .B1(\MAR[19] ),
    .X(_0399_)
  );
  sky130_fd_sc_hd__and2_2 _0883_ (
    .A(_0394_),
    .B(_0399_),
    .X(_0400_)
  );
  sky130_fd_sc_hd__buf_1 _0884_ (
    .A(_0400_),
    .X(_0142_)
  );
  sky130_fd_sc_hd__nand2_2 _0885_ (
    .A(\MAR[17] ),
    .B(_0398_),
    .Y(_0401_)
  );
  sky130_fd_sc_hd__and3_2 _0886_ (
    .A(\MAR[18] ),
    .B(_0346_),
    .C(_0401_),
    .X(_0402_)
  );
  sky130_fd_sc_hd__and3_2 _0887_ (
    .A(_0351_),
    .B(_0352_),
    .C(_0392_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__and2b_2 _0888_ (
    .A_N(_0200_),
    .B(_0403_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__and4b_2 _0889_ (
    .A_N(\MAR[18] ),
    .B(\MAR[17] ),
    .C(\MAR[16] ),
    .D(_0404_),
    .X(_0405_)
  );
  sky130_fd_sc_hd__or2_2 _0890_ (
    .A(_0402_),
    .B(_0405_),
    .X(_0406_)
  );
  sky130_fd_sc_hd__buf_1 _0891_ (
    .A(_0406_),
    .X(_0141_)
  );
  sky130_fd_sc_hd__or2_2 _0892_ (
    .A(\MAR[17] ),
    .B(_0398_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__and3_2 _0893_ (
    .A(_0347_),
    .B(_0401_),
    .C(_0407_),
    .X(_0408_)
  );
  sky130_fd_sc_hd__buf_1 _0894_ (
    .A(_0408_),
    .X(_0140_)
  );
  sky130_fd_sc_hd__nor2_2 _0895_ (
    .A(_0179_),
    .B(_0403_),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__mux2_2 _0896_ (
    .A0(_0404_),
    .A1(_0409_),
    .S(\MAR[16] ),
    .X(_0410_)
  );
  sky130_fd_sc_hd__buf_1 _0897_ (
    .A(_0410_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__o211a_2 _0898_ (
    .A1(\MAR[15] ),
    .A2(_0397_),
    .B1(_0409_),
    .C1(_0194_),
    .X(_0138_)
  );
  sky130_fd_sc_hd__and2_2 _0899_ (
    .A(_0203_),
    .B(_0392_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__nor2_2 _0900_ (
    .A(_0179_),
    .B(_0397_),
    .Y(_0412_)
  );
  sky130_fd_sc_hd__mux2_2 _0901_ (
    .A0(_0411_),
    .A1(_0412_),
    .S(\MAR[14] ),
    .X(_0413_)
  );
  sky130_fd_sc_hd__buf_1 _0902_ (
    .A(_0413_),
    .X(_0137_)
  );
  sky130_fd_sc_hd__and3_2 _0903_ (
    .A(\MAR[7] ),
    .B(_0355_),
    .C(_0356_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__and3_2 _0904_ (
    .A(\MAR[8] ),
    .B(_0351_),
    .C(_0414_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__and4_2 _0905_ (
    .A(\MAR[11] ),
    .B(\MAR[10] ),
    .C(\MAR[9] ),
    .D(_0415_),
    .X(_0416_)
  );
  sky130_fd_sc_hd__o211a_2 _0906_ (
    .A1(\MAR[13] ),
    .A2(_0416_),
    .B1(_0412_),
    .C1(_0193_),
    .X(_0136_)
  );
  sky130_fd_sc_hd__nor2_2 _0907_ (
    .A(_0180_),
    .B(_0416_),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__nor2_2 _0908_ (
    .A(\MAR[12] ),
    .B(_0200_),
    .Y(_0418_)
  );
  sky130_fd_sc_hd__o22a_2 _0909_ (
    .A1(\MAR[12] ),
    .A2(_0416_),
    .B1(_0417_),
    .B2(_0418_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__and2_2 _0910_ (
    .A(_0351_),
    .B(_0358_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__o211a_2 _0911_ (
    .A1(\MAR[11] ),
    .A2(_0419_),
    .B1(_0417_),
    .C1(_0195_),
    .X(_0134_)
  );
  sky130_fd_sc_hd__nor2_2 _0912_ (
    .A(\MAR[10] ),
    .B(_0200_),
    .Y(_0420_)
  );
  sky130_fd_sc_hd__nor2_2 _0913_ (
    .A(_0180_),
    .B(_0419_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__o22a_2 _0914_ (
    .A1(\MAR[10] ),
    .A2(_0419_),
    .B1(_0420_),
    .B2(_0421_),
    .X(_0133_)
  );
  sky130_fd_sc_hd__o21a_2 _0915_ (
    .A1(\MAR[9] ),
    .A2(_0415_),
    .B1(_0421_),
    .X(_0132_)
  );
  sky130_fd_sc_hd__nand2_2 _0916_ (
    .A(_0351_),
    .B(_0357_),
    .Y(_0422_)
  );
  sky130_fd_sc_hd__and3b_2 _0917_ (
    .A_N(\MAR[8] ),
    .B(_0203_),
    .C(_0357_),
    .X(_0423_)
  );
  sky130_fd_sc_hd__a31o_2 _0918_ (
    .A1(\MAR[8] ),
    .A2(_0369_),
    .A3(_0422_),
    .B1(_0423_),
    .X(_0131_)
  );
  sky130_fd_sc_hd__and3_2 _0919_ (
    .A(_0355_),
    .B(_0351_),
    .C(_0356_),
    .X(_0424_)
  );
  sky130_fd_sc_hd__or2_2 _0920_ (
    .A(\MAR[7] ),
    .B(_0424_),
    .X(_0425_)
  );
  sky130_fd_sc_hd__and3_2 _0921_ (
    .A(_0347_),
    .B(_0422_),
    .C(_0425_),
    .X(_0426_)
  );
  sky130_fd_sc_hd__buf_1 _0922_ (
    .A(_0426_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__inv_2 _0923_ (
    .A(_0424_),
    .Y(_0427_)
  );
  sky130_fd_sc_hd__and3_2 _0924_ (
    .A(_0220_),
    .B(_0355_),
    .C(_0351_),
    .X(_0428_)
  );
  sky130_fd_sc_hd__a21o_2 _0925_ (
    .A1(\MAR[5] ),
    .A2(_0428_),
    .B1(\MAR[6] ),
    .X(_0429_)
  );
  sky130_fd_sc_hd__and3_2 _0926_ (
    .A(_0347_),
    .B(_0427_),
    .C(_0429_),
    .X(_0430_)
  );
  sky130_fd_sc_hd__buf_1 _0927_ (
    .A(_0430_),
    .X(_0129_)
  );
  sky130_fd_sc_hd__o21ai_2 _0928_ (
    .A1(\MAR[5] ),
    .A2(_0428_),
    .B1(_0369_),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__a21oi_2 _0929_ (
    .A1(\MAR[5] ),
    .A2(_0428_),
    .B1(_0431_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__nor2_2 _0930_ (
    .A(_0179_),
    .B(_0203_),
    .Y(_0432_)
  );
  sky130_fd_sc_hd__nor2_2 _0931_ (
    .A(_0190_),
    .B(_0432_),
    .Y(_0433_)
  );
  sky130_fd_sc_hd__o21ai_2 _0932_ (
    .A1(_0220_),
    .A2(_0433_),
    .B1(_0369_),
    .Y(_0434_)
  );
  sky130_fd_sc_hd__nor2_2 _0933_ (
    .A(_0428_),
    .B(_0434_),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__a32o_2 _0934_ (
    .A1(_0190_),
    .A2(_0203_),
    .A3(_0231_),
    .B1(_0432_),
    .B2(_0227_),
    .X(_0126_)
  );
  sky130_fd_sc_hd__nor2_2 _0935_ (
    .A(_0189_),
    .B(_0208_),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__a22o_2 _0936_ (
    .A1(_0203_),
    .A2(_0435_),
    .B1(_0432_),
    .B2(_0217_),
    .X(_0125_)
  );
  sky130_fd_sc_hd__inv_2 _0937_ (
    .A(_0237_),
    .Y(_0436_)
  );
  sky130_fd_sc_hd__a32o_2 _0938_ (
    .A1(_0203_),
    .A2(_0244_),
    .A3(_0436_),
    .B1(_0432_),
    .B2(_0230_),
    .X(_0124_)
  );
  sky130_fd_sc_hd__mux2_2 _0939_ (
    .A0(_0203_),
    .A1(_0432_),
    .S(_0218_),
    .X(_0437_)
  );
  sky130_fd_sc_hd__buf_1 _0940_ (
    .A(_0437_),
    .X(_0123_)
  );
  sky130_fd_sc_hd__inv_2 _0941_ (
    .A(FLAG),
    .Y(_0438_)
  );
  sky130_fd_sc_hd__a211oi_2 _0942_ (
    .A1(_0438_),
    .A2(_0181_),
    .B1(_0178_),
    .C1(_0299_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__and3_2 _0943_ (
    .A(\NUM[20] ),
    .B(\NUM[19] ),
    .C(\NUM[18] ),
    .X(_0440_)
  );
  sky130_fd_sc_hd__and3_2 _0944_ (
    .A(\NUM[23] ),
    .B(\NUM[22] ),
    .C(\NUM[21] ),
    .X(_0441_)
  );
  sky130_fd_sc_hd__and2_2 _0945_ (
    .A(_0440_),
    .B(_0441_),
    .X(_0442_)
  );
  sky130_fd_sc_hd__and4_2 _0946_ (
    .A(\NUM[6] ),
    .B(\NUM[5] ),
    .C(\NUM[1] ),
    .D(\NUM[0] ),
    .X(_0443_)
  );
  sky130_fd_sc_hd__and4_2 _0947_ (
    .A(\NUM[4] ),
    .B(\NUM[3] ),
    .C(\NUM[2] ),
    .D(_0443_),
    .X(_0444_)
  );
  sky130_fd_sc_hd__and4_2 _0948_ (
    .A(\NUM[16] ),
    .B(\NUM[15] ),
    .C(\NUM[14] ),
    .D(\NUM[13] ),
    .X(_0445_)
  );
  sky130_fd_sc_hd__and3_2 _0949_ (
    .A(\NUM[17] ),
    .B(\NUM[12] ),
    .C(_0445_),
    .X(_0446_)
  );
  sky130_fd_sc_hd__and3_2 _0950_ (
    .A(\NUM[10] ),
    .B(\NUM[9] ),
    .C(\NUM[8] ),
    .X(_0447_)
  );
  sky130_fd_sc_hd__and2_2 _0951_ (
    .A(\NUM[7] ),
    .B(_0447_),
    .X(_0448_)
  );
  sky130_fd_sc_hd__and3_2 _0952_ (
    .A(_0444_),
    .B(_0446_),
    .C(_0448_),
    .X(_0449_)
  );
  sky130_fd_sc_hd__and3_2 _0953_ (
    .A(\NUM[25] ),
    .B(\NUM[11] ),
    .C(_0449_),
    .X(_0450_)
  );
  sky130_fd_sc_hd__and3_2 _0954_ (
    .A(\NUM[24] ),
    .B(_0442_),
    .C(_0450_),
    .X(_0451_)
  );
  sky130_fd_sc_hd__and4_2 _0955_ (
    .A(\NUM[26] ),
    .B(_0292_),
    .C(_0439_),
    .D(_0451_),
    .X(_0452_)
  );
  sky130_fd_sc_hd__and4_2 _0956_ (
    .A(\NUM[29] ),
    .B(\NUM[28] ),
    .C(\NUM[27] ),
    .D(_0452_),
    .X(_0453_)
  );
  sky130_fd_sc_hd__a21oi_2 _0957_ (
    .A1(\NUM[30] ),
    .A2(_0453_),
    .B1(\NUM[31] ),
    .Y(_0454_)
  );
  sky130_fd_sc_hd__and3_2 _0958_ (
    .A(\NUM[11] ),
    .B(\NUM[7] ),
    .C(_0447_),
    .X(_0455_)
  );
  sky130_fd_sc_hd__and4_2 _0959_ (
    .A(\NUM[25] ),
    .B(\NUM[24] ),
    .C(\NUM[21] ),
    .D(\NUM[18] ),
    .X(_0456_)
  );
  sky130_fd_sc_hd__and4_2 _0960_ (
    .A(\NUM[23] ),
    .B(\NUM[22] ),
    .C(\NUM[20] ),
    .D(\NUM[19] ),
    .X(_0457_)
  );
  sky130_fd_sc_hd__and4_2 _0961_ (
    .A(_0455_),
    .B(_0446_),
    .C(_0456_),
    .D(_0457_),
    .X(_0458_)
  );
  sky130_fd_sc_hd__and4_2 _0962_ (
    .A(_0292_),
    .B(_0439_),
    .C(_0444_),
    .D(_0458_),
    .X(_0459_)
  );
  sky130_fd_sc_hd__and4_2 _0963_ (
    .A(\NUM[28] ),
    .B(\NUM[27] ),
    .C(\NUM[26] ),
    .D(_0459_),
    .X(_0460_)
  );
  sky130_fd_sc_hd__a41o_2 _0964_ (
    .A1(\NUM[31] ),
    .A2(\NUM[30] ),
    .A3(\NUM[29] ),
    .A4(_0460_),
    .B1(_0180_),
    .X(_0461_)
  );
  sky130_fd_sc_hd__nor2_2 _0965_ (
    .A(_0454_),
    .B(_0461_),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__a31o_2 _0966_ (
    .A1(\NUM[30] ),
    .A2(\NUM[29] ),
    .A3(_0460_),
    .B1(_0180_),
    .X(_0462_)
  );
  sky130_fd_sc_hd__o21ba_2 _0967_ (
    .A1(\NUM[30] ),
    .A2(_0453_),
    .B1_N(_0462_),
    .X(_0121_)
  );
  sky130_fd_sc_hd__a21oi_2 _0968_ (
    .A1(\NUM[29] ),
    .A2(_0460_),
    .B1(_0383_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__o21a_2 _0969_ (
    .A1(\NUM[29] ),
    .A2(_0460_),
    .B1(_0463_),
    .X(_0120_)
  );
  sky130_fd_sc_hd__inv_2 _0970_ (
    .A(\NUM[28] ),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__and3_2 _0971_ (
    .A(_0292_),
    .B(_0439_),
    .C(_0444_),
    .X(_0465_)
  );
  sky130_fd_sc_hd__and3_2 _0972_ (
    .A(\NUM[25] ),
    .B(\NUM[24] ),
    .C(\NUM[11] ),
    .X(_0466_)
  );
  sky130_fd_sc_hd__and4_2 _0973_ (
    .A(_0446_),
    .B(_0442_),
    .C(_0448_),
    .D(_0466_),
    .X(_0467_)
  );
  sky130_fd_sc_hd__and3_2 _0974_ (
    .A(\NUM[26] ),
    .B(_0465_),
    .C(_0467_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__nand2_2 _0975_ (
    .A(\NUM[27] ),
    .B(_0468_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__a211oi_2 _0976_ (
    .A1(_0464_),
    .A2(_0469_),
    .B1(_0460_),
    .C1(_0383_),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__o211a_2 _0977_ (
    .A1(\NUM[27] ),
    .A2(_0468_),
    .B1(_0469_),
    .C1(_0348_),
    .X(_0118_)
  );
  sky130_fd_sc_hd__o21ai_2 _0978_ (
    .A1(\NUM[26] ),
    .A2(_0459_),
    .B1(_0369_),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__nor2_2 _0979_ (
    .A(_0468_),
    .B(_0470_),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__and4_2 _0980_ (
    .A(_0292_),
    .B(_0439_),
    .C(_0444_),
    .D(_0448_),
    .X(_0471_)
  );
  sky130_fd_sc_hd__and4_2 _0981_ (
    .A(\NUM[11] ),
    .B(_0446_),
    .C(_0440_),
    .D(_0471_),
    .X(_0472_)
  );
  sky130_fd_sc_hd__and3_2 _0982_ (
    .A(\NUM[24] ),
    .B(_0441_),
    .C(_0472_),
    .X(_0473_)
  );
  sky130_fd_sc_hd__nand2_2 _0983_ (
    .A(_0465_),
    .B(_0467_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__o211a_2 _0984_ (
    .A1(\NUM[25] ),
    .A2(_0473_),
    .B1(_0474_),
    .C1(_0348_),
    .X(_0116_)
  );
  sky130_fd_sc_hd__inv_2 _0985_ (
    .A(\NUM[24] ),
    .Y(_0475_)
  );
  sky130_fd_sc_hd__and3_2 _0986_ (
    .A(\NUM[11] ),
    .B(_0446_),
    .C(_0471_),
    .X(_0476_)
  );
  sky130_fd_sc_hd__nand2_2 _0987_ (
    .A(_0442_),
    .B(_0476_),
    .Y(_0477_)
  );
  sky130_fd_sc_hd__a211oi_2 _0988_ (
    .A1(_0475_),
    .A2(_0477_),
    .B1(_0473_),
    .C1(_0383_),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__and3_2 _0989_ (
    .A(\NUM[22] ),
    .B(\NUM[21] ),
    .C(_0472_),
    .X(_0478_)
  );
  sky130_fd_sc_hd__o211a_2 _0990_ (
    .A1(\NUM[23] ),
    .A2(_0478_),
    .B1(_0477_),
    .C1(_0348_),
    .X(_0114_)
  );
  sky130_fd_sc_hd__inv_2 _0991_ (
    .A(\NUM[22] ),
    .Y(_0479_)
  );
  sky130_fd_sc_hd__nand2_2 _0992_ (
    .A(\NUM[21] ),
    .B(_0472_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__a211oi_2 _0993_ (
    .A1(_0479_),
    .A2(_0480_),
    .B1(_0478_),
    .C1(_0383_),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__o211a_2 _0994_ (
    .A1(\NUM[21] ),
    .A2(_0472_),
    .B1(_0480_),
    .C1(_0348_),
    .X(_0112_)
  );
  sky130_fd_sc_hd__and3_2 _0995_ (
    .A(\NUM[19] ),
    .B(\NUM[18] ),
    .C(_0476_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__nand2_2 _0996_ (
    .A(_0440_),
    .B(_0476_),
    .Y(_0482_)
  );
  sky130_fd_sc_hd__o211a_2 _0997_ (
    .A1(\NUM[20] ),
    .A2(_0481_),
    .B1(_0482_),
    .C1(_0348_),
    .X(_0111_)
  );
  sky130_fd_sc_hd__and4_2 _0998_ (
    .A(_0292_),
    .B(_0439_),
    .C(_0444_),
    .D(_0455_),
    .X(_0483_)
  );
  sky130_fd_sc_hd__a31o_2 _0999_ (
    .A1(\NUM[18] ),
    .A2(_0446_),
    .A3(_0483_),
    .B1(\NUM[19] ),
    .X(_0484_)
  );
  sky130_fd_sc_hd__nor3b_2 _1000_ (
    .A(_0383_),
    .B(_0481_),
    .C_N(_0484_),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__nand2_2 _1001_ (
    .A(\NUM[18] ),
    .B(_0476_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__o211a_2 _1002_ (
    .A1(\NUM[18] ),
    .A2(_0476_),
    .B1(_0485_),
    .C1(_0348_),
    .X(_0109_)
  );
  sky130_fd_sc_hd__inv_2 _1003_ (
    .A(_0476_),
    .Y(_0486_)
  );
  sky130_fd_sc_hd__a31o_2 _1004_ (
    .A1(\NUM[12] ),
    .A2(_0445_),
    .A3(_0483_),
    .B1(\NUM[17] ),
    .X(_0487_)
  );
  sky130_fd_sc_hd__and3_2 _1005_ (
    .A(_0347_),
    .B(_0486_),
    .C(_0487_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__buf_1 _1006_ (
    .A(_0488_),
    .X(_0108_)
  );
  sky130_fd_sc_hd__inv_2 _1007_ (
    .A(\NUM[15] ),
    .Y(_0489_)
  );
  sky130_fd_sc_hd__nand4_2 _1008_ (
    .A(\NUM[14] ),
    .B(\NUM[13] ),
    .C(\NUM[12] ),
    .D(_0483_),
    .Y(_0490_)
  );
  sky130_fd_sc_hd__nor2_2 _1009_ (
    .A(_0489_),
    .B(_0490_),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__a31o_2 _1010_ (
    .A1(\NUM[12] ),
    .A2(_0445_),
    .A3(_0483_),
    .B1(_0180_),
    .X(_0492_)
  );
  sky130_fd_sc_hd__o21ba_2 _1011_ (
    .A1(\NUM[16] ),
    .A2(_0491_),
    .B1_N(_0492_),
    .X(_0107_)
  );
  sky130_fd_sc_hd__nand2_2 _1012_ (
    .A(_0489_),
    .B(_0490_),
    .Y(_0493_)
  );
  sky130_fd_sc_hd__o211a_2 _1013_ (
    .A1(_0489_),
    .A2(_0490_),
    .B1(_0493_),
    .C1(_0348_),
    .X(_0106_)
  );
  sky130_fd_sc_hd__a31o_2 _1014_ (
    .A1(\NUM[13] ),
    .A2(\NUM[12] ),
    .A3(_0483_),
    .B1(\NUM[14] ),
    .X(_0494_)
  );
  sky130_fd_sc_hd__and3_2 _1015_ (
    .A(_0347_),
    .B(_0490_),
    .C(_0494_),
    .X(_0495_)
  );
  sky130_fd_sc_hd__buf_1 _1016_ (
    .A(_0495_),
    .X(_0105_)
  );
  sky130_fd_sc_hd__and3_2 _1017_ (
    .A(\NUM[12] ),
    .B(\NUM[11] ),
    .C(_0471_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__o21ai_2 _1018_ (
    .A1(\NUM[13] ),
    .A2(_0496_),
    .B1(_0369_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__a21oi_2 _1019_ (
    .A1(\NUM[13] ),
    .A2(_0496_),
    .B1(_0497_),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__o21a_2 _1020_ (
    .A1(\NUM[12] ),
    .A2(_0483_),
    .B1(_0347_),
    .X(_0498_)
  );
  sky130_fd_sc_hd__and2b_2 _1021_ (
    .A_N(_0496_),
    .B(_0498_),
    .X(_0499_)
  );
  sky130_fd_sc_hd__buf_1 _1022_ (
    .A(_0499_),
    .X(_0103_)
  );
  sky130_fd_sc_hd__nor2_2 _1023_ (
    .A(_0180_),
    .B(_0483_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__o21a_2 _1024_ (
    .A1(\NUM[11] ),
    .A2(_0471_),
    .B1(_0500_),
    .X(_0102_)
  );
  sky130_fd_sc_hd__and3_2 _1025_ (
    .A(\NUM[8] ),
    .B(\NUM[7] ),
    .C(_0465_),
    .X(_0501_)
  );
  sky130_fd_sc_hd__a21oi_2 _1026_ (
    .A1(\NUM[9] ),
    .A2(_0501_),
    .B1(\NUM[10] ),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__nor3_2 _1027_ (
    .A(_0383_),
    .B(_0471_),
    .C(_0502_),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__a21oi_2 _1028_ (
    .A1(\NUM[9] ),
    .A2(_0501_),
    .B1(_0383_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__o21a_2 _1029_ (
    .A1(\NUM[9] ),
    .A2(_0501_),
    .B1(_0503_),
    .X(_0100_)
  );
  sky130_fd_sc_hd__and2_2 _1030_ (
    .A(\NUM[7] ),
    .B(_0465_),
    .X(_0504_)
  );
  sky130_fd_sc_hd__o21ai_2 _1031_ (
    .A1(\NUM[8] ),
    .A2(_0504_),
    .B1(_0369_),
    .Y(_0505_)
  );
  sky130_fd_sc_hd__nor2_2 _1032_ (
    .A(_0501_),
    .B(_0505_),
    .Y(_0099_)
  );
  sky130_fd_sc_hd__o21ai_2 _1033_ (
    .A1(\NUM[7] ),
    .A2(_0465_),
    .B1(_0369_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__nor2_2 _1034_ (
    .A(_0504_),
    .B(_0506_),
    .Y(_0098_)
  );
  sky130_fd_sc_hd__and3_2 _1035_ (
    .A(\NUM[0] ),
    .B(_0292_),
    .C(_0439_),
    .X(_0507_)
  );
  sky130_fd_sc_hd__and4_2 _1036_ (
    .A(\NUM[3] ),
    .B(\NUM[2] ),
    .C(\NUM[1] ),
    .D(_0507_),
    .X(_0508_)
  );
  sky130_fd_sc_hd__and3_2 _1037_ (
    .A(\NUM[5] ),
    .B(\NUM[4] ),
    .C(_0508_),
    .X(_0509_)
  );
  sky130_fd_sc_hd__inv_2 _1038_ (
    .A(_0465_),
    .Y(_0510_)
  );
  sky130_fd_sc_hd__o211a_2 _1039_ (
    .A1(\NUM[6] ),
    .A2(_0509_),
    .B1(_0510_),
    .C1(_0348_),
    .X(_0097_)
  );
  sky130_fd_sc_hd__a21oi_2 _1040_ (
    .A1(\NUM[4] ),
    .A2(_0508_),
    .B1(\NUM[5] ),
    .Y(_0511_)
  );
  sky130_fd_sc_hd__nor3_2 _1041_ (
    .A(_0383_),
    .B(_0509_),
    .C(_0511_),
    .Y(_0096_)
  );
  sky130_fd_sc_hd__a21oi_2 _1042_ (
    .A1(\NUM[4] ),
    .A2(_0508_),
    .B1(_0180_),
    .Y(_0512_)
  );
  sky130_fd_sc_hd__o21a_2 _1043_ (
    .A1(\NUM[4] ),
    .A2(_0508_),
    .B1(_0512_),
    .X(_0095_)
  );
  sky130_fd_sc_hd__inv_2 _1044_ (
    .A(_0508_),
    .Y(_0513_)
  );
  sky130_fd_sc_hd__a31o_2 _1045_ (
    .A1(\NUM[2] ),
    .A2(\NUM[1] ),
    .A3(_0507_),
    .B1(\NUM[3] ),
    .X(_0514_)
  );
  sky130_fd_sc_hd__and3_2 _1046_ (
    .A(_0347_),
    .B(_0513_),
    .C(_0514_),
    .X(_0515_)
  );
  sky130_fd_sc_hd__buf_1 _1047_ (
    .A(_0515_),
    .X(_0094_)
  );
  sky130_fd_sc_hd__inv_2 _1048_ (
    .A(\NUM[2] ),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__nand2_2 _1049_ (
    .A(\NUM[1] ),
    .B(_0507_),
    .Y(_0517_)
  );
  sky130_fd_sc_hd__a31o_2 _1050_ (
    .A1(\NUM[2] ),
    .A2(\NUM[1] ),
    .A3(_0507_),
    .B1(_0180_),
    .X(_0518_)
  );
  sky130_fd_sc_hd__a21oi_2 _1051_ (
    .A1(_0516_),
    .A2(_0517_),
    .B1(_0518_),
    .Y(_0093_)
  );
  sky130_fd_sc_hd__or2_2 _1052_ (
    .A(\NUM[1] ),
    .B(_0507_),
    .X(_0519_)
  );
  sky130_fd_sc_hd__and3_2 _1053_ (
    .A(_0347_),
    .B(_0517_),
    .C(_0519_),
    .X(_0520_)
  );
  sky130_fd_sc_hd__buf_1 _1054_ (
    .A(_0520_),
    .X(_0092_)
  );
  sky130_fd_sc_hd__a21oi_2 _1055_ (
    .A1(_0292_),
    .A2(_0439_),
    .B1(\NUM[0] ),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__nor3_2 _1056_ (
    .A(_0383_),
    .B(_0507_),
    .C(_0521_),
    .Y(_0091_)
  );
  sky130_fd_sc_hd__or3_2 _1057_ (
    .A(_0176_),
    .B(_0188_),
    .C(_0198_),
    .X(_0522_)
  );
  sky130_fd_sc_hd__or3b_2 _1058_ (
    .A(_0181_),
    .B(\STATO[0] ),
    .C_N(_0522_),
    .X(_0523_)
  );
  sky130_fd_sc_hd__a22o_2 _1059_ (
    .A1(\STATO[0] ),
    .A2(_0336_),
    .B1(_0523_),
    .B2(\STATO[2] ),
    .X(_0090_)
  );
  sky130_fd_sc_hd__a21o_2 _1060_ (
    .A1(_0181_),
    .A2(_0178_),
    .B1(_0351_),
    .X(_0089_)
  );
  sky130_fd_sc_hd__a31o_2 _1061_ (
    .A1(_0177_),
    .A2(\STATO[0] ),
    .A3(_0299_),
    .B1(_0201_),
    .X(_0524_)
  );
  sky130_fd_sc_hd__a22o_2 _1062_ (
    .A1(_0178_),
    .A2(_0200_),
    .B1(_0522_),
    .B2(_0524_),
    .X(_0088_)
  );
  sky130_fd_sc_hd__inv_2 _1063_ (
    .A(\MAX[10] ),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__a21oi_2 _1064_ (
    .A1(RES_DISP),
    .A2(_0525_),
    .B1(EN_DISP),
    .Y(SIGN)
  );
  sky130_fd_sc_hd__or4_2 _1065_ (
    .A(\NUM[11] ),
    .B(\NUM[10] ),
    .C(\NUM[9] ),
    .D(\NUM[8] ),
    .X(_0526_)
  );
  sky130_fd_sc_hd__or4_2 _1066_ (
    .A(\NUM[18] ),
    .B(\NUM[17] ),
    .C(\NUM[15] ),
    .D(\NUM[12] ),
    .X(_0527_)
  );
  sky130_fd_sc_hd__or4_2 _1067_ (
    .A(\NUM[24] ),
    .B(\NUM[21] ),
    .C(\NUM[20] ),
    .D(\NUM[19] ),
    .X(_0528_)
  );
  sky130_fd_sc_hd__or3_2 _1068_ (
    .A(_0526_),
    .B(_0527_),
    .C(_0528_),
    .X(_0529_)
  );
  sky130_fd_sc_hd__o21a_2 _1069_ (
    .A1(\NUM[2] ),
    .A2(\NUM[1] ),
    .B1(\NUM[3] ),
    .X(_0530_)
  );
  sky130_fd_sc_hd__or3_2 _1070_ (
    .A(\NUM[7] ),
    .B(\NUM[6] ),
    .C(\NUM[5] ),
    .X(_0531_)
  );
  sky130_fd_sc_hd__or4_2 _1071_ (
    .A(\NUM[25] ),
    .B(\NUM[16] ),
    .C(\NUM[14] ),
    .D(\NUM[13] ),
    .X(_0532_)
  );
  sky130_fd_sc_hd__or4_2 _1072_ (
    .A(\NUM[31] ),
    .B(\NUM[24] ),
    .C(_0531_),
    .D(_0532_),
    .X(_0533_)
  );
  sky130_fd_sc_hd__or4_2 _1073_ (
    .A(\NUM[30] ),
    .B(\NUM[29] ),
    .C(\NUM[28] ),
    .D(\NUM[27] ),
    .X(_0534_)
  );
  sky130_fd_sc_hd__or4_2 _1074_ (
    .A(\NUM[26] ),
    .B(\NUM[23] ),
    .C(\NUM[22] ),
    .D(_0534_),
    .X(_0535_)
  );
  sky130_fd_sc_hd__a211o_2 _1075_ (
    .A1(\NUM[4] ),
    .A2(_0530_),
    .B1(_0533_),
    .C1(_0535_),
    .X(_0536_)
  );
  sky130_fd_sc_hd__or2_2 _1076_ (
    .A(_0529_),
    .B(_0536_),
    .X(_0537_)
  );
  sky130_fd_sc_hd__or4_2 _1077_ (
    .A(\NUM[4] ),
    .B(_0530_),
    .C(_0531_),
    .D(_0532_),
    .X(_0538_)
  );
  sky130_fd_sc_hd__inv_2 _1078_ (
    .A(\NUM[31] ),
    .Y(_0539_)
  );
  sky130_fd_sc_hd__o31a_2 _1079_ (
    .A1(_0529_),
    .A2(_0535_),
    .A3(_0538_),
    .B1(_0539_),
    .X(_0540_)
  );
  sky130_fd_sc_hd__o21ai_2 _1080_ (
    .A1(\NUM[2] ),
    .A2(\NUM[1] ),
    .B1(_0540_),
    .Y(_0541_)
  );
  sky130_fd_sc_hd__xnor2_2 _1081_ (
    .A(\NUM[3] ),
    .B(_0541_),
    .Y(_0542_)
  );
  sky130_fd_sc_hd__nor2_2 _1082_ (
    .A(_0537_),
    .B(_0542_),
    .Y(_0543_)
  );
  sky130_fd_sc_hd__nor2_2 _1083_ (
    .A(\NUM[31] ),
    .B(_0543_),
    .Y(_0544_)
  );
  sky130_fd_sc_hd__and2b_2 _1084_ (
    .A_N(\NUM[1] ),
    .B(_0540_),
    .X(_0545_)
  );
  sky130_fd_sc_hd__xnor2_2 _1085_ (
    .A(\NUM[2] ),
    .B(_0545_),
    .Y(_0546_)
  );
  sky130_fd_sc_hd__nand2_2 _1086_ (
    .A(_0543_),
    .B(_0546_),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__nand2_2 _1087_ (
    .A(_0539_),
    .B(_0547_),
    .Y(_0548_)
  );
  sky130_fd_sc_hd__and2b_2 _1088_ (
    .A_N(_0540_),
    .B(\NUM[1] ),
    .X(_0549_)
  );
  sky130_fd_sc_hd__or2_2 _1089_ (
    .A(_0545_),
    .B(_0549_),
    .X(_0550_)
  );
  sky130_fd_sc_hd__o21ai_2 _1090_ (
    .A1(\NUM[0] ),
    .A2(_0550_),
    .B1(_0539_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__and2_2 _1091_ (
    .A(_0548_),
    .B(_0551_),
    .X(_0552_)
  );
  sky130_fd_sc_hd__and3_2 _1092_ (
    .A(\NUM[0] ),
    .B(_0550_),
    .C(_0548_),
    .X(_0553_)
  );
  sky130_fd_sc_hd__nand2_2 _1093_ (
    .A(_0539_),
    .B(_0550_),
    .Y(_0554_)
  );
  sky130_fd_sc_hd__nor2_2 _1094_ (
    .A(_0554_),
    .B(_0546_),
    .Y(_0555_)
  );
  sky130_fd_sc_hd__or4_2 _1095_ (
    .A(_0544_),
    .B(_0552_),
    .C(_0553_),
    .D(_0555_),
    .X(_0556_)
  );
  sky130_fd_sc_hd__or4_2 _1096_ (
    .A(\NUM[2] ),
    .B(\NUM[0] ),
    .C(_0550_),
    .D(_0537_),
    .X(_0557_)
  );
  sky130_fd_sc_hd__nand2_2 _1097_ (
    .A(_0544_),
    .B(_0557_),
    .Y(_0558_)
  );
  sky130_fd_sc_hd__or2b_2 _1098_ (
    .A(EN_DISP),
    .B_N(RES_DISP),
    .X(_0559_)
  );
  sky130_fd_sc_hd__buf_1 _1099_ (
    .A(_0559_),
    .X(_0560_)
  );
  sky130_fd_sc_hd__nand2_2 _1100_ (
    .A(\NUM[0] ),
    .B(_0555_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__nor2_2 _1101_ (
    .A(_0544_),
    .B(_0561_),
    .Y(_0562_)
  );
  sky130_fd_sc_hd__nor2_2 _1102_ (
    .A(_0560_),
    .B(_0562_),
    .Y(_0563_)
  );
  sky130_fd_sc_hd__and3_2 _1103_ (
    .A(_0556_),
    .B(_0558_),
    .C(_0563_),
    .X(_0564_)
  );
  sky130_fd_sc_hd__buf_1 _1104_ (
    .A(_0564_),
    .X(DISPNUM2[0])
  );
  sky130_fd_sc_hd__o21a_2 _1105_ (
    .A1(_0547_),
    .A2(_0551_),
    .B1(_0563_),
    .X(DISPNUM2[1])
  );
  sky130_fd_sc_hd__o22a_2 _1106_ (
    .A1(\NUM[31] ),
    .A2(_0543_),
    .B1(_0546_),
    .B2(_0551_),
    .X(_0565_)
  );
  sky130_fd_sc_hd__o211a_2 _1107_ (
    .A1(\NUM[0] ),
    .A2(_0547_),
    .B1(_0565_),
    .C1(_0539_),
    .X(_0566_)
  );
  sky130_fd_sc_hd__nor2_2 _1108_ (
    .A(_0560_),
    .B(_0566_),
    .Y(DISPNUM2[2])
  );
  sky130_fd_sc_hd__inv_2 _1109_ (
    .A(_0561_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__inv_2 _1110_ (
    .A(_0560_),
    .Y(DISPMAX1[5])
  );
  sky130_fd_sc_hd__o31a_2 _1111_ (
    .A1(_0544_),
    .A2(_0567_),
    .A3(_0565_),
    .B1(DISPMAX1[5]),
    .X(DISPNUM2[3])
  );
  sky130_fd_sc_hd__o31a_2 _1112_ (
    .A1(\NUM[0] ),
    .A2(_0554_),
    .A3(_0547_),
    .B1(DISPMAX1[5]),
    .X(DISPNUM2[4])
  );
  sky130_fd_sc_hd__nand2_2 _1113_ (
    .A(_0554_),
    .B(_0565_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__o21a_2 _1114_ (
    .A1(_0552_),
    .A2(_0568_),
    .B1(_0563_),
    .X(DISPNUM2[5])
  );
  sky130_fd_sc_hd__nor2_2 _1115_ (
    .A(RES_DISP),
    .B(EN_DISP),
    .Y(DISPMAX1[6])
  );
  sky130_fd_sc_hd__a211oi_2 _1116_ (
    .A1(_0554_),
    .A2(_0548_),
    .B1(_0562_),
    .C1(EN_DISP),
    .Y(_0569_)
  );
  sky130_fd_sc_hd__or2_2 _1117_ (
    .A(DISPMAX1[6]),
    .B(_0569_),
    .X(_0570_)
  );
  sky130_fd_sc_hd__buf_1 _1118_ (
    .A(_0570_),
    .X(DISPNUM2[6])
  );
  sky130_fd_sc_hd__nor2_2 _1119_ (
    .A(_0540_),
    .B(_0560_),
    .Y(DISPNUM1[5])
  );
  sky130_fd_sc_hd__or2_2 _1120_ (
    .A(\MAX[3] ),
    .B(\MAX[2] ),
    .X(_0571_)
  );
  sky130_fd_sc_hd__or4_2 _1121_ (
    .A(\MAX[4] ),
    .B(\MAX[1] ),
    .C(_0305_),
    .D(_0571_),
    .X(_0572_)
  );
  sky130_fd_sc_hd__nand2_2 _1122_ (
    .A(\MAX[10] ),
    .B(_0572_),
    .Y(_0573_)
  );
  sky130_fd_sc_hd__inv_2 _1123_ (
    .A(\MAX[1] ),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__o21a_2 _1124_ (
    .A1(\MAX[1] ),
    .A2(_0305_),
    .B1(\MAX[10] ),
    .X(_0575_)
  );
  sky130_fd_sc_hd__xnor2_2 _1125_ (
    .A(\MAX[2] ),
    .B(_0575_),
    .Y(_0576_)
  );
  sky130_fd_sc_hd__o31a_2 _1126_ (
    .A1(\MAX[2] ),
    .A2(\MAX[1] ),
    .A3(\MAX[0] ),
    .B1(\MAX[10] ),
    .X(_0577_)
  );
  sky130_fd_sc_hd__xnor2_2 _1127_ (
    .A(\MAX[3] ),
    .B(_0577_),
    .Y(_0578_)
  );
  sky130_fd_sc_hd__nor2_2 _1128_ (
    .A(_0576_),
    .B(_0578_),
    .Y(_0579_)
  );
  sky130_fd_sc_hd__nand3_2 _1129_ (
    .A(_0525_),
    .B(\MAX[4] ),
    .C(_0571_),
    .Y(_0580_)
  );
  sky130_fd_sc_hd__inv_2 _1130_ (
    .A(_0580_),
    .Y(_0581_)
  );
  sky130_fd_sc_hd__nand2_2 _1131_ (
    .A(\MAX[10] ),
    .B(_0305_),
    .Y(_0582_)
  );
  sky130_fd_sc_hd__xnor2_2 _1132_ (
    .A(_0574_),
    .B(_0582_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__nor2_2 _1133_ (
    .A(_0578_),
    .B(_0583_),
    .Y(_0584_)
  );
  sky130_fd_sc_hd__o31a_2 _1134_ (
    .A1(\MAX[4] ),
    .A2(_0579_),
    .A3(_0584_),
    .B1(_0573_),
    .X(_0585_)
  );
  sky130_fd_sc_hd__a21oi_2 _1135_ (
    .A1(_0574_),
    .A2(_0585_),
    .B1(_0581_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__xnor2_2 _1136_ (
    .A(_0578_),
    .B(_0585_),
    .Y(_0587_)
  );
  sky130_fd_sc_hd__a32o_2 _1137_ (
    .A1(_0574_),
    .A2(_0579_),
    .A3(_0581_),
    .B1(_0586_),
    .B2(_0587_),
    .X(_0588_)
  );
  sky130_fd_sc_hd__and2_2 _1138_ (
    .A(_0573_),
    .B(_0588_),
    .X(_0589_)
  );
  sky130_fd_sc_hd__buf_1 _1139_ (
    .A(_0589_),
    .X(_0590_)
  );
  sky130_fd_sc_hd__and2_2 _1140_ (
    .A(\MAX[10] ),
    .B(_0572_),
    .X(_0591_)
  );
  sky130_fd_sc_hd__xor2_2 _1141_ (
    .A(_0576_),
    .B(_0586_),
    .X(_0592_)
  );
  sky130_fd_sc_hd__nor2_2 _1142_ (
    .A(_0588_),
    .B(_0592_),
    .Y(_0593_)
  );
  sky130_fd_sc_hd__or2_2 _1143_ (
    .A(_0591_),
    .B(_0593_),
    .X(_0594_)
  );
  sky130_fd_sc_hd__and3_2 _1144_ (
    .A(_0580_),
    .B(_0583_),
    .C(_0585_),
    .X(_0595_)
  );
  sky130_fd_sc_hd__and2_2 _1145_ (
    .A(_0580_),
    .B(_0585_),
    .X(_0596_)
  );
  sky130_fd_sc_hd__nor2_2 _1146_ (
    .A(_0583_),
    .B(_0596_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__nand4_2 _1147_ (
    .A(_0525_),
    .B(\MAX[4] ),
    .C(\MAX[1] ),
    .D(_0579_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__o21a_2 _1148_ (
    .A1(_0595_),
    .A2(_0597_),
    .B1(_0598_),
    .X(_0599_)
  );
  sky130_fd_sc_hd__nand2_2 _1149_ (
    .A(_0305_),
    .B(_0599_),
    .Y(_0600_)
  );
  sky130_fd_sc_hd__o21a_2 _1150_ (
    .A1(_0305_),
    .A2(_0599_),
    .B1(_0573_),
    .X(_0601_)
  );
  sky130_fd_sc_hd__nand2_2 _1151_ (
    .A(_0600_),
    .B(_0601_),
    .Y(_0602_)
  );
  sky130_fd_sc_hd__a21oi_2 _1152_ (
    .A1(_0305_),
    .A2(_0599_),
    .B1(_0588_),
    .Y(_0603_)
  );
  sky130_fd_sc_hd__or2_2 _1153_ (
    .A(_0594_),
    .B(_0603_),
    .X(_0604_)
  );
  sky130_fd_sc_hd__a31o_2 _1154_ (
    .A1(_0592_),
    .A2(_0599_),
    .A3(_0604_),
    .B1(_0590_),
    .X(_0605_)
  );
  sky130_fd_sc_hd__a21oi_2 _1155_ (
    .A1(_0594_),
    .A2(_0602_),
    .B1(_0605_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__a211oi_2 _1156_ (
    .A1(_0305_),
    .A2(_0590_),
    .B1(_0606_),
    .C1(_0560_),
    .Y(DISPMAX3[0])
  );
  sky130_fd_sc_hd__o2bb2a_2 _1157_ (
    .A1_N(_0593_),
    .A2_N(_0601_),
    .B1(_0603_),
    .B2(_0594_),
    .X(_0607_)
  );
  sky130_fd_sc_hd__o21a_2 _1158_ (
    .A1(_0590_),
    .A2(_0607_),
    .B1(DISPMAX1[5]),
    .X(DISPMAX3[1])
  );
  sky130_fd_sc_hd__and2_2 _1159_ (
    .A(_0592_),
    .B(_0601_),
    .X(_0608_)
  );
  sky130_fd_sc_hd__or2_2 _1160_ (
    .A(_0590_),
    .B(_0608_),
    .X(_0609_)
  );
  sky130_fd_sc_hd__and2_2 _1161_ (
    .A(_0593_),
    .B(_0600_),
    .X(_0610_)
  );
  sky130_fd_sc_hd__o31a_2 _1162_ (
    .A1(_0588_),
    .A2(_0592_),
    .A3(_0599_),
    .B1(_0573_),
    .X(_0611_)
  );
  sky130_fd_sc_hd__a21oi_2 _1163_ (
    .A1(_0525_),
    .A2(_0305_),
    .B1(_0611_),
    .Y(_0612_)
  );
  sky130_fd_sc_hd__o31a_2 _1164_ (
    .A1(_0599_),
    .A2(_0612_),
    .A3(_0609_),
    .B1(DISPMAX1[5]),
    .X(_0613_)
  );
  sky130_fd_sc_hd__o31a_2 _1165_ (
    .A1(_0591_),
    .A2(_0609_),
    .A3(_0610_),
    .B1(_0613_),
    .X(DISPMAX3[2])
  );
  sky130_fd_sc_hd__a21oi_2 _1166_ (
    .A1(_0603_),
    .A2(_0608_),
    .B1(_0560_),
    .Y(DISPMAX3[3])
  );
  sky130_fd_sc_hd__a31oi_2 _1167_ (
    .A1(_0573_),
    .A2(_0599_),
    .A3(_0610_),
    .B1(_0560_),
    .Y(DISPMAX3[4])
  );
  sky130_fd_sc_hd__a22o_2 _1168_ (
    .A1(DISPMAX1[5]),
    .A2(_0590_),
    .B1(_0613_),
    .B2(_0604_),
    .X(DISPMAX3[5])
  );
  sky130_fd_sc_hd__a21oi_2 _1169_ (
    .A1(_0604_),
    .A2(_0611_),
    .B1(_0590_),
    .Y(_0614_)
  );
  sky130_fd_sc_hd__a21oi_2 _1170_ (
    .A1(RES_DISP),
    .A2(_0614_),
    .B1(EN_DISP),
    .Y(DISPMAX3[6])
  );
  sky130_fd_sc_hd__a21oi_2 _1171_ (
    .A1(_0598_),
    .A2(_0585_),
    .B1(_0560_),
    .Y(DISPMAX2[0])
  );
  sky130_fd_sc_hd__nor2_2 _1172_ (
    .A(_0560_),
    .B(_0585_),
    .Y(DISPMAX2[1])
  );
  sky130_fd_sc_hd__nor2_2 _1173_ (
    .A(_0559_),
    .B(_0596_),
    .Y(DISPMAX2[5])
  );
  sky130_fd_sc_hd__and2_2 _1174_ (
    .A(_0598_),
    .B(DISPMAX2[5]),
    .X(_0615_)
  );
  sky130_fd_sc_hd__buf_1 _1175_ (
    .A(_0615_),
    .X(DISPMAX2[2])
  );
  sky130_fd_sc_hd__a21oi_2 _1176_ (
    .A1(_0581_),
    .A2(_0598_),
    .B1(_0560_),
    .Y(DISPMAX2[4])
  );
  sky130_fd_sc_hd__a21oi_2 _1177_ (
    .A1(RES_DISP),
    .A2(_0580_),
    .B1(EN_DISP),
    .Y(DISPMAX2[6])
  );
  sky130_fd_sc_hd__buf_1 _1178_ (
    .A(RESET),
    .X(_0616_)
  );
  sky130_fd_sc_hd__buf_1 _1179_ (
    .A(_0616_),
    .X(_0617_)
  );
  sky130_fd_sc_hd__buf_1 _1180_ (
    .A(_0617_),
    .X(_0618_)
  );
  sky130_fd_sc_hd__inv_2 _1181_ (
    .A(_0618_),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__inv_2 _1182_ (
    .A(_0618_),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__inv_2 _1183_ (
    .A(_0618_),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__inv_2 _1184_ (
    .A(_0618_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__inv_2 _1185_ (
    .A(_0618_),
    .Y(_0004_)
  );
  sky130_fd_sc_hd__inv_2 _1186_ (
    .A(_0618_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__inv_2 _1187_ (
    .A(_0618_),
    .Y(_0006_)
  );
  sky130_fd_sc_hd__inv_2 _1188_ (
    .A(_0618_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__inv_2 _1189_ (
    .A(_0618_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__inv_2 _1190_ (
    .A(_0618_),
    .Y(_0009_)
  );
  sky130_fd_sc_hd__buf_1 _1191_ (
    .A(_0617_),
    .X(_0619_)
  );
  sky130_fd_sc_hd__inv_2 _1192_ (
    .A(_0619_),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__inv_2 _1193_ (
    .A(_0619_),
    .Y(_0011_)
  );
  sky130_fd_sc_hd__inv_2 _1194_ (
    .A(_0619_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__inv_2 _1195_ (
    .A(_0619_),
    .Y(_0013_)
  );
  sky130_fd_sc_hd__inv_2 _1196_ (
    .A(_0619_),
    .Y(_0014_)
  );
  sky130_fd_sc_hd__inv_2 _1197_ (
    .A(_0619_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__inv_2 _1198_ (
    .A(_0619_),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__inv_2 _1199_ (
    .A(_0619_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__inv_2 _1200_ (
    .A(_0619_),
    .Y(_0018_)
  );
  sky130_fd_sc_hd__inv_2 _1201_ (
    .A(_0619_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__buf_1 _1202_ (
    .A(_0616_),
    .X(_0620_)
  );
  sky130_fd_sc_hd__inv_2 _1203_ (
    .A(_0620_),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__inv_2 _1204_ (
    .A(_0620_),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__inv_2 _1205_ (
    .A(_0620_),
    .Y(_0022_)
  );
  sky130_fd_sc_hd__inv_2 _1206_ (
    .A(_0620_),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__inv_2 _1207_ (
    .A(_0620_),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__inv_2 _1208_ (
    .A(_0620_),
    .Y(_0025_)
  );
  sky130_fd_sc_hd__inv_2 _1209_ (
    .A(_0620_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__inv_2 _1210_ (
    .A(_0620_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__inv_2 _1211_ (
    .A(_0620_),
    .Y(_0028_)
  );
  sky130_fd_sc_hd__inv_2 _1212_ (
    .A(_0620_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__buf_1 _1213_ (
    .A(_0616_),
    .X(_0621_)
  );
  sky130_fd_sc_hd__inv_2 _1214_ (
    .A(_0621_),
    .Y(_0030_)
  );
  sky130_fd_sc_hd__inv_2 _1215_ (
    .A(_0621_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__inv_2 _1216_ (
    .A(_0621_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__inv_2 _1217_ (
    .A(_0621_),
    .Y(_0033_)
  );
  sky130_fd_sc_hd__inv_2 _1218_ (
    .A(_0621_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__inv_2 _1219_ (
    .A(_0621_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__inv_2 _1220_ (
    .A(_0621_),
    .Y(_0036_)
  );
  sky130_fd_sc_hd__inv_2 _1221_ (
    .A(_0621_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__inv_2 _1222_ (
    .A(_0621_),
    .Y(_0038_)
  );
  sky130_fd_sc_hd__inv_2 _1223_ (
    .A(_0621_),
    .Y(_0039_)
  );
  sky130_fd_sc_hd__buf_1 _1224_ (
    .A(_0616_),
    .X(_0622_)
  );
  sky130_fd_sc_hd__inv_2 _1225_ (
    .A(_0622_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__inv_2 _1226_ (
    .A(_0622_),
    .Y(_0041_)
  );
  sky130_fd_sc_hd__inv_2 _1227_ (
    .A(_0622_),
    .Y(_0042_)
  );
  sky130_fd_sc_hd__inv_2 _1228_ (
    .A(_0622_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__inv_2 _1229_ (
    .A(_0622_),
    .Y(_0044_)
  );
  sky130_fd_sc_hd__inv_2 _1230_ (
    .A(_0622_),
    .Y(_0045_)
  );
  sky130_fd_sc_hd__inv_2 _1231_ (
    .A(_0622_),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__inv_2 _1232_ (
    .A(_0622_),
    .Y(_0047_)
  );
  sky130_fd_sc_hd__inv_2 _1233_ (
    .A(_0622_),
    .Y(_0048_)
  );
  sky130_fd_sc_hd__inv_2 _1234_ (
    .A(_0622_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__buf_1 _1235_ (
    .A(_0616_),
    .X(_0623_)
  );
  sky130_fd_sc_hd__inv_2 _1236_ (
    .A(_0623_),
    .Y(_0050_)
  );
  sky130_fd_sc_hd__inv_2 _1237_ (
    .A(_0623_),
    .Y(_0051_)
  );
  sky130_fd_sc_hd__inv_2 _1238_ (
    .A(_0623_),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__inv_2 _1239_ (
    .A(_0623_),
    .Y(_0053_)
  );
  sky130_fd_sc_hd__inv_2 _1240_ (
    .A(_0623_),
    .Y(_0054_)
  );
  sky130_fd_sc_hd__inv_2 _1241_ (
    .A(_0623_),
    .Y(_0055_)
  );
  sky130_fd_sc_hd__inv_2 _1242_ (
    .A(_0623_),
    .Y(_0056_)
  );
  sky130_fd_sc_hd__inv_2 _1243_ (
    .A(_0623_),
    .Y(_0057_)
  );
  sky130_fd_sc_hd__inv_2 _1244_ (
    .A(_0623_),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__inv_2 _1245_ (
    .A(_0623_),
    .Y(_0059_)
  );
  sky130_fd_sc_hd__buf_1 _1246_ (
    .A(_0616_),
    .X(_0624_)
  );
  sky130_fd_sc_hd__inv_2 _1247_ (
    .A(_0624_),
    .Y(_0060_)
  );
  sky130_fd_sc_hd__inv_2 _1248_ (
    .A(_0624_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__inv_2 _1249_ (
    .A(_0624_),
    .Y(_0062_)
  );
  sky130_fd_sc_hd__inv_2 _1250_ (
    .A(_0624_),
    .Y(_0063_)
  );
  sky130_fd_sc_hd__inv_2 _1251_ (
    .A(_0624_),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__inv_2 _1252_ (
    .A(_0624_),
    .Y(_0065_)
  );
  sky130_fd_sc_hd__inv_2 _1253_ (
    .A(_0624_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__inv_2 _1254_ (
    .A(_0624_),
    .Y(_0067_)
  );
  sky130_fd_sc_hd__inv_2 _1255_ (
    .A(_0624_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__inv_2 _1256_ (
    .A(_0624_),
    .Y(_0069_)
  );
  sky130_fd_sc_hd__buf_1 _1257_ (
    .A(_0616_),
    .X(_0625_)
  );
  sky130_fd_sc_hd__inv_2 _1258_ (
    .A(_0625_),
    .Y(_0070_)
  );
  sky130_fd_sc_hd__inv_2 _1259_ (
    .A(_0625_),
    .Y(_0071_)
  );
  sky130_fd_sc_hd__inv_2 _1260_ (
    .A(_0625_),
    .Y(_0072_)
  );
  sky130_fd_sc_hd__inv_2 _1261_ (
    .A(_0625_),
    .Y(_0073_)
  );
  sky130_fd_sc_hd__inv_2 _1262_ (
    .A(_0625_),
    .Y(_0074_)
  );
  sky130_fd_sc_hd__inv_2 _1263_ (
    .A(_0625_),
    .Y(_0075_)
  );
  sky130_fd_sc_hd__inv_2 _1264_ (
    .A(_0625_),
    .Y(_0076_)
  );
  sky130_fd_sc_hd__inv_2 _1265_ (
    .A(_0625_),
    .Y(_0077_)
  );
  sky130_fd_sc_hd__inv_2 _1266_ (
    .A(_0625_),
    .Y(_0078_)
  );
  sky130_fd_sc_hd__inv_2 _1267_ (
    .A(_0625_),
    .Y(_0079_)
  );
  sky130_fd_sc_hd__inv_2 _1268_ (
    .A(_0617_),
    .Y(_0080_)
  );
  sky130_fd_sc_hd__inv_2 _1269_ (
    .A(_0617_),
    .Y(_0081_)
  );
  sky130_fd_sc_hd__inv_2 _1270_ (
    .A(_0617_),
    .Y(_0082_)
  );
  sky130_fd_sc_hd__inv_2 _1271_ (
    .A(_0617_),
    .Y(_0083_)
  );
  sky130_fd_sc_hd__inv_2 _1272_ (
    .A(_0617_),
    .Y(_0084_)
  );
  sky130_fd_sc_hd__inv_2 _1273_ (
    .A(_0617_),
    .Y(_0085_)
  );
  sky130_fd_sc_hd__inv_2 _1274_ (
    .A(_0617_),
    .Y(_0086_)
  );
  sky130_fd_sc_hd__inv_2 _1275_ (
    .A(_0617_),
    .Y(_0087_)
  );
  FI_DFF_DFRTP_FAULTY _1276_ (
    .CLK(CLOCK),
    .D(_0088_),
    .RESET_B(_0000_),
    .fault_en(fault_en[0]),
    .Q(\STATO[0] )
  );
FI_DFF_DFRTP_FAULTY _1277_ (
  .CLK(CLOCK),
  .D(_0089_),
  .RESET_B(_0001_),
  .fault_en(fault_en[1]),
  .Q(\STATO[1] )
);
FI_DFF_DFRTP_FAULTY _1278_ (
  .CLK(CLOCK),
  .D(_0090_),
  .RESET_B(_0002_),
  .fault_en(fault_en[2]),
  .Q(\STATO[2] )
);
FI_DFF_DFRTP_FAULTY _1279_ (
  .CLK(CLOCK),
  .D(_0091_),
  .RESET_B(_0003_),
  .fault_en(fault_en[3]),
  .Q(\NUM[0] )
);
FI_DFF_DFRTP_FAULTY _1280_ (
  .CLK(CLOCK),
  .D(_0092_),
  .RESET_B(_0004_),
  .fault_en(fault_en[4]),
  .Q(\NUM[1] )
);
FI_DFF_DFRTP_FAULTY _1281_ (
  .CLK(CLOCK),
  .D(_0093_),
  .RESET_B(_0005_),
  .fault_en(fault_en[5]),
  .Q(\NUM[2] )
);
FI_DFF_DFRTP_FAULTY _1282_ (
  .CLK(CLOCK),
  .D(_0094_),
  .RESET_B(_0006_),
  .fault_en(fault_en[6]),
  .Q(\NUM[3] )
);
FI_DFF_DFRTP_FAULTY _1283_ (
  .CLK(CLOCK),
  .D(_0095_),
  .RESET_B(_0007_),
  .fault_en(fault_en[7]),
  .Q(\NUM[4] )
);
FI_DFF_DFRTP_FAULTY _1284_ (
  .CLK(CLOCK),
  .D(_0096_),
  .RESET_B(_0008_),
  .fault_en(fault_en[8]),
  .Q(\NUM[5] )
);
FI_DFF_DFRTP_FAULTY _1285_ (
  .CLK(CLOCK),
  .D(_0097_),
  .RESET_B(_0009_),
  .fault_en(fault_en[9]),
  .Q(\NUM[6] )
);
FI_DFF_DFRTP_FAULTY _1286_ (
  .CLK(CLOCK),
  .D(_0098_),
  .RESET_B(_0010_),
  .fault_en(fault_en[10]),
  .Q(\NUM[7] )
);
FI_DFF_DFRTP_FAULTY _1287_ (
  .CLK(CLOCK),
  .D(_0099_),
  .RESET_B(_0011_),
  .fault_en(fault_en[11]),
  .Q(\NUM[8] )
);
FI_DFF_DFRTP_FAULTY _1288_ (
  .CLK(CLOCK),
  .D(_0100_),
  .RESET_B(_0012_),
  .fault_en(fault_en[12]),
  .Q(\NUM[9] )
);
FI_DFF_DFRTP_FAULTY _1289_ (
  .CLK(CLOCK),
  .D(_0101_),
  .RESET_B(_0013_),
  .fault_en(fault_en[13]),
  .Q(\NUM[10] )
);
FI_DFF_DFRTP_FAULTY _1290_ (
  .CLK(CLOCK),
  .D(_0102_),
  .RESET_B(_0014_),
  .fault_en(fault_en[14]),
  .Q(\NUM[11] )
);
FI_DFF_DFRTP_FAULTY _1291_ (
  .CLK(CLOCK),
  .D(_0103_),
  .RESET_B(_0015_),
  .fault_en(fault_en[15]),
  .Q(\NUM[12] )
);
FI_DFF_DFRTP_FAULTY _1292_ (
  .CLK(CLOCK),
  .D(_0104_),
  .RESET_B(_0016_),
  .fault_en(fault_en[16]),
  .Q(\NUM[13] )
);
FI_DFF_DFRTP_FAULTY _1293_ (
  .CLK(CLOCK),
  .D(_0105_),
  .RESET_B(_0017_),
  .fault_en(fault_en[17]),
  .Q(\NUM[14] )
);
FI_DFF_DFRTP_FAULTY _1294_ (
  .CLK(CLOCK),
  .D(_0106_),
  .RESET_B(_0018_),
  .fault_en(fault_en[18]),
  .Q(\NUM[15] )
);
FI_DFF_DFRTP_FAULTY _1295_ (
  .CLK(CLOCK),
  .D(_0107_),
  .RESET_B(_0019_),
  .fault_en(fault_en[19]),
  .Q(\NUM[16] )
);
FI_DFF_DFRTP_FAULTY _1296_ (
  .CLK(CLOCK),
  .D(_0108_),
  .RESET_B(_0020_),
  .fault_en(fault_en[20]),
  .Q(\NUM[17] )
);
FI_DFF_DFRTP_FAULTY _1297_ (
  .CLK(CLOCK),
  .D(_0109_),
  .RESET_B(_0021_),
  .fault_en(fault_en[21]),
  .Q(\NUM[18] )
);
FI_DFF_DFRTP_FAULTY _1298_ (
  .CLK(CLOCK),
  .D(_0110_),
  .RESET_B(_0022_),
  .fault_en(fault_en[22]),
  .Q(\NUM[19] )
);
FI_DFF_DFRTP_FAULTY _1299_ (
  .CLK(CLOCK),
  .D(_0111_),
  .RESET_B(_0023_),
  .fault_en(fault_en[23]),
  .Q(\NUM[20] )
);
FI_DFF_DFRTP_FAULTY _1300_ (
  .CLK(CLOCK),
  .D(_0112_),
  .RESET_B(_0024_),
  .fault_en(fault_en[24]),
  .Q(\NUM[21] )
);
FI_DFF_DFRTP_FAULTY _1301_ (
  .CLK(CLOCK),
  .D(_0113_),
  .RESET_B(_0025_),
  .fault_en(fault_en[25]),
  .Q(\NUM[22] )
);
FI_DFF_DFRTP_FAULTY _1302_ (
  .CLK(CLOCK),
  .D(_0114_),
  .RESET_B(_0026_),
  .fault_en(fault_en[26]),
  .Q(\NUM[23] )
);
FI_DFF_DFRTP_FAULTY _1303_ (
  .CLK(CLOCK),
  .D(_0115_),
  .RESET_B(_0027_),
  .fault_en(fault_en[27]),
  .Q(\NUM[24] )
);
FI_DFF_DFRTP_FAULTY _1304_ (
  .CLK(CLOCK),
  .D(_0116_),
  .RESET_B(_0028_),
  .fault_en(fault_en[28]),
  .Q(\NUM[25] )
);
FI_DFF_DFRTP_FAULTY _1305_ (
  .CLK(CLOCK),
  .D(_0117_),
  .RESET_B(_0029_),
  .fault_en(fault_en[29]),
  .Q(\NUM[26] )
);
FI_DFF_DFRTP_FAULTY _1306_ (
  .CLK(CLOCK),
  .D(_0118_),
  .RESET_B(_0030_),
  .fault_en(fault_en[30]),
  .Q(\NUM[27] )
);
FI_DFF_DFRTP_FAULTY _1307_ (
  .CLK(CLOCK),
  .D(_0119_),
  .RESET_B(_0031_),
  .fault_en(fault_en[31]),
  .Q(\NUM[28] )
);
FI_DFF_DFRTP_FAULTY _1308_ (
  .CLK(CLOCK),
  .D(_0120_),
  .RESET_B(_0032_),
  .fault_en(fault_en[32]),
  .Q(\NUM[29] )
);
FI_DFF_DFRTP_FAULTY _1309_ (
  .CLK(CLOCK),
  .D(_0121_),
  .RESET_B(_0033_),
  .fault_en(fault_en[33]),
  .Q(\NUM[30] )
);
FI_DFF_DFRTP_FAULTY _1310_ (
  .CLK(CLOCK),
  .D(_0122_),
  .RESET_B(_0034_),
  .fault_en(fault_en[34]),
  .Q(\NUM[31] )
);
FI_DFF_DFRTP_FAULTY _1311_ (
  .CLK(CLOCK),
  .D(_0123_),
  .RESET_B(_0035_),
  .fault_en(fault_en[35]),
  .Q(\MAR[0] )
);
FI_DFF_DFRTP_FAULTY _1312_ (
  .CLK(CLOCK),
  .D(_0124_),
  .RESET_B(_0036_),
  .fault_en(fault_en[36]),
  .Q(\MAR[1] )
);
FI_DFF_DFRTP_FAULTY _1313_ (
  .CLK(CLOCK),
  .D(_0125_),
  .RESET_B(_0037_),
  .fault_en(fault_en[37]),
  .Q(\MAR[2] )
);
FI_DFF_DFRTP_FAULTY _1314_ (
  .CLK(CLOCK),
  .D(_0126_),
  .RESET_B(_0038_),
  .fault_en(fault_en[38]),
  .Q(\MAR[3] )
);
FI_DFF_DFRTP_FAULTY _1315_ (
  .CLK(CLOCK),
  .D(_0127_),
  .RESET_B(_0039_),
  .fault_en(fault_en[39]),
  .Q(\MAR[4] )
);
FI_DFF_DFRTP_FAULTY _1316_ (
  .CLK(CLOCK),
  .D(_0128_),
  .RESET_B(_0040_),
  .fault_en(fault_en[40]),
  .Q(\MAR[5] )
);
FI_DFF_DFRTP_FAULTY _1317_ (
  .CLK(CLOCK),
  .D(_0129_),
  .RESET_B(_0041_),
  .fault_en(fault_en[41]),
  .Q(\MAR[6] )
);
FI_DFF_DFRTP_FAULTY _1318_ (
  .CLK(CLOCK),
  .D(_0130_),
  .RESET_B(_0042_),
  .fault_en(fault_en[42]),
  .Q(\MAR[7] )
);
FI_DFF_DFRTP_FAULTY _1319_ (
  .CLK(CLOCK),
  .D(_0131_),
  .RESET_B(_0043_),
  .fault_en(fault_en[43]),
  .Q(\MAR[8] )
);
FI_DFF_DFRTP_FAULTY _1320_ (
  .CLK(CLOCK),
  .D(_0132_),
  .RESET_B(_0044_),
  .fault_en(fault_en[44]),
  .Q(\MAR[9] )
);
FI_DFF_DFRTP_FAULTY _1321_ (
  .CLK(CLOCK),
  .D(_0133_),
  .RESET_B(_0045_),
  .fault_en(fault_en[45]),
  .Q(\MAR[10] )
);
FI_DFF_DFRTP_FAULTY _1322_ (
  .CLK(CLOCK),
  .D(_0134_),
  .RESET_B(_0046_),
  .fault_en(fault_en[46]),
  .Q(\MAR[11] )
);
FI_DFF_DFRTP_FAULTY _1323_ (
  .CLK(CLOCK),
  .D(_0135_),
  .RESET_B(_0047_),
  .fault_en(fault_en[47]),
  .Q(\MAR[12] )
);
FI_DFF_DFRTP_FAULTY _1324_ (
  .CLK(CLOCK),
  .D(_0136_),
  .RESET_B(_0048_),
  .fault_en(fault_en[48]),
  .Q(\MAR[13] )
);
FI_DFF_DFRTP_FAULTY _1325_ (
  .CLK(CLOCK),
  .D(_0137_),
  .RESET_B(_0049_),
  .fault_en(fault_en[49]),
  .Q(\MAR[14] )
);
FI_DFF_DFRTP_FAULTY _1326_ (
  .CLK(CLOCK),
  .D(_0138_),
  .RESET_B(_0050_),
  .fault_en(fault_en[50]),
  .Q(\MAR[15] )
);
FI_DFF_DFRTP_FAULTY _1327_ (
  .CLK(CLOCK),
  .D(_0139_),
  .RESET_B(_0051_),
  .fault_en(fault_en[51]),
  .Q(\MAR[16] )
);
FI_DFF_DFRTP_FAULTY _1328_ (
  .CLK(CLOCK),
  .D(_0140_),
  .RESET_B(_0052_),
  .fault_en(fault_en[52]),
  .Q(\MAR[17] )
);
FI_DFF_DFRTP_FAULTY _1329_ (
  .CLK(CLOCK),
  .D(_0141_),
  .RESET_B(_0053_),
  .fault_en(fault_en[53]),
  .Q(\MAR[18] )
);
FI_DFF_DFRTP_FAULTY _1330_ (
  .CLK(CLOCK),
  .D(_0142_),
  .RESET_B(_0054_),
  .fault_en(fault_en[54]),
  .Q(\MAR[19] )
);
FI_DFF_DFRTP_FAULTY _1331_ (
  .CLK(CLOCK),
  .D(_0143_),
  .RESET_B(_0055_),
  .fault_en(fault_en[55]),
  .Q(\MAR[20] )
);
FI_DFF_DFRTP_FAULTY _1332_ (
  .CLK(CLOCK),
  .D(_0144_),
  .RESET_B(_0056_),
  .fault_en(fault_en[56]),
  .Q(\MAR[21] )
);
FI_DFF_DFRTP_FAULTY _1333_ (
  .CLK(CLOCK),
  .D(_0145_),
  .RESET_B(_0057_),
  .fault_en(fault_en[57]),
  .Q(\MAR[22] )
);
FI_DFF_DFRTP_FAULTY _1334_ (
  .CLK(CLOCK),
  .D(_0146_),
  .RESET_B(_0058_),
  .fault_en(fault_en[58]),
  .Q(\MAR[23] )
);
FI_DFF_DFRTP_FAULTY _1335_ (
  .CLK(CLOCK),
  .D(_0147_),
  .RESET_B(_0059_),
  .fault_en(fault_en[59]),
  .Q(\MAR[24] )
);
FI_DFF_DFRTP_FAULTY _1336_ (
  .CLK(CLOCK),
  .D(_0148_),
  .RESET_B(_0060_),
  .fault_en(fault_en[60]),
  .Q(\MAR[25] )
);
FI_DFF_DFRTP_FAULTY _1337_ (
  .CLK(CLOCK),
  .D(_0149_),
  .RESET_B(_0061_),
  .fault_en(fault_en[61]),
  .Q(\MAR[26] )
);
FI_DFF_DFRTP_FAULTY _1338_ (
  .CLK(CLOCK),
  .D(_0150_),
  .RESET_B(_0062_),
  .fault_en(fault_en[62]),
  .Q(\MAR[27] )
);
FI_DFF_DFRTP_FAULTY _1339_ (
  .CLK(CLOCK),
  .D(_0151_),
  .RESET_B(_0063_),
  .fault_en(fault_en[63]),
  .Q(\MAR[28] )
);
FI_DFF_DFRTP_FAULTY _1340_ (
  .CLK(CLOCK),
  .D(_0152_),
  .RESET_B(_0064_),
  .fault_en(fault_en[64]),
  .Q(\MAR[29] )
);
FI_DFF_DFRTP_FAULTY _1341_ (
  .CLK(CLOCK),
  .D(_0153_),
  .RESET_B(_0065_),
  .fault_en(fault_en[65]),
  .Q(\MAR[30] )
);
FI_DFF_DFRTP_FAULTY _1342_ (
  .CLK(CLOCK),
  .D(_0154_),
  .RESET_B(_0066_),
  .fault_en(fault_en[66]),
  .Q(\MAR[31] )
);
FI_DFF_DFRTP_FAULTY _1343_ (
  .CLK(CLOCK),
  .D(_0155_),
  .RESET_B(_0067_),
  .fault_en(fault_en[67]),
  .Q(\TEMP[0] )
);
FI_DFF_DFRTP_FAULTY _1344_ (
  .CLK(CLOCK),
  .D(_0156_),
  .RESET_B(_0068_),
  .fault_en(fault_en[68]),
  .Q(\TEMP[1] )
);
FI_DFF_DFRTP_FAULTY _1345_ (
  .CLK(CLOCK),
  .D(_0157_),
  .RESET_B(_0069_),
  .fault_en(fault_en[69]),
  .Q(\TEMP[2] )
);
FI_DFF_DFRTP_FAULTY _1346_ (
  .CLK(CLOCK),
  .D(_0158_),
  .RESET_B(_0070_),
  .fault_en(fault_en[70]),
  .Q(\TEMP[3] )
);
FI_DFF_DFRTP_FAULTY _1347_ (
  .CLK(CLOCK),
  .D(_0159_),
  .RESET_B(_0071_),
  .fault_en(fault_en[71]),
  .Q(\TEMP[4] )
);
FI_DFF_DFRTP_FAULTY _1348_ (
  .CLK(CLOCK),
  .D(_0160_),
  .RESET_B(_0072_),
  .fault_en(fault_en[72]),
  .Q(\TEMP[5] )
);
FI_DFF_DFRTP_FAULTY _1349_ (
  .CLK(CLOCK),
  .D(_0161_),
  .RESET_B(_0073_),
  .fault_en(fault_en[73]),
  .Q(\TEMP[6] )
);
FI_DFF_DFRTP_FAULTY _1350_ (
  .CLK(CLOCK),
  .D(_0162_),
  .RESET_B(_0074_),
  .fault_en(fault_en[74]),
  .Q(\TEMP[7] )
);
FI_DFF_DFRTP_FAULTY _1351_ (
  .CLK(CLOCK),
  .D(_0163_),
  .RESET_B(_0075_),
  .fault_en(fault_en[75]),
  .Q(\TEMP[10] )
);
FI_DFF_DFRTP_FAULTY _1352_ (
  .CLK(CLOCK),
  .D(_0164_),
  .RESET_B(_0076_),
  .fault_en(fault_en[76]),
  .Q(\MAX[0] )
);
FI_DFF_DFRTP_FAULTY _1353_ (
  .CLK(CLOCK),
  .D(_0165_),
  .RESET_B(_0077_),
  .fault_en(fault_en[77]),
  .Q(\MAX[1] )
);
FI_DFF_DFRTP_FAULTY _1354_ (
  .CLK(CLOCK),
  .D(_0166_),
  .RESET_B(_0078_),
  .fault_en(fault_en[78]),
  .Q(\MAX[2] )
);
FI_DFF_DFRTP_FAULTY _1355_ (
  .CLK(CLOCK),
  .D(_0167_),
  .RESET_B(_0079_),
  .fault_en(fault_en[79]),
  .Q(\MAX[3] )
);
FI_DFF_DFRTP_FAULTY _1356_ (
  .CLK(CLOCK),
  .D(_0168_),
  .RESET_B(_0080_),
  .fault_en(fault_en[80]),
  .Q(\MAX[4] )
);
FI_DFF_DFRTP_FAULTY _1357_ (
  .CLK(CLOCK),
  .D(_0169_),
  .RESET_B(_0081_),
  .fault_en(fault_en[81]),
  .Q(\MAX[5] )
);
FI_DFF_DFRTP_FAULTY _1358_ (
  .CLK(CLOCK),
  .D(_0170_),
  .RESET_B(_0082_),
  .fault_en(fault_en[82]),
  .Q(\MAX[6] )
);
FI_DFF_DFRTP_FAULTY _1359_ (
  .CLK(CLOCK),
  .D(_0171_),
  .RESET_B(_0083_),
  .fault_en(fault_en[83]),
  .Q(\MAX[7] )
);
FI_DFF_DFRTP_FAULTY _1360_ (
  .CLK(CLOCK),
  .D(_0172_),
  .RESET_B(_0084_),
  .fault_en(fault_en[84]),
  .Q(\MAX[10] )
);
FI_DFF_DFRTP_FAULTY _1361_ (
  .CLK(CLOCK),
  .D(_0173_),
  .RESET_B(_0085_),
  .fault_en(fault_en[85]),
  .Q(FLAG)
);
FI_DFF_DFRTP_FAULTY _1362_ (
  .CLK(CLOCK),
  .D(_0174_),
  .RESET_B(_0086_),
  .fault_en(fault_en[86]),
  .Q(EN_DISP)
);
FI_DFF_DFRTP_FAULTY _1363_ (
  .CLK(CLOCK),
  .D(_0175_),
  .RESET_B(_0087_),
  .fault_en(fault_en[87]),
  .Q(RES_DISP)
);
sky130_fd_sc_hd__buf_2 _1364_ (
    .A(DISPMAX1[5]),
    .X(DISPMAX1[0])
  );
  sky130_fd_sc_hd__buf_2 _1365_ (
    .A(DISPMAX1[5]),
    .X(DISPMAX1[1])
  );
  sky130_fd_sc_hd__buf_2 _1366_ (
    .A(DISPMAX1[5]),
    .X(DISPMAX1[2])
  );
  sky130_fd_sc_hd__buf_2 _1367_ (
    .A(DISPMAX1[5]),
    .X(DISPMAX1[3])
  );
  sky130_fd_sc_hd__buf_2 _1368_ (
    .A(DISPMAX1[5]),
    .X(DISPMAX1[4])
  );
  sky130_fd_sc_hd__buf_2 _1369_ (
    .A(DISPMAX1[5]),
    .X(DISPMAX2[3])
  );
  sky130_fd_sc_hd__buf_2 _1370_ (
    .A(DISPNUM1[5]),
    .X(DISPNUM1[0])
  );
  sky130_fd_sc_hd__buf_2 _1371_ (
    .A(DISPNUM1[5]),
    .X(DISPNUM1[1])
  );
  sky130_fd_sc_hd__buf_2 _1372_ (
    .A(DISPNUM1[5]),
    .X(DISPNUM1[2])
  );
  sky130_fd_sc_hd__buf_2 _1373_ (
    .A(DISPMAX1[5]),
    .X(DISPNUM1[3])
  );
  sky130_fd_sc_hd__buf_2 _1374_ (
    .A(DISPMAX1[5]),
    .X(DISPNUM1[4])
  );
  sky130_fd_sc_hd__buf_2 _1375_ (
    .A(DISPMAX1[6]),
    .X(DISPNUM1[6])
  );
endmodule
