/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b08(CLOCK, RESET, START, I, O);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  input CLOCK;
  wire CLOCK;
  input [7:0] I;
  wire [7:0] I;
  wire \IN_R[0] ;
  wire \IN_R[1] ;
  wire \IN_R[2] ;
  wire \IN_R[3] ;
  wire \IN_R[4] ;
  wire \IN_R[5] ;
  wire \IN_R[6] ;
  wire \IN_R[7] ;
  wire \MAR[0] ;
  wire \MAR[1] ;
  wire \MAR[2] ;
  output [3:0] O;
  wire [3:0] O;
  wire \OUT_R[0] ;
  wire \OUT_R[1] ;
  wire \OUT_R[2] ;
  wire \OUT_R[3] ;
  input RESET;
  wire RESET;
  input START;
  wire START;
  wire \STATO[0] ;
  wire \STATO[1] ;
  wire \STATO[2] ;
  wire \STATO[3] ;
  sky130_fd_sc_hd__or2b_2 _111_ (
    .A(\MAR[1] ),
    .B_N(\MAR[2] ),
    .X(_091_)
  );
  sky130_fd_sc_hd__buf_1 _112_ (
    .A(\MAR[2] ),
    .X(_092_)
  );
  sky130_fd_sc_hd__inv_2 _113_ (
    .A(_092_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a21o_2 _114_ (
    .A1(\IN_R[1] ),
    .A2(_093_),
    .B1(\IN_R[2] ),
    .X(_094_)
  );
  sky130_fd_sc_hd__buf_1 _115_ (
    .A(\MAR[1] ),
    .X(_095_)
  );
  sky130_fd_sc_hd__xor2_2 _116_ (
    .A(_095_),
    .B(\MAR[0] ),
    .X(_096_)
  );
  sky130_fd_sc_hd__and3_2 _117_ (
    .A(_092_),
    .B(_095_),
    .C(\MAR[0] ),
    .X(_097_)
  );
  sky130_fd_sc_hd__nor2_2 _118_ (
    .A(_092_),
    .B(_095_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__o21a_2 _119_ (
    .A1(_097_),
    .A2(_098_),
    .B1(\IN_R[7] ),
    .X(_099_)
  );
  sky130_fd_sc_hd__inv_2 _120_ (
    .A(\MAR[0] ),
    .Y(_100_)
  );
  sky130_fd_sc_hd__or2_2 _121_ (
    .A(_100_),
    .B(_091_),
    .X(_101_)
  );
  sky130_fd_sc_hd__or3_2 _122_ (
    .A(_092_),
    .B(_095_),
    .C(\MAR[0] ),
    .X(_102_)
  );
  sky130_fd_sc_hd__a21oi_2 _123_ (
    .A1(_101_),
    .A2(_102_),
    .B1(\IN_R[6] ),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a311o_2 _124_ (
    .A1(_091_),
    .A2(_094_),
    .A3(_096_),
    .B1(_099_),
    .C1(_103_),
    .X(_104_)
  );
  sky130_fd_sc_hd__or2b_2 _125_ (
    .A(\MAR[2] ),
    .B_N(_095_),
    .X(_105_)
  );
  sky130_fd_sc_hd__or2_2 _126_ (
    .A(_100_),
    .B(_105_),
    .X(_106_)
  );
  sky130_fd_sc_hd__a21oi_2 _127_ (
    .A1(_101_),
    .A2(_106_),
    .B1(\IN_R[2] ),
    .Y(_107_)
  );
  sky130_fd_sc_hd__and2b_2 _128_ (
    .A_N(\MAR[0] ),
    .B(_095_),
    .X(_108_)
  );
  sky130_fd_sc_hd__nand2_2 _129_ (
    .A(_092_),
    .B(_108_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a21oi_2 _130_ (
    .A1(_106_),
    .A2(_109_),
    .B1(\IN_R[7] ),
    .Y(_110_)
  );
  sky130_fd_sc_hd__inv_2 _131_ (
    .A(\IN_R[5] ),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_2 _132_ (
    .A(\STATO[1] ),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a221o_2 _133_ (
    .A1(_046_),
    .A2(_098_),
    .B1(_108_),
    .B2(\IN_R[0] ),
    .C1(_047_),
    .X(_048_)
  );
  sky130_fd_sc_hd__o211ai_2 _134_ (
    .A1(_092_),
    .A2(_100_),
    .B1(_095_),
    .C1(\IN_R[4] ),
    .Y(_049_)
  );
  sky130_fd_sc_hd__o21ai_2 _135_ (
    .A1(\IN_R[4] ),
    .A2(_106_),
    .B1(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__or4_2 _136_ (
    .A(_107_),
    .B(_110_),
    .C(_048_),
    .D(_050_),
    .X(_051_)
  );
  sky130_fd_sc_hd__a21oi_2 _137_ (
    .A1(_095_),
    .A2(\MAR[0] ),
    .B1(_092_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__o2111a_2 _138_ (
    .A1(_097_),
    .A2(_052_),
    .B1(_101_),
    .C1(\IN_R[6] ),
    .D1(_102_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a21oi_2 _139_ (
    .A1(_046_),
    .A2(\IN_R[1] ),
    .B1(_109_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__or2_2 _140_ (
    .A(_095_),
    .B(_100_),
    .X(_055_)
  );
  sky130_fd_sc_hd__a21oi_2 _141_ (
    .A1(_091_),
    .A2(_055_),
    .B1(\IN_R[0] ),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_2 _142_ (
    .A(_092_),
    .B(\MAR[0] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__and3b_2 _143_ (
    .A_N(\IN_R[3] ),
    .B(_105_),
    .C(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__or4_2 _144_ (
    .A(_053_),
    .B(_054_),
    .C(_056_),
    .D(_058_),
    .X(_059_)
  );
  sky130_fd_sc_hd__or3_2 _145_ (
    .A(_104_),
    .B(_051_),
    .C(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__buf_1 _146_ (
    .A(\STATO[2] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__nand2_2 _147_ (
    .A(_061_),
    .B(_047_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_2 _148_ (
    .A(\OUT_R[3] ),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__and4b_2 _149_ (
    .A_N(\OUT_R[3] ),
    .B(\MAR[0] ),
    .C(_105_),
    .D(_091_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21oi_2 _150_ (
    .A1(_060_),
    .A2(_063_),
    .B1(_064_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21a_2 _151_ (
    .A1(_092_),
    .A2(_108_),
    .B1(_055_),
    .X(_065_)
  );
  sky130_fd_sc_hd__a21oi_2 _152_ (
    .A1(_109_),
    .A2(_065_),
    .B1(\OUT_R[2] ),
    .Y(_066_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _153_ (
    .A1_N(_066_),
    .A2_N(_060_),
    .B1(\OUT_R[2] ),
    .B2(_062_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_2 _154_ (
    .A(\OUT_R[1] ),
    .B(_062_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _155_ (
    .A1_N(_060_),
    .A2_N(_067_),
    .B1(\OUT_R[1] ),
    .B2(_057_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _156_ (
    .A(\OUT_R[0] ),
    .B(_062_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a2bb2oi_2 _157_ (
    .A1_N(\OUT_R[0] ),
    .A2_N(_108_),
    .B1(_060_),
    .B2(_068_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__mux2_2 _158_ (
    .A0(\IN_R[7] ),
    .A1(I[7]),
    .S(_061_),
    .X(_069_)
  );
  sky130_fd_sc_hd__buf_1 _159_ (
    .A(_069_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_2 _160_ (
    .A0(\IN_R[6] ),
    .A1(I[6]),
    .S(_061_),
    .X(_070_)
  );
  sky130_fd_sc_hd__buf_1 _161_ (
    .A(_070_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_2 _162_ (
    .A0(\IN_R[5] ),
    .A1(I[5]),
    .S(_061_),
    .X(_071_)
  );
  sky130_fd_sc_hd__buf_1 _163_ (
    .A(_071_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_2 _164_ (
    .A0(\IN_R[4] ),
    .A1(I[4]),
    .S(_061_),
    .X(_072_)
  );
  sky130_fd_sc_hd__buf_1 _165_ (
    .A(_072_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_2 _166_ (
    .A0(\IN_R[3] ),
    .A1(I[3]),
    .S(_061_),
    .X(_073_)
  );
  sky130_fd_sc_hd__buf_1 _167_ (
    .A(_073_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_2 _168_ (
    .A0(\IN_R[2] ),
    .A1(I[2]),
    .S(_061_),
    .X(_074_)
  );
  sky130_fd_sc_hd__buf_1 _169_ (
    .A(_074_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_2 _170_ (
    .A0(\IN_R[1] ),
    .A1(I[1]),
    .S(_061_),
    .X(_075_)
  );
  sky130_fd_sc_hd__buf_1 _171_ (
    .A(_075_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_2 _172_ (
    .A0(\IN_R[0] ),
    .A1(I[0]),
    .S(_061_),
    .X(_076_)
  );
  sky130_fd_sc_hd__buf_1 _173_ (
    .A(_076_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand2_2 _174_ (
    .A(\STATO[3] ),
    .B(_097_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_2 _175_ (
    .A(START),
    .B(_077_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__mux2_2 _176_ (
    .A0(O[3]),
    .A1(\OUT_R[3] ),
    .S(_078_),
    .X(_079_)
  );
  sky130_fd_sc_hd__buf_1 _177_ (
    .A(_079_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_2 _178_ (
    .A0(O[2]),
    .A1(\OUT_R[2] ),
    .S(_078_),
    .X(_080_)
  );
  sky130_fd_sc_hd__buf_1 _179_ (
    .A(_080_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_2 _180_ (
    .A0(O[1]),
    .A1(\OUT_R[1] ),
    .S(_078_),
    .X(_081_)
  );
  sky130_fd_sc_hd__buf_1 _181_ (
    .A(_081_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_2 _182_ (
    .A0(O[0]),
    .A1(\OUT_R[0] ),
    .S(_078_),
    .X(_082_)
  );
  sky130_fd_sc_hd__buf_1 _183_ (
    .A(_082_),
    .X(_030_)
  );
  sky130_fd_sc_hd__inv_2 _184_ (
    .A(\STATO[3] ),
    .Y(_083_)
  );
  sky130_fd_sc_hd__inv_2 _185_ (
    .A(_061_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _186_ (
    .A1_N(_083_),
    .A2_N(_052_),
    .B1(_084_),
    .B2(_092_),
    .X(_029_)
  );
  sky130_fd_sc_hd__o21ai_2 _187_ (
    .A1(\STATO[2] ),
    .A2(\STATO[3] ),
    .B1(_077_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a22o_2 _188_ (
    .A1(\STATO[3] ),
    .A2(_096_),
    .B1(_085_),
    .B2(_095_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_2 _189_ (
    .A0(\STATO[3] ),
    .A1(_085_),
    .S(\MAR[0] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__buf_1 _190_ (
    .A(_086_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a31o_2 _191_ (
    .A1(START),
    .A2(\STATO[3] ),
    .A3(_097_),
    .B1(\STATO[1] ),
    .X(_003_)
  );
  sky130_fd_sc_hd__inv_2 _192_ (
    .A(\STATO[0] ),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a21oi_2 _193_ (
    .A1(_087_),
    .A2(_077_),
    .B1(START),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21ai_2 _194_ (
    .A1(_083_),
    .A2(_097_),
    .B1(_084_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and2_2 _195_ (
    .A(START),
    .B(\STATO[0] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__buf_1 _196_ (
    .A(_088_),
    .X(_000_)
  );
  sky130_fd_sc_hd__buf_1 _197_ (
    .A(RESET),
    .X(_089_)
  );
  sky130_fd_sc_hd__inv_2 _198_ (
    .A(_089_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _199_ (
    .A(_089_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _200_ (
    .A(_089_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _201_ (
    .A(_089_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_2 _202_ (
    .A(_089_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _203_ (
    .A(_089_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _204_ (
    .A(_089_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _205_ (
    .A(_089_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _206_ (
    .A(_089_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _207_ (
    .A(_089_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__buf_1 _208_ (
    .A(RESET),
    .X(_090_)
  );
  sky130_fd_sc_hd__inv_2 _209_ (
    .A(_090_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _210_ (
    .A(_090_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _211_ (
    .A(_090_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _212_ (
    .A(_090_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _213_ (
    .A(_090_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _214_ (
    .A(_090_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _215_ (
    .A(_090_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _216_ (
    .A(_090_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _217_ (
    .A(_090_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _218_ (
    .A(_090_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _219_ (
    .A(RESET),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _220_ (
    .A(RESET),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _221_ (
    .A(RESET),
    .Y(_026_)
  );
  sky130_fd_sc_hd__dfstp_2 _222_ (
    .CLK(CLOCK),
    .D(_001_),
    .Q(\STATO[0] ),
    .SET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_2 _223_ (
    .CLK(CLOCK),
    .D(_002_),
    .Q(\STATO[1] ),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_2 _224_ (
    .CLK(CLOCK),
    .D(_000_),
    .Q(\STATO[2] ),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_2 _225_ (
    .CLK(CLOCK),
    .D(_003_),
    .Q(\STATO[3] ),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_2 _226_ (
    .CLK(CLOCK),
    .D(_027_),
    .Q(\MAR[0] ),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_2 _227_ (
    .CLK(CLOCK),
    .D(_028_),
    .Q(\MAR[1] ),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_2 _228_ (
    .CLK(CLOCK),
    .D(_029_),
    .Q(\MAR[2] ),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfrtp_2 _229_ (
    .CLK(CLOCK),
    .D(_030_),
    .Q(O[0]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_2 _230_ (
    .CLK(CLOCK),
    .D(_031_),
    .Q(O[1]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_2 _231_ (
    .CLK(CLOCK),
    .D(_032_),
    .Q(O[2]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_2 _232_ (
    .CLK(CLOCK),
    .D(_033_),
    .Q(O[3]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_2 _233_ (
    .CLK(CLOCK),
    .D(_034_),
    .Q(\IN_R[0] ),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_2 _234_ (
    .CLK(CLOCK),
    .D(_035_),
    .Q(\IN_R[1] ),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_2 _235_ (
    .CLK(CLOCK),
    .D(_036_),
    .Q(\IN_R[2] ),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_2 _236_ (
    .CLK(CLOCK),
    .D(_037_),
    .Q(\IN_R[3] ),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _237_ (
    .CLK(CLOCK),
    .D(_038_),
    .Q(\IN_R[4] ),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_2 _238_ (
    .CLK(CLOCK),
    .D(_039_),
    .Q(\IN_R[5] ),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_2 _239_ (
    .CLK(CLOCK),
    .D(_040_),
    .Q(\IN_R[6] ),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_2 _240_ (
    .CLK(CLOCK),
    .D(_041_),
    .Q(\IN_R[7] ),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_2 _241_ (
    .CLK(CLOCK),
    .D(_042_),
    .Q(\OUT_R[0] ),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_2 _242_ (
    .CLK(CLOCK),
    .D(_043_),
    .Q(\OUT_R[1] ),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_2 _243_ (
    .CLK(CLOCK),
    .D(_044_),
    .Q(\OUT_R[2] ),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_2 _244_ (
    .CLK(CLOCK),
    .D(_045_),
    .Q(\OUT_R[3] ),
    .RESET_B(_026_)
  );
endmodule
