// Auto-generated mapped fault enables:
//   fault_en[0] -> _48_ -> u[0]
//   fault_en[1] -> _49_ -> stato[0]
//   fault_en[2] -> _50_ -> stato[1]
//   fault_en[3] -> _51_ -> stato[2]
//   fault_en[4] -> _52_ -> stato[3]
//   fault_en[5] -> _53_ -> stato[4]
//   fault_en[6] -> _54_ -> stato[5]
//   fault_en[7] -> _55_ -> stato[6]

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b02(reset, clock, linea, u, fault_en);
    input [7:0] fault_en;
wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  input clock;
  wire clock;
  input linea;
  wire linea;
  input reset;
  wire reset;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  wire \stato[3] ;
  wire \stato[4] ;
  wire \stato[5] ;
  wire \stato[6] ;
  output u;
  wire u;
  sky130_fd_sc_hd__or4_2 _24_ (
    .A(\stato[5] ),
    .B(\stato[4] ),
    .C(\stato[3] ),
    .D(\stato[6] ),
    .X(_16_)
  );
  sky130_fd_sc_hd__nor2_2 _25_ (
    .A(u),
    .B(\stato[1] ),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nor4_2 _26_ (
    .A(\stato[0] ),
    .B(\stato[2] ),
    .C(_16_),
    .D(_17_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__or2_2 _27_ (
    .A(\stato[1] ),
    .B(\stato[0] ),
    .X(_18_)
  );
  sky130_fd_sc_hd__buf_1 _28_ (
    .A(_18_),
    .X(_06_)
  );
  sky130_fd_sc_hd__a21o_2 _29_ (
    .A1(linea),
    .A2(\stato[2] ),
    .B1(\stato[5] ),
    .X(_05_)
  );
  sky130_fd_sc_hd__inv_2 _30_ (
    .A(linea),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a21o_2 _31_ (
    .A1(_19_),
    .A2(\stato[3] ),
    .B1(\stato[6] ),
    .X(_04_)
  );
  sky130_fd_sc_hd__and2_2 _32_ (
    .A(_19_),
    .B(\stato[2] ),
    .X(_20_)
  );
  sky130_fd_sc_hd__buf_1 _33_ (
    .A(_20_),
    .X(_03_)
  );
  sky130_fd_sc_hd__and2_2 _34_ (
    .A(_19_),
    .B(\stato[4] ),
    .X(_21_)
  );
  sky130_fd_sc_hd__buf_1 _35_ (
    .A(_21_),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_2 _36_ (
    .A(linea),
    .B(\stato[4] ),
    .X(_22_)
  );
  sky130_fd_sc_hd__buf_1 _37_ (
    .A(_22_),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_2 _38_ (
    .A(linea),
    .B(\stato[3] ),
    .X(_23_)
  );
  sky130_fd_sc_hd__buf_1 _39_ (
    .A(_23_),
    .X(_00_)
  );
  sky130_fd_sc_hd__inv_2 _40_ (
    .A(reset),
    .Y(_07_)
  );
  sky130_fd_sc_hd__inv_2 _41_ (
    .A(reset),
    .Y(_08_)
  );
  sky130_fd_sc_hd__inv_2 _42_ (
    .A(reset),
    .Y(_09_)
  );
  sky130_fd_sc_hd__inv_2 _43_ (
    .A(reset),
    .Y(_10_)
  );
  sky130_fd_sc_hd__inv_2 _44_ (
    .A(reset),
    .Y(_11_)
  );
  sky130_fd_sc_hd__inv_2 _45_ (
    .A(reset),
    .Y(_12_)
  );
  sky130_fd_sc_hd__inv_2 _46_ (
    .A(reset),
    .Y(_13_)
  );
  sky130_fd_sc_hd__inv_2 _47_ (
    .A(reset),
    .Y(_14_)
  );
  FI_DFF_DFRTP_FAULTY _48_ (
    .CLK(clock),
    .D(_15_),
    .RESET_B(_07_),
    .fault_en(fault_en[0]),
    .Q(u)
  );
sky130_fd_sc_hd__dfstp_2 _49_ (
    .CLK(clock),
    .D(_00_),
    .Q(\stato[0] ),
    .SET_B(_08_)
  );
  FI_DFF_DFRTP_FAULTY _50_ (
    .CLK(clock),
    .D(_04_),
    .RESET_B(_09_),
    .fault_en(fault_en[2]),
    .Q(\stato[1] )
  );
FI_DFF_DFRTP_FAULTY _51_ (
  .CLK(clock),
  .D(_01_),
  .RESET_B(_10_),
  .fault_en(fault_en[3]),
  .Q(\stato[2] )
);
FI_DFF_DFRTP_FAULTY _52_ (
  .CLK(clock),
  .D(_05_),
  .RESET_B(_11_),
  .fault_en(fault_en[4]),
  .Q(\stato[3] )
);
FI_DFF_DFRTP_FAULTY _53_ (
  .CLK(clock),
  .D(_06_),
  .RESET_B(_12_),
  .fault_en(fault_en[5]),
  .Q(\stato[4] )
);
FI_DFF_DFRTP_FAULTY _54_ (
  .CLK(clock),
  .D(_02_),
  .RESET_B(_13_),
  .fault_en(fault_en[6]),
  .Q(\stato[5] )
);
FI_DFF_DFRTP_FAULTY _55_ (
  .CLK(clock),
  .D(_03_),
  .RESET_B(_14_),
  .fault_en(fault_en[7]),
  .Q(\stato[6] )
);
endmodule
