// Auto-generated mapped fault enables:
//   fault_en[0] -> _467_ -> stato[0] (RTL)
//   fault_en[1] -> _468_ -> stato[1] (RTL)
//   fault_en[2] -> _469_ -> stato[2] (RTL)
//   fault_en[3] -> _470_ -> stato[3] (GL_ONLY)
//   fault_en[4] -> _471_ -> stato[4] (GL_ONLY)
//   fault_en[5] -> _472_ -> stato[5] (GL_ONLY)
//   fault_en[6] -> _473_ -> stato[6] (GL_ONLY)
//   fault_en[7] -> _474_ -> mar[0] (RTL)
//   fault_en[8] -> _475_ -> mar[1] (RTL)
//   fault_en[9] -> _476_ -> mar[2] (RTL)
//   fault_en[10] -> _477_ -> mar[3] (RTL)
//   fault_en[11] -> _478_ -> punti_retta[0] (RTL)
//   fault_en[12] -> _479_ -> punti_retta[1] (RTL)
//   fault_en[13] -> _480_ -> punti_retta[2] (RTL)
//   fault_en[14] -> _481_ -> punti_retta[3] (RTL)
//   fault_en[15] -> _482_ -> punti_retta[4] (RTL)
//   fault_en[16] -> _483_ -> punti_retta[5] (RTL)
//   fault_en[17] -> _484_ -> punti_retta[6] (RTL)
//   fault_en[18] -> _485_ -> punti_retta[7] (RTL)
//   fault_en[19] -> _486_ -> cont[0] (RTL)
//   fault_en[20] -> _487_ -> cont[1] (RTL)
//   fault_en[21] -> _488_ -> cont[2] (RTL)
//   fault_en[22] -> _489_ -> cont[3] (RTL)
//   fault_en[23] -> _490_ -> cont[4] (RTL)
//   fault_en[24] -> _491_ -> cont[5] (RTL)
//   fault_en[25] -> _492_ -> cont[6] (RTL)
//   fault_en[26] -> _493_ -> cont[7] (RTL)
//   fault_en[27] -> _494_ -> x[0] (RTL)
//   fault_en[28] -> _495_ -> x[1] (RTL)
//   fault_en[29] -> _496_ -> x[2] (RTL)
//   fault_en[30] -> _497_ -> x[3] (RTL)
//   fault_en[31] -> _498_ -> x[4] (RTL)
//   fault_en[32] -> _499_ -> x[5] (RTL)
//   fault_en[33] -> _500_ -> x[6] (RTL)
//   fault_en[34] -> _501_ -> x[7] (RTL)
//   fault_en[35] -> _502_ -> y[0] (RTL)
//   fault_en[36] -> _503_ -> y[1] (RTL)
//   fault_en[37] -> _504_ -> y[2] (RTL)
//   fault_en[38] -> _505_ -> y[3] (RTL)
//   fault_en[39] -> _506_ -> t[1] (RTL)
//   fault_en[40] -> _507_ -> t[2] (RTL)
//   fault_en[41] -> _508_ -> t[3] (RTL)
//   fault_en[42] -> _509_ -> t[4] (RTL)
//   fault_en[43] -> _510_ -> t[5] (RTL)
//   fault_en[44] -> _511_ -> t[6] (RTL)

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b07(punti_retta, start, reset, clock, fault_en);
  input [44:0] fault_en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  input clock;
  wire clock;
  wire \cont[0] ;
  wire \cont[1] ;
  wire \cont[2] ;
  wire \cont[3] ;
  wire \cont[4] ;
  wire \cont[5] ;
  wire \cont[6] ;
  wire \cont[7] ;
  wire \mar[0] ;
  wire \mar[1] ;
  wire \mar[2] ;
  wire \mar[3] ;
  output [7:0] punti_retta;
  wire [7:0] punti_retta;
  input reset;
  wire reset;
  input start;
  wire start;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  wire \stato[3] ;
  wire \stato[4] ;
  wire \stato[5] ;
  wire \stato[6] ;
  wire \t[1] ;
  wire \t[2] ;
  wire \t[3] ;
  wire \t[4] ;
  wire \t[5] ;
  wire \t[6] ;
  wire \x[0] ;
  wire \x[1] ;
  wire \x[2] ;
  wire \x[3] ;
  wire \x[4] ;
  wire \x[5] ;
  wire \x[6] ;
  wire \x[7] ;
  wire \y[0] ;
  wire \y[1] ;
  wire \y[2] ;
  wire \y[3] ;
  sky130_fd_sc_hd__mux2_2 _234_ (
    .A0(\t[6] ),
    .A1(\x[5] ),
    .S(\stato[6] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__buf_1 _235_ (
    .A(_086_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_2 _236_ (
    .A0(\t[5] ),
    .A1(\x[4] ),
    .S(\stato[6] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__buf_1 _237_ (
    .A(_087_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_2 _238_ (
    .A0(\t[4] ),
    .A1(\x[3] ),
    .S(\stato[6] ),
    .X(_088_)
  );
  sky130_fd_sc_hd__buf_1 _239_ (
    .A(_088_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_2 _240_ (
    .A0(\t[3] ),
    .A1(\x[2] ),
    .S(\stato[6] ),
    .X(_089_)
  );
  sky130_fd_sc_hd__buf_1 _241_ (
    .A(_089_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_2 _242_ (
    .A0(\t[2] ),
    .A1(\x[1] ),
    .S(\stato[6] ),
    .X(_090_)
  );
  sky130_fd_sc_hd__buf_1 _243_ (
    .A(_090_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_2 _244_ (
    .A0(\t[1] ),
    .A1(\x[0] ),
    .S(\stato[6] ),
    .X(_091_)
  );
  sky130_fd_sc_hd__buf_1 _245_ (
    .A(_091_),
    .X(_080_)
  );
  sky130_fd_sc_hd__or3_2 _246_ (
    .A(\mar[3] ),
    .B(\mar[2] ),
    .C(\mar[1] ),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2_2 _247_ (
    .A(\mar[3] ),
    .B(\mar[1] ),
    .Y(_093_)
  );
  sky130_fd_sc_hd__o21ba_2 _248_ (
    .A1(\mar[2] ),
    .A2(_093_),
    .B1_N(\mar[0] ),
    .X(_094_)
  );
  sky130_fd_sc_hd__a21oi_2 _249_ (
    .A1(\mar[0] ),
    .A2(_092_),
    .B1(_094_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__mux2_2 _250_ (
    .A0(\y[3] ),
    .A1(_095_),
    .S(\stato[1] ),
    .X(_096_)
  );
  sky130_fd_sc_hd__buf_1 _251_ (
    .A(_096_),
    .X(_079_)
  );
  sky130_fd_sc_hd__o21ai_2 _252_ (
    .A1(\mar[2] ),
    .A2(_093_),
    .B1(_092_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__and2b_2 _253_ (
    .A_N(_094_),
    .B(_097_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_2 _254_ (
    .A0(\y[2] ),
    .A1(_098_),
    .S(\stato[1] ),
    .X(_099_)
  );
  sky130_fd_sc_hd__buf_1 _255_ (
    .A(_099_),
    .X(_078_)
  );
  sky130_fd_sc_hd__and2_2 _256_ (
    .A(\mar[2] ),
    .B(\mar[0] ),
    .X(_100_)
  );
  sky130_fd_sc_hd__nor2_2 _257_ (
    .A(\mar[2] ),
    .B(\mar[0] ),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21a_2 _258_ (
    .A1(_100_),
    .A2(_101_),
    .B1(\mar[3] ),
    .X(_102_)
  );
  sky130_fd_sc_hd__mux2_2 _259_ (
    .A0(\mar[0] ),
    .A1(_102_),
    .S(\mar[1] ),
    .X(_103_)
  );
  sky130_fd_sc_hd__mux2_2 _260_ (
    .A0(\y[1] ),
    .A1(_103_),
    .S(\stato[1] ),
    .X(_104_)
  );
  sky130_fd_sc_hd__buf_1 _261_ (
    .A(_104_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_2 _262_ (
    .A0(\y[0] ),
    .A1(_097_),
    .S(\stato[1] ),
    .X(_105_)
  );
  sky130_fd_sc_hd__buf_1 _263_ (
    .A(_105_),
    .X(_076_)
  );
  sky130_fd_sc_hd__buf_1 _264_ (
    .A(\stato[5] ),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_2 _265_ (
    .A0(\t[6] ),
    .A1(\y[3] ),
    .S(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__xor2_2 _266_ (
    .A(\x[6] ),
    .B(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_2 _267_ (
    .A0(\t[5] ),
    .A1(\y[3] ),
    .S(_106_),
    .X(_109_)
  );
  sky130_fd_sc_hd__or2_2 _268_ (
    .A(\x[5] ),
    .B(_109_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_2 _269_ (
    .A0(\t[4] ),
    .A1(\y[3] ),
    .S(_106_),
    .X(_111_)
  );
  sky130_fd_sc_hd__nand2_2 _270_ (
    .A(\x[4] ),
    .B(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__or2_2 _271_ (
    .A(\x[4] ),
    .B(_111_),
    .X(_113_)
  );
  sky130_fd_sc_hd__and2_2 _272_ (
    .A(_112_),
    .B(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_2 _273_ (
    .A0(\t[3] ),
    .A1(\y[3] ),
    .S(_106_),
    .X(_115_)
  );
  sky130_fd_sc_hd__or2_2 _274_ (
    .A(\x[3] ),
    .B(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_2 _275_ (
    .A0(\t[2] ),
    .A1(\y[2] ),
    .S(_106_),
    .X(_117_)
  );
  sky130_fd_sc_hd__nand2_2 _276_ (
    .A(\x[2] ),
    .B(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__or2_2 _277_ (
    .A(\x[2] ),
    .B(_117_),
    .X(_119_)
  );
  sky130_fd_sc_hd__and2_2 _278_ (
    .A(\y[0] ),
    .B(_106_),
    .X(_120_)
  );
  sky130_fd_sc_hd__mux2_2 _279_ (
    .A0(\t[1] ),
    .A1(\y[1] ),
    .S(\stato[5] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__or2_2 _280_ (
    .A(\x[1] ),
    .B(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__and2_2 _281_ (
    .A(\x[1] ),
    .B(_121_),
    .X(_123_)
  );
  sky130_fd_sc_hd__a31o_2 _282_ (
    .A1(\x[0] ),
    .A2(_120_),
    .A3(_122_),
    .B1(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__nand2_2 _283_ (
    .A(\x[3] ),
    .B(_115_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_2 _284_ (
    .A(_118_),
    .B(_125_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__a31o_2 _285_ (
    .A1(_118_),
    .A2(_119_),
    .A3(_124_),
    .B1(_126_),
    .X(_127_)
  );
  sky130_fd_sc_hd__nand2_2 _286_ (
    .A(\x[5] ),
    .B(_109_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_2 _287_ (
    .A(_112_),
    .B(_128_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a31o_2 _288_ (
    .A1(_114_),
    .A2(_116_),
    .A3(_127_),
    .B1(_129_),
    .X(_130_)
  );
  sky130_fd_sc_hd__nor2_2 _289_ (
    .A(\stato[1] ),
    .B(_106_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a31o_2 _290_ (
    .A1(_108_),
    .A2(_110_),
    .A3(_130_),
    .B1(_131_),
    .X(_132_)
  );
  sky130_fd_sc_hd__a21oi_2 _291_ (
    .A1(\x[6] ),
    .A2(_107_),
    .B1(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__or2_2 _292_ (
    .A(\stato[1] ),
    .B(_106_),
    .X(_134_)
  );
  sky130_fd_sc_hd__buf_1 _293_ (
    .A(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a21oi_2 _294_ (
    .A1(\stato[2] ),
    .A2(_095_),
    .B1(_135_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nor2_2 _295_ (
    .A(\stato[2] ),
    .B(_135_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _296_ (
    .A1_N(_133_),
    .A2_N(_136_),
    .B1(_137_),
    .B2(\x[7] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__a21oi_2 _297_ (
    .A1(_095_),
    .A2(_131_),
    .B1(_137_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__a21oi_2 _298_ (
    .A1(_110_),
    .A2(_130_),
    .B1(_108_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__or2_2 _299_ (
    .A(_132_),
    .B(_139_),
    .X(_140_)
  );
  sky130_fd_sc_hd__or2_2 _300_ (
    .A(\stato[2] ),
    .B(_135_),
    .X(_141_)
  );
  sky130_fd_sc_hd__buf_1 _301_ (
    .A(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _302_ (
    .A1_N(_138_),
    .A2_N(_140_),
    .B1(_142_),
    .B2(\x[6] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__nand3_2 _303_ (
    .A(_114_),
    .B(_116_),
    .C(_127_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_2 _304_ (
    .A(_110_),
    .B(_128_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__and3_2 _305_ (
    .A(_112_),
    .B(_143_),
    .C(_144_),
    .X(_145_)
  );
  sky130_fd_sc_hd__a21oi_2 _306_ (
    .A1(_112_),
    .A2(_143_),
    .B1(_144_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__or3_2 _307_ (
    .A(_131_),
    .B(_145_),
    .C(_146_),
    .X(_147_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _308_ (
    .A1_N(_138_),
    .A2_N(_147_),
    .B1(\x[5] ),
    .B2(_142_),
    .X(_073_)
  );
  sky130_fd_sc_hd__a21o_2 _309_ (
    .A1(_116_),
    .A2(_127_),
    .B1(_114_),
    .X(_148_)
  );
  sky130_fd_sc_hd__a21oi_2 _310_ (
    .A1(_143_),
    .A2(_148_),
    .B1(_131_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _311_ (
    .A1_N(_136_),
    .A2_N(_149_),
    .B1(\x[4] ),
    .B2(_137_),
    .X(_072_)
  );
  sky130_fd_sc_hd__and3_2 _312_ (
    .A(_118_),
    .B(_119_),
    .C(_124_),
    .X(_150_)
  );
  sky130_fd_sc_hd__a21oi_2 _313_ (
    .A1(\x[2] ),
    .A2(_117_),
    .B1(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a21o_2 _314_ (
    .A1(_116_),
    .A2(_125_),
    .B1(_151_),
    .X(_152_)
  );
  sky130_fd_sc_hd__or2b_2 _315_ (
    .A(_127_),
    .B_N(_116_),
    .X(_153_)
  );
  sky130_fd_sc_hd__a31oi_2 _316_ (
    .A1(_135_),
    .A2(_152_),
    .A3(_153_),
    .B1(_136_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a21o_2 _317_ (
    .A1(\x[3] ),
    .A2(_137_),
    .B1(_154_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_2 _318_ (
    .A(\stato[2] ),
    .B(_131_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_2 _319_ (
    .A1(_118_),
    .A2(_119_),
    .B1(_124_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__o21ai_2 _320_ (
    .A1(_150_),
    .A2(_156_),
    .B1(_135_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o221a_2 _321_ (
    .A1(\x[2] ),
    .A2(_142_),
    .B1(_155_),
    .B2(_098_),
    .C1(_157_),
    .X(_070_)
  );
  sky130_fd_sc_hd__inv_2 _322_ (
    .A(_123_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__and4_2 _323_ (
    .A(\x[0] ),
    .B(_158_),
    .C(_120_),
    .D(_122_),
    .X(_159_)
  );
  sky130_fd_sc_hd__a22o_2 _324_ (
    .A1(\x[0] ),
    .A2(_120_),
    .B1(_122_),
    .B2(_158_),
    .X(_160_)
  );
  sky130_fd_sc_hd__inv_2 _325_ (
    .A(_160_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21ai_2 _326_ (
    .A1(_159_),
    .A2(_161_),
    .B1(_135_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__o221a_2 _327_ (
    .A1(\x[1] ),
    .A2(_142_),
    .B1(_155_),
    .B2(_103_),
    .C1(_162_),
    .X(_069_)
  );
  sky130_fd_sc_hd__nand2_2 _328_ (
    .A(\y[0] ),
    .B(_106_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _329_ (
    .A1_N(\x[0] ),
    .A2_N(_163_),
    .B1(_097_),
    .B2(_131_),
    .X(_164_)
  );
  sky130_fd_sc_hd__a32o_2 _330_ (
    .A1(\x[0] ),
    .A2(_163_),
    .A3(_155_),
    .B1(_164_),
    .B2(_142_),
    .X(_068_)
  );
  sky130_fd_sc_hd__buf_1 _331_ (
    .A(\stato[3] ),
    .X(_165_)
  );
  sky130_fd_sc_hd__or4b_2 _332_ (
    .A(\x[0] ),
    .B(\x[7] ),
    .C(\x[6] ),
    .D_N(\x[1] ),
    .X(_166_)
  );
  sky130_fd_sc_hd__or4_2 _333_ (
    .A(\x[5] ),
    .B(\x[4] ),
    .C(\x[3] ),
    .D(\x[2] ),
    .X(_167_)
  );
  sky130_fd_sc_hd__nor2_2 _334_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__and3_2 _335_ (
    .A(\cont[2] ),
    .B(\cont[1] ),
    .C(\cont[0] ),
    .X(_169_)
  );
  sky130_fd_sc_hd__and4_2 _336_ (
    .A(\cont[5] ),
    .B(\cont[4] ),
    .C(\cont[3] ),
    .D(_169_),
    .X(_170_)
  );
  sky130_fd_sc_hd__and3_2 _337_ (
    .A(\cont[6] ),
    .B(_168_),
    .C(_170_),
    .X(_171_)
  );
  sky130_fd_sc_hd__or2_2 _338_ (
    .A(\cont[7] ),
    .B(_171_),
    .X(_172_)
  );
  sky130_fd_sc_hd__nand2_2 _339_ (
    .A(\cont[7] ),
    .B(_171_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__and3_2 _340_ (
    .A(_165_),
    .B(_172_),
    .C(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd__inv_2 _341_ (
    .A(_165_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_2 _342_ (
    .A(_175_),
    .B(_168_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__inv_2 _343_ (
    .A(\stato[4] ),
    .Y(_177_)
  );
  sky130_fd_sc_hd__and3_2 _344_ (
    .A(\mar[3] ),
    .B(\mar[1] ),
    .C(_100_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nand2_2 _345_ (
    .A(\stato[3] ),
    .B(_178_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o21a_2 _346_ (
    .A1(_177_),
    .A2(start),
    .B1(_179_),
    .X(_180_)
  );
  sky130_fd_sc_hd__o21ai_2 _347_ (
    .A1(\stato[4] ),
    .A2(_165_),
    .B1(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__nor2_2 _348_ (
    .A(_176_),
    .B(_181_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__mux2_2 _349_ (
    .A0(\cont[7] ),
    .A1(_174_),
    .S(_182_),
    .X(_183_)
  );
  sky130_fd_sc_hd__buf_1 _350_ (
    .A(_183_),
    .X(_067_)
  );
  sky130_fd_sc_hd__or2_2 _351_ (
    .A(_176_),
    .B(_181_),
    .X(_184_)
  );
  sky130_fd_sc_hd__buf_1 _352_ (
    .A(_184_),
    .X(_185_)
  );
  sky130_fd_sc_hd__nor2_2 _353_ (
    .A(_175_),
    .B(_185_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__xor2_2 _354_ (
    .A(\cont[6] ),
    .B(_170_),
    .X(_187_)
  );
  sky130_fd_sc_hd__a22o_2 _355_ (
    .A1(\cont[6] ),
    .A2(_185_),
    .B1(_186_),
    .B2(_187_),
    .X(_066_)
  );
  sky130_fd_sc_hd__and2_2 _356_ (
    .A(_168_),
    .B(_170_),
    .X(_188_)
  );
  sky130_fd_sc_hd__a41o_2 _357_ (
    .A1(\cont[4] ),
    .A2(\cont[3] ),
    .A3(_168_),
    .A4(_169_),
    .B1(\cont[5] ),
    .X(_189_)
  );
  sky130_fd_sc_hd__and3b_2 _358_ (
    .A_N(_188_),
    .B(_189_),
    .C(_165_),
    .X(_190_)
  );
  sky130_fd_sc_hd__mux2_2 _359_ (
    .A0(\cont[5] ),
    .A1(_190_),
    .S(_182_),
    .X(_191_)
  );
  sky130_fd_sc_hd__buf_1 _360_ (
    .A(_191_),
    .X(_065_)
  );
  sky130_fd_sc_hd__nand2_2 _361_ (
    .A(\cont[3] ),
    .B(_169_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__xor2_2 _362_ (
    .A(\cont[4] ),
    .B(_192_),
    .X(_193_)
  );
  sky130_fd_sc_hd__inv_2 _363_ (
    .A(_193_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__a22o_2 _364_ (
    .A1(\cont[4] ),
    .A2(_185_),
    .B1(_186_),
    .B2(_194_),
    .X(_064_)
  );
  sky130_fd_sc_hd__a21o_2 _365_ (
    .A1(_168_),
    .A2(_169_),
    .B1(\cont[3] ),
    .X(_195_)
  );
  sky130_fd_sc_hd__o311a_2 _366_ (
    .A1(_166_),
    .A2(_167_),
    .A3(_192_),
    .B1(_195_),
    .C1(_165_),
    .X(_196_)
  );
  sky130_fd_sc_hd__mux2_2 _367_ (
    .A0(\cont[3] ),
    .A1(_196_),
    .S(_182_),
    .X(_197_)
  );
  sky130_fd_sc_hd__buf_1 _368_ (
    .A(_197_),
    .X(_063_)
  );
  sky130_fd_sc_hd__a21oi_2 _369_ (
    .A1(\cont[1] ),
    .A2(\cont[0] ),
    .B1(\cont[2] ),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nor2_2 _370_ (
    .A(_169_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__a22o_2 _371_ (
    .A1(\cont[2] ),
    .A2(_185_),
    .B1(_186_),
    .B2(_199_),
    .X(_062_)
  );
  sky130_fd_sc_hd__xor2_2 _372_ (
    .A(\cont[1] ),
    .B(\cont[0] ),
    .X(_200_)
  );
  sky130_fd_sc_hd__a22o_2 _373_ (
    .A1(\cont[1] ),
    .A2(_185_),
    .B1(_186_),
    .B2(_200_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_2 _374_ (
    .A0(_186_),
    .A1(_185_),
    .S(\cont[0] ),
    .X(_201_)
  );
  sky130_fd_sc_hd__buf_1 _375_ (
    .A(_201_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nor2_2 _376_ (
    .A(_175_),
    .B(_178_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__a211o_2 _377_ (
    .A1(_177_),
    .A2(_175_),
    .B1(start),
    .C1(_202_),
    .X(_203_)
  );
  sky130_fd_sc_hd__mux2_2 _378_ (
    .A0(_174_),
    .A1(punti_retta[7]),
    .S(_203_),
    .X(_204_)
  );
  sky130_fd_sc_hd__buf_1 _379_ (
    .A(_204_),
    .X(_059_)
  );
  sky130_fd_sc_hd__nor2_2 _380_ (
    .A(start),
    .B(_179_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__o21ai_2 _381_ (
    .A1(\cont[6] ),
    .A2(_188_),
    .B1(_205_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _382_ (
    .A1_N(_171_),
    .A2_N(_206_),
    .B1(_203_),
    .B2(punti_retta[6]),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_2 _383_ (
    .A0(_190_),
    .A1(punti_retta[5]),
    .S(_203_),
    .X(_207_)
  );
  sky130_fd_sc_hd__buf_1 _384_ (
    .A(_207_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_2 _385_ (
    .A0(\cont[4] ),
    .A1(_194_),
    .S(_168_),
    .X(_208_)
  );
  sky130_fd_sc_hd__a22o_2 _386_ (
    .A1(punti_retta[4]),
    .A2(_203_),
    .B1(_205_),
    .B2(_208_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_2 _387_ (
    .A0(_196_),
    .A1(punti_retta[3]),
    .S(_203_),
    .X(_209_)
  );
  sky130_fd_sc_hd__buf_1 _388_ (
    .A(_209_),
    .X(_055_)
  );
  sky130_fd_sc_hd__or2_2 _389_ (
    .A(\cont[2] ),
    .B(_168_),
    .X(_210_)
  );
  sky130_fd_sc_hd__o311a_2 _390_ (
    .A1(_166_),
    .A2(_167_),
    .A3(_199_),
    .B1(_210_),
    .C1(_165_),
    .X(_211_)
  );
  sky130_fd_sc_hd__mux2_2 _391_ (
    .A0(_211_),
    .A1(punti_retta[2]),
    .S(_203_),
    .X(_212_)
  );
  sky130_fd_sc_hd__buf_1 _392_ (
    .A(_212_),
    .X(_054_)
  );
  sky130_fd_sc_hd__and3_2 _393_ (
    .A(_165_),
    .B(_168_),
    .C(_200_),
    .X(_213_)
  );
  sky130_fd_sc_hd__a21o_2 _394_ (
    .A1(\cont[1] ),
    .A2(_176_),
    .B1(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd__mux2_2 _395_ (
    .A0(_214_),
    .A1(punti_retta[1]),
    .S(_203_),
    .X(_215_)
  );
  sky130_fd_sc_hd__buf_1 _396_ (
    .A(_215_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand2_2 _397_ (
    .A(\cont[0] ),
    .B(_168_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__or2_2 _398_ (
    .A(\cont[0] ),
    .B(_168_),
    .X(_217_)
  );
  sky130_fd_sc_hd__a32o_2 _399_ (
    .A1(_205_),
    .A2(_216_),
    .A3(_217_),
    .B1(_203_),
    .B2(punti_retta[0]),
    .X(_052_)
  );
  sky130_fd_sc_hd__inv_2 _400_ (
    .A(\mar[3] ),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand2_2 _401_ (
    .A(\mar[1] ),
    .B(_100_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21a_2 _402_ (
    .A1(\stato[6] ),
    .A2(_165_),
    .B1(_180_),
    .X(_220_)
  );
  sky130_fd_sc_hd__a21bo_2 _403_ (
    .A1(_218_),
    .A2(_219_),
    .B1_N(_220_),
    .X(_221_)
  );
  sky130_fd_sc_hd__o31ai_2 _404_ (
    .A1(\stato[6] ),
    .A2(\stato[4] ),
    .A3(_165_),
    .B1(_180_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _405_ (
    .A1_N(_178_),
    .A2_N(_221_),
    .B1(_222_),
    .B2(\mar[3] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__a21o_2 _406_ (
    .A1(\mar[1] ),
    .A2(\mar[0] ),
    .B1(\mar[2] ),
    .X(_223_)
  );
  sky130_fd_sc_hd__a32o_2 _407_ (
    .A1(_219_),
    .A2(_220_),
    .A3(_223_),
    .B1(_222_),
    .B2(\mar[2] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__or2_2 _408_ (
    .A(\mar[1] ),
    .B(\mar[0] ),
    .X(_224_)
  );
  sky130_fd_sc_hd__nand2_2 _409_ (
    .A(\mar[1] ),
    .B(\mar[0] ),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a32o_2 _410_ (
    .A1(_224_),
    .A2(_225_),
    .A3(_220_),
    .B1(_222_),
    .B2(\mar[1] ),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_2 _411_ (
    .A0(_220_),
    .A1(_222_),
    .S(\mar[0] ),
    .X(_226_)
  );
  sky130_fd_sc_hd__buf_1 _412_ (
    .A(_226_),
    .X(_048_)
  );
  sky130_fd_sc_hd__inv_2 _413_ (
    .A(start),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a211o_2 _414_ (
    .A1(\stato[4] ),
    .A2(_227_),
    .B1(\stato[0] ),
    .C1(_205_),
    .X(_002_)
  );
  sky130_fd_sc_hd__a31o_2 _415_ (
    .A1(_165_),
    .A2(start),
    .A3(_178_),
    .B1(_106_),
    .X(_001_)
  );
  sky130_fd_sc_hd__a21o_2 _416_ (
    .A1(\stato[4] ),
    .A2(start),
    .B1(_202_),
    .X(_000_)
  );
  sky130_fd_sc_hd__buf_1 _417_ (
    .A(reset),
    .X(_228_)
  );
  sky130_fd_sc_hd__buf_1 _418_ (
    .A(_228_),
    .X(_229_)
  );
  sky130_fd_sc_hd__inv_2 _419_ (
    .A(_229_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _420_ (
    .A(_229_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _421_ (
    .A(_229_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _422_ (
    .A(_229_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _423_ (
    .A(_229_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_2 _424_ (
    .A(_229_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _425_ (
    .A(_229_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _426_ (
    .A(_229_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _427_ (
    .A(_229_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _428_ (
    .A(_229_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__buf_1 _429_ (
    .A(_228_),
    .X(_230_)
  );
  sky130_fd_sc_hd__inv_2 _430_ (
    .A(_230_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _431_ (
    .A(_230_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _432_ (
    .A(_230_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _433_ (
    .A(_230_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _434_ (
    .A(_230_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _435_ (
    .A(_230_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _436_ (
    .A(_230_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _437_ (
    .A(_230_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _438_ (
    .A(_230_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _439_ (
    .A(_230_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__buf_1 _440_ (
    .A(_228_),
    .X(_231_)
  );
  sky130_fd_sc_hd__inv_2 _441_ (
    .A(_231_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _442_ (
    .A(_231_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _443_ (
    .A(_231_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _444_ (
    .A(_231_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _445_ (
    .A(_231_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _446_ (
    .A(_231_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _447_ (
    .A(_231_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _448_ (
    .A(_231_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _449_ (
    .A(_231_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__inv_2 _450_ (
    .A(_231_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__buf_1 _451_ (
    .A(_228_),
    .X(_232_)
  );
  sky130_fd_sc_hd__inv_2 _452_ (
    .A(_232_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__inv_2 _453_ (
    .A(_232_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__inv_2 _454_ (
    .A(_232_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__inv_2 _455_ (
    .A(_232_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__inv_2 _456_ (
    .A(_232_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__inv_2 _457_ (
    .A(_232_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_2 _458_ (
    .A(_232_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_2 _459_ (
    .A(_232_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_2 _460_ (
    .A(_232_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _461_ (
    .A(_232_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _462_ (
    .A(_228_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__inv_2 _463_ (
    .A(_228_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__inv_2 _464_ (
    .A(_228_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__inv_2 _465_ (
    .A(_228_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_2 _466_ (
    .A(_228_),
    .Y(_047_)
  );
  FI_DFF_DFSTP_FAULTY _467_ (
    .CLK(clock),
    .D(_233_),
    .SET_B(_003_),
    .fault_en(fault_en[0]),
    .Q(\stato[0] )
  );
FI_DFF_DFRTP_FAULTY _468_ (
  .CLK(clock),
  .D(\stato[6] ),
  .RESET_B(_004_),
  .fault_en(fault_en[1]),
  .Q(\stato[1] )
);
FI_DFF_DFRTP_FAULTY _469_ (
  .CLK(clock),
  .D(_000_),
  .RESET_B(_005_),
  .fault_en(fault_en[2]),
  .Q(\stato[2] )
);
FI_DFF_DFRTP_FAULTY _470_ (
  .CLK(clock),
  .D(_001_),
  .RESET_B(_006_),
  .fault_en(fault_en[3]),
  .Q(\stato[3] )
);
FI_DFF_DFRTP_FAULTY _471_ (
  .CLK(clock),
  .D(_002_),
  .RESET_B(_007_),
  .fault_en(fault_en[4]),
  .Q(\stato[4] )
);
FI_DFF_DFRTP_FAULTY _472_ (
  .CLK(clock),
  .D(\stato[1] ),
  .RESET_B(_008_),
  .fault_en(fault_en[5]),
  .Q(\stato[5] )
);
FI_DFF_DFRTP_FAULTY _473_ (
  .CLK(clock),
  .D(\stato[2] ),
  .RESET_B(_009_),
  .fault_en(fault_en[6]),
  .Q(\stato[6] )
);
FI_DFF_DFRTP_FAULTY _474_ (
  .CLK(clock),
  .D(_048_),
  .RESET_B(_010_),
  .fault_en(fault_en[7]),
  .Q(\mar[0] )
);
FI_DFF_DFRTP_FAULTY _475_ (
  .CLK(clock),
  .D(_049_),
  .RESET_B(_011_),
  .fault_en(fault_en[8]),
  .Q(\mar[1] )
);
FI_DFF_DFRTP_FAULTY _476_ (
  .CLK(clock),
  .D(_050_),
  .RESET_B(_012_),
  .fault_en(fault_en[9]),
  .Q(\mar[2] )
);
FI_DFF_DFRTP_FAULTY _477_ (
  .CLK(clock),
  .D(_051_),
  .RESET_B(_013_),
  .fault_en(fault_en[10]),
  .Q(\mar[3] )
);
FI_DFF_DFRTP_FAULTY _478_ (
  .CLK(clock),
  .D(_052_),
  .RESET_B(_014_),
  .fault_en(fault_en[11]),
  .Q(punti_retta[0])
);
FI_DFF_DFRTP_FAULTY _479_ (
  .CLK(clock),
  .D(_053_),
  .RESET_B(_015_),
  .fault_en(fault_en[12]),
  .Q(punti_retta[1])
);
FI_DFF_DFRTP_FAULTY _480_ (
  .CLK(clock),
  .D(_054_),
  .RESET_B(_016_),
  .fault_en(fault_en[13]),
  .Q(punti_retta[2])
);
FI_DFF_DFRTP_FAULTY _481_ (
  .CLK(clock),
  .D(_055_),
  .RESET_B(_017_),
  .fault_en(fault_en[14]),
  .Q(punti_retta[3])
);
FI_DFF_DFRTP_FAULTY _482_ (
  .CLK(clock),
  .D(_056_),
  .RESET_B(_018_),
  .fault_en(fault_en[15]),
  .Q(punti_retta[4])
);
FI_DFF_DFRTP_FAULTY _483_ (
  .CLK(clock),
  .D(_057_),
  .RESET_B(_019_),
  .fault_en(fault_en[16]),
  .Q(punti_retta[5])
);
FI_DFF_DFRTP_FAULTY _484_ (
  .CLK(clock),
  .D(_058_),
  .RESET_B(_020_),
  .fault_en(fault_en[17]),
  .Q(punti_retta[6])
);
FI_DFF_DFRTP_FAULTY _485_ (
  .CLK(clock),
  .D(_059_),
  .RESET_B(_021_),
  .fault_en(fault_en[18]),
  .Q(punti_retta[7])
);
FI_DFF_DFRTP_FAULTY _486_ (
  .CLK(clock),
  .D(_060_),
  .RESET_B(_022_),
  .fault_en(fault_en[19]),
  .Q(\cont[0] )
);
FI_DFF_DFRTP_FAULTY _487_ (
  .CLK(clock),
  .D(_061_),
  .RESET_B(_023_),
  .fault_en(fault_en[20]),
  .Q(\cont[1] )
);
FI_DFF_DFRTP_FAULTY _488_ (
  .CLK(clock),
  .D(_062_),
  .RESET_B(_024_),
  .fault_en(fault_en[21]),
  .Q(\cont[2] )
);
FI_DFF_DFRTP_FAULTY _489_ (
  .CLK(clock),
  .D(_063_),
  .RESET_B(_025_),
  .fault_en(fault_en[22]),
  .Q(\cont[3] )
);
FI_DFF_DFRTP_FAULTY _490_ (
  .CLK(clock),
  .D(_064_),
  .RESET_B(_026_),
  .fault_en(fault_en[23]),
  .Q(\cont[4] )
);
FI_DFF_DFRTP_FAULTY _491_ (
  .CLK(clock),
  .D(_065_),
  .RESET_B(_027_),
  .fault_en(fault_en[24]),
  .Q(\cont[5] )
);
FI_DFF_DFRTP_FAULTY _492_ (
  .CLK(clock),
  .D(_066_),
  .RESET_B(_028_),
  .fault_en(fault_en[25]),
  .Q(\cont[6] )
);
FI_DFF_DFRTP_FAULTY _493_ (
  .CLK(clock),
  .D(_067_),
  .RESET_B(_029_),
  .fault_en(fault_en[26]),
  .Q(\cont[7] )
);
FI_DFF_DFRTP_FAULTY _494_ (
  .CLK(clock),
  .D(_068_),
  .RESET_B(_030_),
  .fault_en(fault_en[27]),
  .Q(\x[0] )
);
FI_DFF_DFRTP_FAULTY _495_ (
  .CLK(clock),
  .D(_069_),
  .RESET_B(_031_),
  .fault_en(fault_en[28]),
  .Q(\x[1] )
);
FI_DFF_DFRTP_FAULTY _496_ (
  .CLK(clock),
  .D(_070_),
  .RESET_B(_032_),
  .fault_en(fault_en[29]),
  .Q(\x[2] )
);
FI_DFF_DFRTP_FAULTY _497_ (
  .CLK(clock),
  .D(_071_),
  .RESET_B(_033_),
  .fault_en(fault_en[30]),
  .Q(\x[3] )
);
FI_DFF_DFRTP_FAULTY _498_ (
  .CLK(clock),
  .D(_072_),
  .RESET_B(_034_),
  .fault_en(fault_en[31]),
  .Q(\x[4] )
);
FI_DFF_DFRTP_FAULTY _499_ (
  .CLK(clock),
  .D(_073_),
  .RESET_B(_035_),
  .fault_en(fault_en[32]),
  .Q(\x[5] )
);
FI_DFF_DFRTP_FAULTY _500_ (
  .CLK(clock),
  .D(_074_),
  .RESET_B(_036_),
  .fault_en(fault_en[33]),
  .Q(\x[6] )
);
FI_DFF_DFRTP_FAULTY _501_ (
  .CLK(clock),
  .D(_075_),
  .RESET_B(_037_),
  .fault_en(fault_en[34]),
  .Q(\x[7] )
);
FI_DFF_DFRTP_FAULTY _502_ (
  .CLK(clock),
  .D(_076_),
  .RESET_B(_038_),
  .fault_en(fault_en[35]),
  .Q(\y[0] )
);
FI_DFF_DFRTP_FAULTY _503_ (
  .CLK(clock),
  .D(_077_),
  .RESET_B(_039_),
  .fault_en(fault_en[36]),
  .Q(\y[1] )
);
FI_DFF_DFRTP_FAULTY _504_ (
  .CLK(clock),
  .D(_078_),
  .RESET_B(_040_),
  .fault_en(fault_en[37]),
  .Q(\y[2] )
);
FI_DFF_DFRTP_FAULTY _505_ (
  .CLK(clock),
  .D(_079_),
  .RESET_B(_041_),
  .fault_en(fault_en[38]),
  .Q(\y[3] )
);
FI_DFF_DFRTP_FAULTY _506_ (
  .CLK(clock),
  .D(_080_),
  .RESET_B(_042_),
  .fault_en(fault_en[39]),
  .Q(\t[1] )
);
FI_DFF_DFRTP_FAULTY _507_ (
  .CLK(clock),
  .D(_081_),
  .RESET_B(_043_),
  .fault_en(fault_en[40]),
  .Q(\t[2] )
);
FI_DFF_DFRTP_FAULTY _508_ (
  .CLK(clock),
  .D(_082_),
  .RESET_B(_044_),
  .fault_en(fault_en[41]),
  .Q(\t[3] )
);
FI_DFF_DFRTP_FAULTY _509_ (
  .CLK(clock),
  .D(_083_),
  .RESET_B(_045_),
  .fault_en(fault_en[42]),
  .Q(\t[4] )
);
FI_DFF_DFRTP_FAULTY _510_ (
  .CLK(clock),
  .D(_084_),
  .RESET_B(_046_),
  .fault_en(fault_en[43]),
  .Q(\t[5] )
);
FI_DFF_DFRTP_FAULTY _511_ (
  .CLK(clock),
  .D(_085_),
  .RESET_B(_047_),
  .fault_en(fault_en[44]),
  .Q(\t[6] )
);
sky130_fd_sc_hd__conb_1 _512_ (
    .LO(_233_)
  );
endmodule
