/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b06(cc_mux, eql, uscite, clock, enable_count, ackout, reset, cont_eql);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  output ackout;
  wire ackout;
  output [2:1] cc_mux;
  wire [2:1] cc_mux;
  input clock;
  wire clock;
  input cont_eql;
  wire cont_eql;
  output enable_count;
  wire enable_count;
  input eql;
  wire eql;
  input reset;
  wire reset;
  wire \state[0] ;
  wire \state[1] ;
  wire \state[2] ;
  wire \state[3] ;
  wire \state[4] ;
  wire \state[5] ;
  wire \state[6] ;
  output [2:1] uscite;
  wire [2:1] uscite;
  sky130_fd_sc_hd__mux2_2 _39_ (
    .A0(\state[2] ),
    .A1(\state[6] ),
    .S(eql),
    .X(_22_)
  );
  sky130_fd_sc_hd__buf_1 _40_ (
    .A(_22_),
    .X(_21_)
  );
  sky130_fd_sc_hd__or3_2 _41_ (
    .A(\state[6] ),
    .B(\state[0] ),
    .C(\state[3] ),
    .X(_23_)
  );
  sky130_fd_sc_hd__buf_1 _42_ (
    .A(_23_),
    .X(_24_)
  );
  sky130_fd_sc_hd__or4_2 _43_ (
    .A(\state[2] ),
    .B(\state[4] ),
    .C(\state[5] ),
    .D(\state[1] ),
    .X(_25_)
  );
  sky130_fd_sc_hd__buf_1 _44_ (
    .A(_25_),
    .X(_26_)
  );
  sky130_fd_sc_hd__inv_2 _45_ (
    .A(eql),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a21oi_2 _46_ (
    .A1(_27_),
    .A2(_26_),
    .B1(_24_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a211o_2 _47_ (
    .A1(eql),
    .A2(\state[3] ),
    .B1(\state[1] ),
    .C1(\state[4] ),
    .X(_29_)
  );
  sky130_fd_sc_hd__o32a_2 _48_ (
    .A1(cc_mux[2]),
    .A2(_24_),
    .A3(_26_),
    .B1(_28_),
    .B2(_29_),
    .X(_20_)
  );
  sky130_fd_sc_hd__o22a_2 _49_ (
    .A1(\state[4] ),
    .A2(\state[1] ),
    .B1(\state[3] ),
    .B2(eql),
    .X(_30_)
  );
  sky130_fd_sc_hd__or3b_2 _50_ (
    .A(\state[6] ),
    .B(\state[0] ),
    .C_N(_29_),
    .X(_31_)
  );
  sky130_fd_sc_hd__o32a_2 _51_ (
    .A1(cc_mux[1]),
    .A2(_24_),
    .A3(_26_),
    .B1(_30_),
    .B2(_31_),
    .X(_19_)
  );
  sky130_fd_sc_hd__mux2_2 _52_ (
    .A0(\state[1] ),
    .A1(\state[3] ),
    .S(eql),
    .X(_32_)
  );
  sky130_fd_sc_hd__buf_1 _53_ (
    .A(_32_),
    .X(_37_)
  );
  sky130_fd_sc_hd__nor2_2 _54_ (
    .A(_24_),
    .B(_26_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__a21o_2 _55_ (
    .A1(uscite[2]),
    .A2(_33_),
    .B1(_37_),
    .X(_18_)
  );
  sky130_fd_sc_hd__inv_2 _56_ (
    .A(uscite[1]),
    .Y(_34_)
  );
  sky130_fd_sc_hd__o21ai_2 _57_ (
    .A1(_34_),
    .A2(_26_),
    .B1(_28_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o22a_2 _58_ (
    .A1(_27_),
    .A2(\state[0] ),
    .B1(_24_),
    .B2(\state[5] ),
    .X(_04_)
  );
  sky130_fd_sc_hd__a21bo_2 _59_ (
    .A1(\state[2] ),
    .A2(_27_),
    .B1_N(cont_eql),
    .X(_00_)
  );
  sky130_fd_sc_hd__o21a_2 _60_ (
    .A1(\state[5] ),
    .A2(\state[1] ),
    .B1(eql),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_2 _61_ (
    .A(_27_),
    .B(\state[4] ),
    .X(_35_)
  );
  sky130_fd_sc_hd__buf_1 _62_ (
    .A(_35_),
    .X(_03_)
  );
  sky130_fd_sc_hd__o21a_2 _63_ (
    .A1(\state[2] ),
    .A2(\state[4] ),
    .B1(eql),
    .X(_02_)
  );
  sky130_fd_sc_hd__buf_1 _64_ (
    .A(reset),
    .X(_36_)
  );
  sky130_fd_sc_hd__inv_2 _65_ (
    .A(_36_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__inv_2 _66_ (
    .A(_36_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__inv_2 _67_ (
    .A(_36_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__inv_2 _68_ (
    .A(_36_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__inv_2 _69_ (
    .A(_36_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__inv_2 _70_ (
    .A(_36_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__inv_2 _71_ (
    .A(_36_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__inv_2 _72_ (
    .A(_36_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__inv_2 _73_ (
    .A(_36_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__inv_2 _74_ (
    .A(_36_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__inv_2 _75_ (
    .A(reset),
    .Y(_15_)
  );
  sky130_fd_sc_hd__inv_2 _76_ (
    .A(reset),
    .Y(_16_)
  );
  sky130_fd_sc_hd__dfstp_2 _77_ (
    .CLK(clock),
    .D(_38_),
    .Q(\state[0] ),
    .SET_B(_05_)
  );
  sky130_fd_sc_hd__dfrtp_2 _78_ (
    .CLK(clock),
    .D(_01_),
    .Q(\state[1] ),
    .RESET_B(_06_)
  );
  sky130_fd_sc_hd__dfrtp_2 _79_ (
    .CLK(clock),
    .D(_02_),
    .Q(\state[2] ),
    .RESET_B(_07_)
  );
  sky130_fd_sc_hd__dfrtp_2 _80_ (
    .CLK(clock),
    .D(_37_),
    .Q(\state[3] ),
    .RESET_B(_08_)
  );
  sky130_fd_sc_hd__dfrtp_2 _81_ (
    .CLK(clock),
    .D(_04_),
    .Q(\state[4] ),
    .RESET_B(_09_)
  );
  sky130_fd_sc_hd__dfrtp_2 _82_ (
    .CLK(clock),
    .D(_03_),
    .Q(\state[5] ),
    .RESET_B(_10_)
  );
  sky130_fd_sc_hd__dfrtp_2 _83_ (
    .CLK(clock),
    .D(_17_),
    .Q(uscite[1]),
    .RESET_B(_11_)
  );
  sky130_fd_sc_hd__dfrtp_2 _84_ (
    .CLK(clock),
    .D(_18_),
    .Q(uscite[2]),
    .RESET_B(_12_)
  );
  sky130_fd_sc_hd__dfrtp_2 _85_ (
    .CLK(clock),
    .D(_19_),
    .Q(cc_mux[1]),
    .RESET_B(_13_)
  );
  sky130_fd_sc_hd__dfrtp_2 _86_ (
    .CLK(clock),
    .D(_20_),
    .Q(cc_mux[2]),
    .RESET_B(_14_)
  );
  sky130_fd_sc_hd__dfrtp_2 _87_ (
    .CLK(clock),
    .D(_00_),
    .Q(ackout),
    .RESET_B(_15_)
  );
  sky130_fd_sc_hd__dfrtp_2 _88_ (
    .CLK(clock),
    .D(_21_),
    .Q(\state[6] ),
    .RESET_B(_16_)
  );
  sky130_fd_sc_hd__conb_1 _89_ (
    .LO(_38_)
  );
  sky130_fd_sc_hd__buf_2 _90_ (
    .A(ackout),
    .X(enable_count)
  );
endmodule

