/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b09(reset, clock, x, y);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  input clock;
  wire clock;
  wire \d_in[0] ;
  wire \d_in[1] ;
  wire \d_in[2] ;
  wire \d_in[3] ;
  wire \d_in[4] ;
  wire \d_in[5] ;
  wire \d_in[6] ;
  wire \d_in[7] ;
  wire \d_in[8] ;
  wire \d_out[0] ;
  wire \d_out[1] ;
  wire \d_out[2] ;
  wire \d_out[3] ;
  wire \d_out[4] ;
  wire \d_out[5] ;
  wire \d_out[6] ;
  wire \d_out[7] ;
  wire \old[0] ;
  wire \old[1] ;
  wire \old[2] ;
  wire \old[3] ;
  wire \old[4] ;
  wire \old[5] ;
  wire \old[6] ;
  wire \old[7] ;
  input reset;
  wire reset;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  wire \stato[3] ;
  input x;
  wire x;
  output y;
  wire y;
  sky130_fd_sc_hd__or2_2 _115_ (
    .A(\stato[2] ),
    .B(\stato[3] ),
    .X(_106_)
  );
  sky130_fd_sc_hd__buf_1 _116_ (
    .A(_106_),
    .X(_107_)
  );
  sky130_fd_sc_hd__and2_2 _117_ (
    .A(\d_in[8] ),
    .B(_107_),
    .X(_108_)
  );
  sky130_fd_sc_hd__xor2_2 _118_ (
    .A(\d_in[1] ),
    .B(\old[0] ),
    .X(_109_)
  );
  sky130_fd_sc_hd__xor2_2 _119_ (
    .A(\d_in[3] ),
    .B(\old[2] ),
    .X(_110_)
  );
  sky130_fd_sc_hd__xor2_2 _120_ (
    .A(\d_in[6] ),
    .B(\old[5] ),
    .X(_111_)
  );
  sky130_fd_sc_hd__xor2_2 _121_ (
    .A(\d_in[7] ),
    .B(\old[6] ),
    .X(_112_)
  );
  sky130_fd_sc_hd__or4_2 _122_ (
    .A(_109_),
    .B(_110_),
    .C(_111_),
    .D(_112_),
    .X(_113_)
  );
  sky130_fd_sc_hd__xor2_2 _123_ (
    .A(\d_in[2] ),
    .B(\old[1] ),
    .X(_059_)
  );
  sky130_fd_sc_hd__xor2_2 _124_ (
    .A(\d_in[4] ),
    .B(\old[3] ),
    .X(_060_)
  );
  sky130_fd_sc_hd__xor2_2 _125_ (
    .A(\d_in[8] ),
    .B(\old[7] ),
    .X(_061_)
  );
  sky130_fd_sc_hd__xor2_2 _126_ (
    .A(\d_in[5] ),
    .B(\old[4] ),
    .X(_062_)
  );
  sky130_fd_sc_hd__or4_2 _127_ (
    .A(_059_),
    .B(_060_),
    .C(_061_),
    .D(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__o21ai_2 _128_ (
    .A1(_113_),
    .A2(_063_),
    .B1(\d_in[0] ),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor3_2 _129_ (
    .A(\stato[1] ),
    .B(\stato[0] ),
    .C(_106_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__inv_2 _130_ (
    .A(\d_in[0] ),
    .Y(_066_)
  );
  sky130_fd_sc_hd__and2_2 _131_ (
    .A(_066_),
    .B(\stato[2] ),
    .X(_067_)
  );
  sky130_fd_sc_hd__or2_2 _132_ (
    .A(_065_),
    .B(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hd__a221o_2 _133_ (
    .A1(\d_in[0] ),
    .A2(\stato[1] ),
    .B1(\stato[3] ),
    .B2(_064_),
    .C1(_068_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_2 _134_ (
    .A0(_108_),
    .A1(\d_out[7] ),
    .S(_069_),
    .X(_070_)
  );
  sky130_fd_sc_hd__buf_1 _135_ (
    .A(_070_),
    .X(_058_)
  );
  sky130_fd_sc_hd__buf_1 _136_ (
    .A(\stato[1] ),
    .X(_071_)
  );
  sky130_fd_sc_hd__a22o_2 _137_ (
    .A1(\d_out[7] ),
    .A2(_071_),
    .B1(_107_),
    .B2(\d_in[7] ),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_2 _138_ (
    .A0(_072_),
    .A1(\d_out[6] ),
    .S(_069_),
    .X(_073_)
  );
  sky130_fd_sc_hd__buf_1 _139_ (
    .A(_073_),
    .X(_057_)
  );
  sky130_fd_sc_hd__a22o_2 _140_ (
    .A1(\d_out[6] ),
    .A2(_071_),
    .B1(_107_),
    .B2(\d_in[6] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_2 _141_ (
    .A0(_074_),
    .A1(\d_out[5] ),
    .S(_069_),
    .X(_075_)
  );
  sky130_fd_sc_hd__buf_1 _142_ (
    .A(_075_),
    .X(_056_)
  );
  sky130_fd_sc_hd__a22o_2 _143_ (
    .A1(\d_out[5] ),
    .A2(_071_),
    .B1(_107_),
    .B2(\d_in[5] ),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_2 _144_ (
    .A0(_076_),
    .A1(\d_out[4] ),
    .S(_069_),
    .X(_077_)
  );
  sky130_fd_sc_hd__buf_1 _145_ (
    .A(_077_),
    .X(_055_)
  );
  sky130_fd_sc_hd__a22o_2 _146_ (
    .A1(\d_out[4] ),
    .A2(_071_),
    .B1(_107_),
    .B2(\d_in[4] ),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_2 _147_ (
    .A0(_078_),
    .A1(\d_out[3] ),
    .S(_069_),
    .X(_079_)
  );
  sky130_fd_sc_hd__buf_1 _148_ (
    .A(_079_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a22o_2 _149_ (
    .A1(\d_out[3] ),
    .A2(_071_),
    .B1(_107_),
    .B2(\d_in[3] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_2 _150_ (
    .A0(_080_),
    .A1(\d_out[2] ),
    .S(_069_),
    .X(_081_)
  );
  sky130_fd_sc_hd__buf_1 _151_ (
    .A(_081_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a22o_2 _152_ (
    .A1(\d_out[2] ),
    .A2(\stato[1] ),
    .B1(_107_),
    .B2(\d_in[2] ),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_2 _153_ (
    .A0(_082_),
    .A1(\d_out[1] ),
    .S(_069_),
    .X(_083_)
  );
  sky130_fd_sc_hd__buf_1 _154_ (
    .A(_083_),
    .X(_052_)
  );
  sky130_fd_sc_hd__a22o_2 _155_ (
    .A1(\d_out[1] ),
    .A2(\stato[1] ),
    .B1(_107_),
    .B2(\d_in[1] ),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_2 _156_ (
    .A0(_084_),
    .A1(\d_out[0] ),
    .S(_069_),
    .X(_085_)
  );
  sky130_fd_sc_hd__buf_1 _157_ (
    .A(_085_),
    .X(_051_)
  );
  sky130_fd_sc_hd__buf_1 _158_ (
    .A(_065_),
    .X(_086_)
  );
  sky130_fd_sc_hd__inv_2 _159_ (
    .A(\stato[3] ),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2_2 _160_ (
    .A(_087_),
    .B(_064_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_2 _161_ (
    .A(\d_in[0] ),
    .B(_087_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__and2_2 _162_ (
    .A(\d_in[0] ),
    .B(\stato[2] ),
    .X(_090_)
  );
  sky130_fd_sc_hd__o32a_2 _163_ (
    .A1(_071_),
    .A2(\stato[2] ),
    .A3(_089_),
    .B1(_090_),
    .B2(x),
    .X(_091_)
  );
  sky130_fd_sc_hd__or4_2 _164_ (
    .A(\d_in[8] ),
    .B(_071_),
    .C(\stato[0] ),
    .D(_107_),
    .X(_092_)
  );
  sky130_fd_sc_hd__o31a_2 _165_ (
    .A1(_086_),
    .A2(_088_),
    .A3(_091_),
    .B1(_092_),
    .X(_050_)
  );
  sky130_fd_sc_hd__or3_2 _166_ (
    .A(\stato[1] ),
    .B(_067_),
    .C(_089_),
    .X(_093_)
  );
  sky130_fd_sc_hd__buf_1 _167_ (
    .A(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__a22o_2 _168_ (
    .A1(\d_in[7] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[8] ),
    .X(_049_)
  );
  sky130_fd_sc_hd__a22o_2 _169_ (
    .A1(\d_in[6] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[7] ),
    .X(_048_)
  );
  sky130_fd_sc_hd__a22o_2 _170_ (
    .A1(\d_in[5] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[6] ),
    .X(_047_)
  );
  sky130_fd_sc_hd__a22o_2 _171_ (
    .A1(\d_in[4] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[5] ),
    .X(_046_)
  );
  sky130_fd_sc_hd__a22o_2 _172_ (
    .A1(\d_in[3] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[4] ),
    .X(_045_)
  );
  sky130_fd_sc_hd__a22o_2 _173_ (
    .A1(\d_in[2] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[3] ),
    .X(_044_)
  );
  sky130_fd_sc_hd__a22o_2 _174_ (
    .A1(\d_in[1] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[2] ),
    .X(_043_)
  );
  sky130_fd_sc_hd__a22o_2 _175_ (
    .A1(\d_in[0] ),
    .A2(_086_),
    .B1(_094_),
    .B2(\d_in[1] ),
    .X(_042_)
  );
  sky130_fd_sc_hd__inv_2 _176_ (
    .A(y),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a311o_2 _177_ (
    .A1(\d_out[0] ),
    .A2(_066_),
    .A3(_071_),
    .B1(\stato[2] ),
    .C1(_086_),
    .X(_096_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _178_ (
    .A1_N(_095_),
    .A2_N(_068_),
    .B1(_088_),
    .B2(_096_),
    .X(_041_)
  );
  sky130_fd_sc_hd__nor2_2 _179_ (
    .A(\stato[0] ),
    .B(_106_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__or3_2 _180_ (
    .A(_097_),
    .B(_067_),
    .C(_089_),
    .X(_098_)
  );
  sky130_fd_sc_hd__buf_1 _181_ (
    .A(_098_),
    .X(_099_)
  );
  sky130_fd_sc_hd__and2_2 _182_ (
    .A(\d_in[0] ),
    .B(_107_),
    .X(_100_)
  );
  sky130_fd_sc_hd__buf_1 _183_ (
    .A(_100_),
    .X(_101_)
  );
  sky130_fd_sc_hd__a22o_2 _184_ (
    .A1(\old[7] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[8] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__a22o_2 _185_ (
    .A1(\old[6] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[7] ),
    .X(_039_)
  );
  sky130_fd_sc_hd__a22o_2 _186_ (
    .A1(\old[5] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[6] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__a22o_2 _187_ (
    .A1(\old[4] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[5] ),
    .X(_037_)
  );
  sky130_fd_sc_hd__a22o_2 _188_ (
    .A1(\old[3] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[4] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__a22o_2 _189_ (
    .A1(\old[2] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[3] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__a22o_2 _190_ (
    .A1(\old[1] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[2] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__a22o_2 _191_ (
    .A1(\old[0] ),
    .A2(_099_),
    .B1(_101_),
    .B2(\d_in[1] ),
    .X(_033_)
  );
  sky130_fd_sc_hd__a211o_2 _192_ (
    .A1(_066_),
    .A2(_071_),
    .B1(_088_),
    .C1(_090_),
    .X(_000_)
  );
  sky130_fd_sc_hd__a22o_2 _193_ (
    .A1(\d_in[0] ),
    .A2(_071_),
    .B1(\stato[3] ),
    .B2(_064_),
    .X(_002_)
  );
  sky130_fd_sc_hd__or2_2 _194_ (
    .A(\stato[0] ),
    .B(_067_),
    .X(_102_)
  );
  sky130_fd_sc_hd__buf_1 _195_ (
    .A(_102_),
    .X(_001_)
  );
  sky130_fd_sc_hd__buf_1 _196_ (
    .A(reset),
    .X(_103_)
  );
  sky130_fd_sc_hd__inv_2 _197_ (
    .A(_103_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _198_ (
    .A(_103_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _199_ (
    .A(_103_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _200_ (
    .A(_103_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _201_ (
    .A(_103_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__inv_2 _202_ (
    .A(_103_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _203_ (
    .A(_103_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _204_ (
    .A(_103_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _205_ (
    .A(_103_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _206_ (
    .A(_103_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__buf_1 _207_ (
    .A(reset),
    .X(_104_)
  );
  sky130_fd_sc_hd__inv_2 _208_ (
    .A(_104_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _209_ (
    .A(_104_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _210_ (
    .A(_104_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _211_ (
    .A(_104_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _212_ (
    .A(_104_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _213_ (
    .A(_104_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _214_ (
    .A(_104_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _215_ (
    .A(_104_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _216_ (
    .A(_104_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _217_ (
    .A(_104_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__buf_1 _218_ (
    .A(reset),
    .X(_105_)
  );
  sky130_fd_sc_hd__inv_2 _219_ (
    .A(_105_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _220_ (
    .A(_105_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _221_ (
    .A(_105_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _222_ (
    .A(_105_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _223_ (
    .A(_105_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _224_ (
    .A(_105_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _225_ (
    .A(_105_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _226_ (
    .A(_105_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _227_ (
    .A(_105_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__inv_2 _228_ (
    .A(_105_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__dfrtp_2 _229_ (
    .CLK(clock),
    .D(_033_),
    .Q(\old[0] ),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_2 _230_ (
    .CLK(clock),
    .D(_034_),
    .Q(\old[1] ),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_2 _231_ (
    .CLK(clock),
    .D(_035_),
    .Q(\old[2] ),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_2 _232_ (
    .CLK(clock),
    .D(_036_),
    .Q(\old[3] ),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_2 _233_ (
    .CLK(clock),
    .D(_037_),
    .Q(\old[4] ),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_2 _234_ (
    .CLK(clock),
    .D(_038_),
    .Q(\old[5] ),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_2 _235_ (
    .CLK(clock),
    .D(_039_),
    .Q(\old[6] ),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_2 _236_ (
    .CLK(clock),
    .D(_040_),
    .Q(\old[7] ),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfstp_2 _237_ (
    .CLK(clock),
    .D(_114_),
    .Q(\stato[0] ),
    .SET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_2 _238_ (
    .CLK(clock),
    .D(_000_),
    .Q(\stato[1] ),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_2 _239_ (
    .CLK(clock),
    .D(_001_),
    .Q(\stato[2] ),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_2 _240_ (
    .CLK(clock),
    .D(_002_),
    .Q(\stato[3] ),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_2 _241_ (
    .CLK(clock),
    .D(_041_),
    .Q(y),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_2 _242_ (
    .CLK(clock),
    .D(_042_),
    .Q(\d_in[0] ),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_2 _243_ (
    .CLK(clock),
    .D(_043_),
    .Q(\d_in[1] ),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_2 _244_ (
    .CLK(clock),
    .D(_044_),
    .Q(\d_in[2] ),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_2 _245_ (
    .CLK(clock),
    .D(_045_),
    .Q(\d_in[3] ),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_2 _246_ (
    .CLK(clock),
    .D(_046_),
    .Q(\d_in[4] ),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_2 _247_ (
    .CLK(clock),
    .D(_047_),
    .Q(\d_in[5] ),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_2 _248_ (
    .CLK(clock),
    .D(_048_),
    .Q(\d_in[6] ),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_2 _249_ (
    .CLK(clock),
    .D(_049_),
    .Q(\d_in[7] ),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_2 _250_ (
    .CLK(clock),
    .D(_050_),
    .Q(\d_in[8] ),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_2 _251_ (
    .CLK(clock),
    .D(_051_),
    .Q(\d_out[0] ),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_2 _252_ (
    .CLK(clock),
    .D(_052_),
    .Q(\d_out[1] ),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_2 _253_ (
    .CLK(clock),
    .D(_053_),
    .Q(\d_out[2] ),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_2 _254_ (
    .CLK(clock),
    .D(_054_),
    .Q(\d_out[3] ),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_2 _255_ (
    .CLK(clock),
    .D(_055_),
    .Q(\d_out[4] ),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_2 _256_ (
    .CLK(clock),
    .D(_056_),
    .Q(\d_out[5] ),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_2 _257_ (
    .CLK(clock),
    .D(_057_),
    .Q(\d_out[6] ),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfrtp_2 _258_ (
    .CLK(clock),
    .D(_058_),
    .Q(\d_out[7] ),
    .RESET_B(_032_)
  );
  sky130_fd_sc_hd__conb_1 _259_ (
    .LO(_114_)
  );
endmodule
