// Auto-generated mapped fault enables:
//   fault_en[0] -> _819_ -> sum_in[0] (RTL)
//   fault_en[1] -> _820_ -> sum_in[1] (RTL)
//   fault_en[2] -> _821_ -> sum_in[2] (RTL)
//   fault_en[3] -> _822_ -> sum_in[3] (RTL)
//   fault_en[4] -> _823_ -> sum_in[4] (RTL)
//   fault_en[5] -> _824_ -> sum_in[5] (RTL)
//   fault_en[6] -> _825_ -> sum_in[6] (RTL)
//   fault_en[7] -> _826_ -> sum_in[31] (RTL)
//   fault_en[8] -> _827_ -> stato[0] (RTL)
//   fault_en[9] -> _828_ -> stato[1] (RTL)
//   fault_en[10] -> _829_ -> stato[2] (GL_ONLY)
//   fault_en[11] -> _830_ -> DATA_OUT[0] (RTL)
//   fault_en[12] -> _831_ -> DATA_OUT[1] (RTL)
//   fault_en[13] -> _832_ -> DATA_OUT[2] (RTL)
//   fault_en[14] -> _833_ -> DATA_OUT[3] (RTL)
//   fault_en[15] -> _834_ -> DATA_OUT[4] (RTL)
//   fault_en[16] -> _835_ -> DATA_OUT[5] (RTL)
//   fault_en[17] -> _836_ -> DATA_OUT[6] (RTL)
//   fault_en[18] -> _837_ -> DATA_OUT[7] (RTL)
//   fault_en[19] -> _838_ -> RMAX[0] (RTL)
//   fault_en[20] -> _839_ -> RMAX[1] (RTL)
//   fault_en[21] -> _840_ -> RMAX[2] (RTL)
//   fault_en[22] -> _841_ -> RMAX[3] (RTL)
//   fault_en[23] -> _842_ -> RMAX[4] (RTL)
//   fault_en[24] -> _843_ -> RMAX[5] (RTL)
//   fault_en[25] -> _844_ -> RMAX[6] (RTL)
//   fault_en[26] -> _845_ -> RMAX[10] (RTL)
//   fault_en[27] -> _846_ -> RMIN[0] (RTL)
//   fault_en[28] -> _847_ -> RMIN[1] (RTL)
//   fault_en[29] -> _848_ -> RMIN[2] (RTL)
//   fault_en[30] -> _849_ -> RMIN[3] (RTL)
//   fault_en[31] -> _850_ -> RMIN[4] (RTL)
//   fault_en[32] -> _851_ -> RMIN[5] (RTL)
//   fault_en[33] -> _852_ -> RMIN[6] (RTL)
//   fault_en[34] -> _853_ -> RMIN[10] (RTL)
//   fault_en[35] -> _854_ -> RLAST[0] (RTL)
//   fault_en[36] -> _855_ -> RLAST[1] (RTL)
//   fault_en[37] -> _856_ -> RLAST[2] (RTL)
//   fault_en[38] -> _857_ -> RLAST[3] (RTL)
//   fault_en[39] -> _858_ -> RLAST[4] (RTL)
//   fault_en[40] -> _859_ -> RLAST[5] (RTL)
//   fault_en[41] -> _860_ -> RLAST[6] (RTL)
//   fault_en[42] -> _861_ -> RLAST[7] (RTL)
//   fault_en[43] -> _862_ -> REG1[0] (RTL)
//   fault_en[44] -> _863_ -> REG1[1] (RTL)
//   fault_en[45] -> _864_ -> REG1[2] (RTL)
//   fault_en[46] -> _865_ -> REG1[3] (RTL)
//   fault_en[47] -> _866_ -> REG1[4] (RTL)
//   fault_en[48] -> _867_ -> REG1[5] (RTL)
//   fault_en[49] -> _868_ -> REG1[6] (RTL)
//   fault_en[50] -> _869_ -> REG1[10] (RTL)
//   fault_en[51] -> _870_ -> REG2[0] (RTL)
//   fault_en[52] -> _871_ -> REG2[1] (RTL)
//   fault_en[53] -> _872_ -> REG2[2] (RTL)
//   fault_en[54] -> _873_ -> REG2[3] (RTL)
//   fault_en[55] -> _874_ -> REG2[4] (RTL)
//   fault_en[56] -> _875_ -> REG2[5] (RTL)
//   fault_en[57] -> _876_ -> REG2[6] (RTL)
//   fault_en[58] -> _877_ -> REG2[10] (RTL)
//   fault_en[59] -> _878_ -> REG3[0] (RTL)
//   fault_en[60] -> _879_ -> REG3[1] (RTL)
//   fault_en[61] -> _880_ -> REG3[2] (RTL)
//   fault_en[62] -> _881_ -> REG3[3] (RTL)
//   fault_en[63] -> _882_ -> REG3[4] (RTL)
//   fault_en[64] -> _883_ -> REG3[5] (RTL)
//   fault_en[65] -> _884_ -> REG3[6] (RTL)
//   fault_en[66] -> _885_ -> REG3[10] (RTL)
//   fault_en[67] -> _886_ -> RES[0] (RTL)
//   fault_en[68] -> _887_ -> AVE[0] (RTL)
//   fault_en[69] -> _888_ -> ENA[0] (RTL)
//   fault_en[70] -> _889_ -> REG4[0] (RTL)
//   fault_en[71] -> _890_ -> REG4[1] (RTL)
//   fault_en[72] -> _891_ -> REG4[2] (RTL)
//   fault_en[73] -> _892_ -> REG4[3] (RTL)
//   fault_en[74] -> _893_ -> REG4[4] (RTL)
//   fault_en[75] -> _894_ -> REG4[5] (RTL)
//   fault_en[76] -> _895_ -> REG4[6] (RTL)
//   fault_en[77] -> _896_ -> REG4[10] (RTL)
//   fault_en[78] -> _897_ -> sum_rm[0] (RTL)
//   fault_en[79] -> _898_ -> sum_rm[1] (RTL)
//   fault_en[80] -> _899_ -> sum_rm[2] (RTL)
//   fault_en[81] -> _900_ -> sum_rm[3] (RTL)
//   fault_en[82] -> _901_ -> sum_rm[4] (RTL)
//   fault_en[83] -> _902_ -> sum_rm[5] (RTL)
//   fault_en[84] -> _903_ -> sum_rm[6] (RTL)
//   fault_en[85] -> _904_ -> sum_rm[31] (RTL)

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b04(RESTART, AVERAGE, ENABLE, DATA_IN, DATA_OUT, RESET, CLOCK, fault_en);
  input [85:0] fault_en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire AVE;
  input AVERAGE;
  wire AVERAGE;
  input CLOCK;
  wire CLOCK;
  input [7:0] DATA_IN;
  wire [7:0] DATA_IN;
  output [7:0] DATA_OUT;
  wire [7:0] DATA_OUT;
  wire ENA;
  input ENABLE;
  wire ENABLE;
  wire \REG1[0] ;
  wire \REG1[10] ;
  wire \REG1[1] ;
  wire \REG1[2] ;
  wire \REG1[3] ;
  wire \REG1[4] ;
  wire \REG1[5] ;
  wire \REG1[6] ;
  wire \REG2[0] ;
  wire \REG2[10] ;
  wire \REG2[1] ;
  wire \REG2[2] ;
  wire \REG2[3] ;
  wire \REG2[4] ;
  wire \REG2[5] ;
  wire \REG2[6] ;
  wire \REG3[0] ;
  wire \REG3[10] ;
  wire \REG3[1] ;
  wire \REG3[2] ;
  wire \REG3[3] ;
  wire \REG3[4] ;
  wire \REG3[5] ;
  wire \REG3[6] ;
  wire \REG4[0] ;
  wire \REG4[10] ;
  wire \REG4[1] ;
  wire \REG4[2] ;
  wire \REG4[3] ;
  wire \REG4[4] ;
  wire \REG4[5] ;
  wire \REG4[6] ;
  wire RES;
  input RESET;
  wire RESET;
  input RESTART;
  wire RESTART;
  wire \RLAST[0] ;
  wire \RLAST[1] ;
  wire \RLAST[2] ;
  wire \RLAST[3] ;
  wire \RLAST[4] ;
  wire \RLAST[5] ;
  wire \RLAST[6] ;
  wire \RLAST[7] ;
  wire \RMAX[0] ;
  wire \RMAX[10] ;
  wire \RMAX[1] ;
  wire \RMAX[2] ;
  wire \RMAX[3] ;
  wire \RMAX[4] ;
  wire \RMAX[5] ;
  wire \RMAX[6] ;
  wire \RMIN[0] ;
  wire \RMIN[10] ;
  wire \RMIN[1] ;
  wire \RMIN[2] ;
  wire \RMIN[3] ;
  wire \RMIN[4] ;
  wire \RMIN[5] ;
  wire \RMIN[6] ;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  wire \sum_in[0] ;
  wire \sum_in[1] ;
  wire \sum_in[2] ;
  wire \sum_in[31] ;
  wire \sum_in[3] ;
  wire \sum_in[4] ;
  wire \sum_in[5] ;
  wire \sum_in[6] ;
  wire \sum_rm[0] ;
  wire \sum_rm[1] ;
  wire \sum_rm[2] ;
  wire \sum_rm[31] ;
  wire \sum_rm[3] ;
  wire \sum_rm[4] ;
  wire \sum_rm[5] ;
  wire \sum_rm[6] ;
  sky130_fd_sc_hd__inv_2 _410_ (
    .A(\stato[1] ),
    .Y(_167_)
  );
  sky130_fd_sc_hd__buf_1 _411_ (
    .A(_167_),
    .X(_168_)
  );
  sky130_fd_sc_hd__or2_2 _412_ (
    .A(\RMIN[10] ),
    .B(\RMAX[10] ),
    .X(_169_)
  );
  sky130_fd_sc_hd__nand2_2 _413_ (
    .A(\RMIN[10] ),
    .B(\RMAX[10] ),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand2_2 _414_ (
    .A(_169_),
    .B(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__and2_2 _415_ (
    .A(\RMIN[6] ),
    .B(\RMAX[6] ),
    .X(_172_)
  );
  sky130_fd_sc_hd__nor2_2 _416_ (
    .A(\RMIN[6] ),
    .B(\RMAX[6] ),
    .Y(_173_)
  );
  sky130_fd_sc_hd__nor2_2 _417_ (
    .A(_172_),
    .B(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__or2_2 _418_ (
    .A(\RMIN[5] ),
    .B(\RMAX[5] ),
    .X(_175_)
  );
  sky130_fd_sc_hd__or2_2 _419_ (
    .A(\RMIN[3] ),
    .B(\RMAX[3] ),
    .X(_176_)
  );
  sky130_fd_sc_hd__or2_2 _420_ (
    .A(\RMIN[1] ),
    .B(\RMAX[1] ),
    .X(_177_)
  );
  sky130_fd_sc_hd__and2_2 _421_ (
    .A(\RMIN[1] ),
    .B(\RMAX[1] ),
    .X(_178_)
  );
  sky130_fd_sc_hd__a31o_2 _422_ (
    .A1(\RMIN[0] ),
    .A2(\RMAX[0] ),
    .A3(_177_),
    .B1(_178_),
    .X(_179_)
  );
  sky130_fd_sc_hd__or2_2 _423_ (
    .A(\RMIN[2] ),
    .B(\RMAX[2] ),
    .X(_180_)
  );
  sky130_fd_sc_hd__nand2_2 _424_ (
    .A(\RMIN[2] ),
    .B(\RMAX[2] ),
    .Y(_181_)
  );
  sky130_fd_sc_hd__a21bo_2 _425_ (
    .A1(_179_),
    .A2(_180_),
    .B1_N(_181_),
    .X(_182_)
  );
  sky130_fd_sc_hd__nand2_2 _426_ (
    .A(\RMIN[3] ),
    .B(\RMAX[3] ),
    .Y(_183_)
  );
  sky130_fd_sc_hd__a21bo_2 _427_ (
    .A1(_176_),
    .A2(_182_),
    .B1_N(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd__or2_2 _428_ (
    .A(\RMIN[4] ),
    .B(\RMAX[4] ),
    .X(_185_)
  );
  sky130_fd_sc_hd__nand2_2 _429_ (
    .A(\RMIN[4] ),
    .B(\RMAX[4] ),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a21bo_2 _430_ (
    .A1(_184_),
    .A2(_185_),
    .B1_N(_186_),
    .X(_187_)
  );
  sky130_fd_sc_hd__nand2_2 _431_ (
    .A(\RMIN[5] ),
    .B(\RMAX[5] ),
    .Y(_188_)
  );
  sky130_fd_sc_hd__a21bo_2 _432_ (
    .A1(_175_),
    .A2(_187_),
    .B1_N(_188_),
    .X(_189_)
  );
  sky130_fd_sc_hd__a21oi_2 _433_ (
    .A1(_174_),
    .A2(_189_),
    .B1(_172_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__buf_1 _434_ (
    .A(\stato[1] ),
    .X(_191_)
  );
  sky130_fd_sc_hd__buf_1 _435_ (
    .A(_191_),
    .X(_192_)
  );
  sky130_fd_sc_hd__o211a_2 _436_ (
    .A1(_171_),
    .A2(_190_),
    .B1(_192_),
    .C1(_169_),
    .X(_193_)
  );
  sky130_fd_sc_hd__a21o_2 _437_ (
    .A1(\sum_rm[31] ),
    .A2(_168_),
    .B1(_193_),
    .X(_166_)
  );
  sky130_fd_sc_hd__buf_1 _438_ (
    .A(_167_),
    .X(_194_)
  );
  sky130_fd_sc_hd__buf_1 _439_ (
    .A(_191_),
    .X(_195_)
  );
  sky130_fd_sc_hd__xnor2_2 _440_ (
    .A(_174_),
    .B(_189_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor2_2 _441_ (
    .A(_195_),
    .B(\sum_rm[6] ),
    .Y(_197_)
  );
  sky130_fd_sc_hd__a21oi_2 _442_ (
    .A1(_195_),
    .A2(_196_),
    .B1(_197_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nand2_2 _443_ (
    .A(_188_),
    .B(_175_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__xnor2_2 _444_ (
    .A(_198_),
    .B(_187_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__mux2_2 _445_ (
    .A0(\sum_rm[5] ),
    .A1(_199_),
    .S(_192_),
    .X(_200_)
  );
  sky130_fd_sc_hd__buf_1 _446_ (
    .A(_200_),
    .X(_164_)
  );
  sky130_fd_sc_hd__nand2_2 _447_ (
    .A(_186_),
    .B(_185_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__xnor2_2 _448_ (
    .A(_184_),
    .B(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__mux2_2 _449_ (
    .A0(\sum_rm[4] ),
    .A1(_202_),
    .S(_191_),
    .X(_203_)
  );
  sky130_fd_sc_hd__buf_1 _450_ (
    .A(_203_),
    .X(_163_)
  );
  sky130_fd_sc_hd__and3_2 _451_ (
    .A(_183_),
    .B(_176_),
    .C(_182_),
    .X(_204_)
  );
  sky130_fd_sc_hd__a21o_2 _452_ (
    .A1(_183_),
    .A2(_176_),
    .B1(_182_),
    .X(_205_)
  );
  sky130_fd_sc_hd__and3b_2 _453_ (
    .A_N(_204_),
    .B(_205_),
    .C(_192_),
    .X(_206_)
  );
  sky130_fd_sc_hd__a21o_2 _454_ (
    .A1(_194_),
    .A2(\sum_rm[3] ),
    .B1(_206_),
    .X(_162_)
  );
  sky130_fd_sc_hd__and3_2 _455_ (
    .A(_181_),
    .B(_179_),
    .C(_180_),
    .X(_207_)
  );
  sky130_fd_sc_hd__a21o_2 _456_ (
    .A1(_181_),
    .A2(_180_),
    .B1(_179_),
    .X(_208_)
  );
  sky130_fd_sc_hd__and3b_2 _457_ (
    .A_N(_207_),
    .B(_208_),
    .C(_192_),
    .X(_209_)
  );
  sky130_fd_sc_hd__a21o_2 _458_ (
    .A1(_194_),
    .A2(\sum_rm[2] ),
    .B1(_209_),
    .X(_161_)
  );
  sky130_fd_sc_hd__nand2_2 _459_ (
    .A(\RMIN[1] ),
    .B(\RMAX[1] ),
    .Y(_210_)
  );
  sky130_fd_sc_hd__and4_2 _460_ (
    .A(\RMIN[0] ),
    .B(\RMAX[0] ),
    .C(_210_),
    .D(_177_),
    .X(_211_)
  );
  sky130_fd_sc_hd__a22o_2 _461_ (
    .A1(\RMIN[0] ),
    .A2(\RMAX[0] ),
    .B1(_210_),
    .B2(_177_),
    .X(_212_)
  );
  sky130_fd_sc_hd__and3b_2 _462_ (
    .A_N(_211_),
    .B(_212_),
    .C(_192_),
    .X(_213_)
  );
  sky130_fd_sc_hd__a21o_2 _463_ (
    .A1(_194_),
    .A2(\sum_rm[1] ),
    .B1(_213_),
    .X(_160_)
  );
  sky130_fd_sc_hd__xor2_2 _464_ (
    .A(\RMIN[0] ),
    .B(\RMAX[0] ),
    .X(_214_)
  );
  sky130_fd_sc_hd__mux2_2 _465_ (
    .A0(\sum_rm[0] ),
    .A1(_214_),
    .S(_191_),
    .X(_215_)
  );
  sky130_fd_sc_hd__buf_1 _466_ (
    .A(_215_),
    .X(_159_)
  );
  sky130_fd_sc_hd__nor2_2 _467_ (
    .A(\stato[1] ),
    .B(\stato[2] ),
    .Y(_216_)
  );
  sky130_fd_sc_hd__buf_1 _468_ (
    .A(_216_),
    .X(_217_)
  );
  sky130_fd_sc_hd__inv_2 _469_ (
    .A(_217_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__buf_1 _470_ (
    .A(_195_),
    .X(_218_)
  );
  sky130_fd_sc_hd__a22o_2 _471_ (
    .A1(_218_),
    .A2(\REG3[10] ),
    .B1(_217_),
    .B2(\REG4[10] ),
    .X(_158_)
  );
  sky130_fd_sc_hd__a22o_2 _472_ (
    .A1(_218_),
    .A2(\REG3[6] ),
    .B1(_217_),
    .B2(\REG4[6] ),
    .X(_157_)
  );
  sky130_fd_sc_hd__a22o_2 _473_ (
    .A1(_218_),
    .A2(\REG3[5] ),
    .B1(_217_),
    .B2(\REG4[5] ),
    .X(_156_)
  );
  sky130_fd_sc_hd__a22o_2 _474_ (
    .A1(_218_),
    .A2(\REG3[4] ),
    .B1(_217_),
    .B2(\REG4[4] ),
    .X(_155_)
  );
  sky130_fd_sc_hd__a22o_2 _475_ (
    .A1(_218_),
    .A2(\REG3[3] ),
    .B1(_217_),
    .B2(\REG4[3] ),
    .X(_154_)
  );
  sky130_fd_sc_hd__a22o_2 _476_ (
    .A1(_218_),
    .A2(\REG3[2] ),
    .B1(_217_),
    .B2(\REG4[2] ),
    .X(_153_)
  );
  sky130_fd_sc_hd__a22o_2 _477_ (
    .A1(_218_),
    .A2(\REG3[1] ),
    .B1(_217_),
    .B2(\REG4[1] ),
    .X(_152_)
  );
  sky130_fd_sc_hd__a22o_2 _478_ (
    .A1(_218_),
    .A2(\REG3[0] ),
    .B1(_217_),
    .B2(\REG4[0] ),
    .X(_151_)
  );
  sky130_fd_sc_hd__a22o_2 _479_ (
    .A1(_218_),
    .A2(\REG2[10] ),
    .B1(_217_),
    .B2(\REG3[10] ),
    .X(_150_)
  );
  sky130_fd_sc_hd__buf_1 _480_ (
    .A(_216_),
    .X(_219_)
  );
  sky130_fd_sc_hd__a22o_2 _481_ (
    .A1(_218_),
    .A2(\REG2[6] ),
    .B1(_219_),
    .B2(\REG3[6] ),
    .X(_149_)
  );
  sky130_fd_sc_hd__buf_1 _482_ (
    .A(_195_),
    .X(_220_)
  );
  sky130_fd_sc_hd__a22o_2 _483_ (
    .A1(_220_),
    .A2(\REG2[5] ),
    .B1(_219_),
    .B2(\REG3[5] ),
    .X(_148_)
  );
  sky130_fd_sc_hd__a22o_2 _484_ (
    .A1(_220_),
    .A2(\REG2[4] ),
    .B1(_219_),
    .B2(\REG3[4] ),
    .X(_147_)
  );
  sky130_fd_sc_hd__a22o_2 _485_ (
    .A1(_220_),
    .A2(\REG2[3] ),
    .B1(_219_),
    .B2(\REG3[3] ),
    .X(_146_)
  );
  sky130_fd_sc_hd__a22o_2 _486_ (
    .A1(_220_),
    .A2(\REG2[2] ),
    .B1(_219_),
    .B2(\REG3[2] ),
    .X(_145_)
  );
  sky130_fd_sc_hd__a22o_2 _487_ (
    .A1(_220_),
    .A2(\REG2[1] ),
    .B1(_219_),
    .B2(\REG3[1] ),
    .X(_144_)
  );
  sky130_fd_sc_hd__a22o_2 _488_ (
    .A1(_220_),
    .A2(\REG2[0] ),
    .B1(_219_),
    .B2(\REG3[0] ),
    .X(_143_)
  );
  sky130_fd_sc_hd__a22o_2 _489_ (
    .A1(_220_),
    .A2(\REG1[10] ),
    .B1(_219_),
    .B2(\REG2[10] ),
    .X(_142_)
  );
  sky130_fd_sc_hd__a22o_2 _490_ (
    .A1(_220_),
    .A2(\REG1[6] ),
    .B1(_219_),
    .B2(\REG2[6] ),
    .X(_141_)
  );
  sky130_fd_sc_hd__a22o_2 _491_ (
    .A1(_220_),
    .A2(\REG1[5] ),
    .B1(_219_),
    .B2(\REG2[5] ),
    .X(_140_)
  );
  sky130_fd_sc_hd__buf_1 _492_ (
    .A(_216_),
    .X(_221_)
  );
  sky130_fd_sc_hd__a22o_2 _493_ (
    .A1(_220_),
    .A2(\REG1[4] ),
    .B1(_221_),
    .B2(\REG2[4] ),
    .X(_139_)
  );
  sky130_fd_sc_hd__buf_1 _494_ (
    .A(_192_),
    .X(_222_)
  );
  sky130_fd_sc_hd__a22o_2 _495_ (
    .A1(_222_),
    .A2(\REG1[3] ),
    .B1(_221_),
    .B2(\REG2[3] ),
    .X(_138_)
  );
  sky130_fd_sc_hd__a22o_2 _496_ (
    .A1(_222_),
    .A2(\REG1[2] ),
    .B1(_221_),
    .B2(\REG2[2] ),
    .X(_137_)
  );
  sky130_fd_sc_hd__a22o_2 _497_ (
    .A1(_222_),
    .A2(\REG1[1] ),
    .B1(_221_),
    .B2(\REG2[1] ),
    .X(_136_)
  );
  sky130_fd_sc_hd__a22o_2 _498_ (
    .A1(_222_),
    .A2(\REG1[0] ),
    .B1(_221_),
    .B2(\REG2[0] ),
    .X(_135_)
  );
  sky130_fd_sc_hd__a22o_2 _499_ (
    .A1(_222_),
    .A2(DATA_IN[7]),
    .B1(_221_),
    .B2(\REG1[10] ),
    .X(_134_)
  );
  sky130_fd_sc_hd__a22o_2 _500_ (
    .A1(_222_),
    .A2(DATA_IN[6]),
    .B1(_221_),
    .B2(\REG1[6] ),
    .X(_133_)
  );
  sky130_fd_sc_hd__a22o_2 _501_ (
    .A1(_222_),
    .A2(DATA_IN[5]),
    .B1(_221_),
    .B2(\REG1[5] ),
    .X(_132_)
  );
  sky130_fd_sc_hd__a22o_2 _502_ (
    .A1(_222_),
    .A2(DATA_IN[4]),
    .B1(_221_),
    .B2(\REG1[4] ),
    .X(_131_)
  );
  sky130_fd_sc_hd__a22o_2 _503_ (
    .A1(_222_),
    .A2(DATA_IN[3]),
    .B1(_221_),
    .B2(\REG1[3] ),
    .X(_130_)
  );
  sky130_fd_sc_hd__buf_1 _504_ (
    .A(_216_),
    .X(_223_)
  );
  sky130_fd_sc_hd__a22o_2 _505_ (
    .A1(_222_),
    .A2(DATA_IN[2]),
    .B1(_223_),
    .B2(\REG1[2] ),
    .X(_129_)
  );
  sky130_fd_sc_hd__a22o_2 _506_ (
    .A1(_195_),
    .A2(DATA_IN[1]),
    .B1(_223_),
    .B2(\REG1[1] ),
    .X(_128_)
  );
  sky130_fd_sc_hd__a22o_2 _507_ (
    .A1(_195_),
    .A2(DATA_IN[0]),
    .B1(_223_),
    .B2(\REG1[0] ),
    .X(_127_)
  );
  sky130_fd_sc_hd__inv_2 _508_ (
    .A(ENA),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor2_2 _509_ (
    .A(_167_),
    .B(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__and2_2 _510_ (
    .A(_167_),
    .B(\stato[2] ),
    .X(_226_)
  );
  sky130_fd_sc_hd__nor2_2 _511_ (
    .A(_225_),
    .B(_226_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a22o_2 _512_ (
    .A1(DATA_IN[7]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[7] ),
    .X(_126_)
  );
  sky130_fd_sc_hd__a22o_2 _513_ (
    .A1(DATA_IN[6]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[6] ),
    .X(_125_)
  );
  sky130_fd_sc_hd__a22o_2 _514_ (
    .A1(DATA_IN[5]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[5] ),
    .X(_124_)
  );
  sky130_fd_sc_hd__a22o_2 _515_ (
    .A1(DATA_IN[4]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[4] ),
    .X(_123_)
  );
  sky130_fd_sc_hd__a22o_2 _516_ (
    .A1(DATA_IN[3]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[3] ),
    .X(_122_)
  );
  sky130_fd_sc_hd__a22o_2 _517_ (
    .A1(DATA_IN[2]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[2] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__a22o_2 _518_ (
    .A1(DATA_IN[1]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[1] ),
    .X(_120_)
  );
  sky130_fd_sc_hd__a22o_2 _519_ (
    .A1(DATA_IN[0]),
    .A2(_225_),
    .B1(_227_),
    .B2(\RLAST[0] ),
    .X(_119_)
  );
  sky130_fd_sc_hd__inv_2 _520_ (
    .A(\RMIN[10] ),
    .Y(_228_)
  );
  sky130_fd_sc_hd__inv_2 _521_ (
    .A(DATA_IN[6]),
    .Y(_229_)
  );
  sky130_fd_sc_hd__inv_2 _522_ (
    .A(DATA_IN[5]),
    .Y(_230_)
  );
  sky130_fd_sc_hd__inv_2 _523_ (
    .A(DATA_IN[4]),
    .Y(_231_)
  );
  sky130_fd_sc_hd__inv_2 _524_ (
    .A(DATA_IN[3]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__inv_2 _525_ (
    .A(DATA_IN[2]),
    .Y(_233_)
  );
  sky130_fd_sc_hd__or2_2 _526_ (
    .A(\RMIN[2] ),
    .B(_233_),
    .X(_234_)
  );
  sky130_fd_sc_hd__inv_2 _527_ (
    .A(DATA_IN[1]),
    .Y(_235_)
  );
  sky130_fd_sc_hd__or2_2 _528_ (
    .A(\RMIN[1] ),
    .B(_235_),
    .X(_236_)
  );
  sky130_fd_sc_hd__inv_2 _529_ (
    .A(DATA_IN[0]),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a22o_2 _530_ (
    .A1(\RMIN[1] ),
    .A2(_235_),
    .B1(\RMIN[0] ),
    .B2(_237_),
    .X(_238_)
  );
  sky130_fd_sc_hd__a22o_2 _531_ (
    .A1(\RMIN[3] ),
    .A2(_232_),
    .B1(\RMIN[2] ),
    .B2(_233_),
    .X(_239_)
  );
  sky130_fd_sc_hd__a31o_2 _532_ (
    .A1(_234_),
    .A2(_236_),
    .A3(_238_),
    .B1(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__o221a_2 _533_ (
    .A1(\RMIN[4] ),
    .A2(_231_),
    .B1(\RMIN[3] ),
    .B2(_232_),
    .C1(_240_),
    .X(_241_)
  );
  sky130_fd_sc_hd__a221o_2 _534_ (
    .A1(\RMIN[5] ),
    .A2(_230_),
    .B1(\RMIN[4] ),
    .B2(_231_),
    .C1(_241_),
    .X(_242_)
  );
  sky130_fd_sc_hd__o221a_2 _535_ (
    .A1(\RMIN[6] ),
    .A2(_229_),
    .B1(\RMIN[5] ),
    .B2(_230_),
    .C1(_242_),
    .X(_243_)
  );
  sky130_fd_sc_hd__a22o_2 _536_ (
    .A1(_228_),
    .A2(DATA_IN[7]),
    .B1(\RMIN[6] ),
    .B2(_229_),
    .X(_244_)
  );
  sky130_fd_sc_hd__o22a_2 _537_ (
    .A1(_228_),
    .A2(DATA_IN[7]),
    .B1(_243_),
    .B2(_244_),
    .X(_245_)
  );
  sky130_fd_sc_hd__inv_2 _538_ (
    .A(\RMAX[10] ),
    .Y(_246_)
  );
  sky130_fd_sc_hd__a211o_2 _539_ (
    .A1(_235_),
    .A2(\RMAX[1] ),
    .B1(\RMAX[0] ),
    .C1(_237_),
    .X(_247_)
  );
  sky130_fd_sc_hd__o221a_2 _540_ (
    .A1(_233_),
    .A2(\RMAX[2] ),
    .B1(\RMAX[1] ),
    .B2(_235_),
    .C1(_247_),
    .X(_248_)
  );
  sky130_fd_sc_hd__a22o_2 _541_ (
    .A1(_232_),
    .A2(\RMAX[3] ),
    .B1(\RMAX[2] ),
    .B2(_233_),
    .X(_249_)
  );
  sky130_fd_sc_hd__o22a_2 _542_ (
    .A1(_231_),
    .A2(\RMAX[4] ),
    .B1(\RMAX[3] ),
    .B2(_232_),
    .X(_250_)
  );
  sky130_fd_sc_hd__o21a_2 _543_ (
    .A1(_248_),
    .A2(_249_),
    .B1(_250_),
    .X(_251_)
  );
  sky130_fd_sc_hd__a221o_2 _544_ (
    .A1(_230_),
    .A2(\RMAX[5] ),
    .B1(\RMAX[4] ),
    .B2(_231_),
    .C1(_251_),
    .X(_252_)
  );
  sky130_fd_sc_hd__o221a_2 _545_ (
    .A1(_229_),
    .A2(\RMAX[6] ),
    .B1(\RMAX[5] ),
    .B2(_230_),
    .C1(_252_),
    .X(_253_)
  );
  sky130_fd_sc_hd__a22o_2 _546_ (
    .A1(DATA_IN[7]),
    .A2(_246_),
    .B1(\RMAX[6] ),
    .B2(_229_),
    .X(_254_)
  );
  sky130_fd_sc_hd__o22a_2 _547_ (
    .A1(DATA_IN[7]),
    .A2(_246_),
    .B1(_253_),
    .B2(_254_),
    .X(_255_)
  );
  sky130_fd_sc_hd__a31o_2 _548_ (
    .A1(_191_),
    .A2(_245_),
    .A3(_255_),
    .B1(_226_),
    .X(_256_)
  );
  sky130_fd_sc_hd__mux2_2 _549_ (
    .A0(\RMIN[10] ),
    .A1(DATA_IN[7]),
    .S(_256_),
    .X(_257_)
  );
  sky130_fd_sc_hd__buf_1 _550_ (
    .A(_257_),
    .X(_118_)
  );
  sky130_fd_sc_hd__mux2_2 _551_ (
    .A0(\RMIN[6] ),
    .A1(DATA_IN[6]),
    .S(_256_),
    .X(_258_)
  );
  sky130_fd_sc_hd__buf_1 _552_ (
    .A(_258_),
    .X(_117_)
  );
  sky130_fd_sc_hd__mux2_2 _553_ (
    .A0(\RMIN[5] ),
    .A1(DATA_IN[5]),
    .S(_256_),
    .X(_259_)
  );
  sky130_fd_sc_hd__buf_1 _554_ (
    .A(_259_),
    .X(_116_)
  );
  sky130_fd_sc_hd__mux2_2 _555_ (
    .A0(\RMIN[4] ),
    .A1(DATA_IN[4]),
    .S(_256_),
    .X(_260_)
  );
  sky130_fd_sc_hd__buf_1 _556_ (
    .A(_260_),
    .X(_115_)
  );
  sky130_fd_sc_hd__mux2_2 _557_ (
    .A0(\RMIN[3] ),
    .A1(DATA_IN[3]),
    .S(_256_),
    .X(_261_)
  );
  sky130_fd_sc_hd__buf_1 _558_ (
    .A(_261_),
    .X(_114_)
  );
  sky130_fd_sc_hd__mux2_2 _559_ (
    .A0(\RMIN[2] ),
    .A1(DATA_IN[2]),
    .S(_256_),
    .X(_262_)
  );
  sky130_fd_sc_hd__buf_1 _560_ (
    .A(_262_),
    .X(_113_)
  );
  sky130_fd_sc_hd__mux2_2 _561_ (
    .A0(\RMIN[1] ),
    .A1(DATA_IN[1]),
    .S(_256_),
    .X(_263_)
  );
  sky130_fd_sc_hd__buf_1 _562_ (
    .A(_263_),
    .X(_112_)
  );
  sky130_fd_sc_hd__mux2_2 _563_ (
    .A0(\RMIN[0] ),
    .A1(DATA_IN[0]),
    .S(_256_),
    .X(_264_)
  );
  sky130_fd_sc_hd__buf_1 _564_ (
    .A(_264_),
    .X(_111_)
  );
  sky130_fd_sc_hd__a21o_2 _565_ (
    .A1(_191_),
    .A2(_255_),
    .B1(_216_),
    .X(_265_)
  );
  sky130_fd_sc_hd__mux2_2 _566_ (
    .A0(DATA_IN[7]),
    .A1(\RMAX[10] ),
    .S(_265_),
    .X(_266_)
  );
  sky130_fd_sc_hd__buf_1 _567_ (
    .A(_266_),
    .X(_110_)
  );
  sky130_fd_sc_hd__mux2_2 _568_ (
    .A0(DATA_IN[6]),
    .A1(\RMAX[6] ),
    .S(_265_),
    .X(_267_)
  );
  sky130_fd_sc_hd__buf_1 _569_ (
    .A(_267_),
    .X(_109_)
  );
  sky130_fd_sc_hd__mux2_2 _570_ (
    .A0(DATA_IN[5]),
    .A1(\RMAX[5] ),
    .S(_265_),
    .X(_268_)
  );
  sky130_fd_sc_hd__buf_1 _571_ (
    .A(_268_),
    .X(_108_)
  );
  sky130_fd_sc_hd__mux2_2 _572_ (
    .A0(DATA_IN[4]),
    .A1(\RMAX[4] ),
    .S(_265_),
    .X(_269_)
  );
  sky130_fd_sc_hd__buf_1 _573_ (
    .A(_269_),
    .X(_107_)
  );
  sky130_fd_sc_hd__mux2_2 _574_ (
    .A0(DATA_IN[3]),
    .A1(\RMAX[3] ),
    .S(_265_),
    .X(_270_)
  );
  sky130_fd_sc_hd__buf_1 _575_ (
    .A(_270_),
    .X(_106_)
  );
  sky130_fd_sc_hd__mux2_2 _576_ (
    .A0(DATA_IN[2]),
    .A1(\RMAX[2] ),
    .S(_265_),
    .X(_271_)
  );
  sky130_fd_sc_hd__buf_1 _577_ (
    .A(_271_),
    .X(_105_)
  );
  sky130_fd_sc_hd__mux2_2 _578_ (
    .A0(DATA_IN[1]),
    .A1(\RMAX[1] ),
    .S(_265_),
    .X(_272_)
  );
  sky130_fd_sc_hd__buf_1 _579_ (
    .A(_272_),
    .X(_104_)
  );
  sky130_fd_sc_hd__mux2_2 _580_ (
    .A0(DATA_IN[0]),
    .A1(\RMAX[0] ),
    .S(_265_),
    .X(_273_)
  );
  sky130_fd_sc_hd__buf_1 _581_ (
    .A(_273_),
    .X(_103_)
  );
  sky130_fd_sc_hd__buf_1 _582_ (
    .A(AVE),
    .X(_274_)
  );
  sky130_fd_sc_hd__a21o_2 _583_ (
    .A1(\REG4[10] ),
    .A2(_274_),
    .B1(_224_),
    .X(_275_)
  );
  sky130_fd_sc_hd__nor2_2 _584_ (
    .A(_167_),
    .B(RES),
    .Y(_276_)
  );
  sky130_fd_sc_hd__or2_2 _585_ (
    .A(\RLAST[7] ),
    .B(ENA),
    .X(_277_)
  );
  sky130_fd_sc_hd__a32o_2 _586_ (
    .A1(_275_),
    .A2(_276_),
    .A3(_277_),
    .B1(_223_),
    .B2(DATA_OUT[7]),
    .X(_102_)
  );
  sky130_fd_sc_hd__or4_2 _587_ (
    .A(\sum_in[3] ),
    .B(\sum_in[2] ),
    .C(\sum_in[1] ),
    .D(\sum_in[0] ),
    .X(_278_)
  );
  sky130_fd_sc_hd__or3_2 _588_ (
    .A(\sum_in[5] ),
    .B(\sum_in[4] ),
    .C(_278_),
    .X(_279_)
  );
  sky130_fd_sc_hd__o21ai_2 _589_ (
    .A1(\sum_in[4] ),
    .A2(_278_),
    .B1(\sum_in[5] ),
    .Y(_280_)
  );
  sky130_fd_sc_hd__and2_2 _590_ (
    .A(_279_),
    .B(_280_),
    .X(_281_)
  );
  sky130_fd_sc_hd__and2_2 _591_ (
    .A(\sum_in[1] ),
    .B(\sum_in[0] ),
    .X(_282_)
  );
  sky130_fd_sc_hd__or3_2 _592_ (
    .A(\sum_in[2] ),
    .B(\sum_in[1] ),
    .C(\sum_in[0] ),
    .X(_283_)
  );
  sky130_fd_sc_hd__a21boi_2 _593_ (
    .A1(\sum_in[2] ),
    .A2(_282_),
    .B1_N(_283_),
    .Y(_284_)
  );
  sky130_fd_sc_hd__xor2_2 _594_ (
    .A(\sum_in[3] ),
    .B(_283_),
    .X(_285_)
  );
  sky130_fd_sc_hd__xor2_2 _595_ (
    .A(\sum_in[4] ),
    .B(_278_),
    .X(_286_)
  );
  sky130_fd_sc_hd__or3_2 _596_ (
    .A(_284_),
    .B(_285_),
    .C(_286_),
    .X(_287_)
  );
  sky130_fd_sc_hd__nor2_2 _597_ (
    .A(_281_),
    .B(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__xor2_2 _598_ (
    .A(\sum_in[6] ),
    .B(_279_),
    .X(_289_)
  );
  sky130_fd_sc_hd__o21ai_2 _599_ (
    .A1(_288_),
    .A2(_289_),
    .B1(\sum_in[31] ),
    .Y(_290_)
  );
  sky130_fd_sc_hd__a21o_2 _600_ (
    .A1(_288_),
    .A2(_289_),
    .B1(_290_),
    .X(_291_)
  );
  sky130_fd_sc_hd__nor2_2 _601_ (
    .A(_274_),
    .B(_291_),
    .Y(_292_)
  );
  sky130_fd_sc_hd__a221o_2 _602_ (
    .A1(\REG4[6] ),
    .A2(_274_),
    .B1(_292_),
    .B2(\sum_in[6] ),
    .C1(_224_),
    .X(_293_)
  );
  sky130_fd_sc_hd__or2_2 _603_ (
    .A(\RLAST[6] ),
    .B(ENA),
    .X(_294_)
  );
  sky130_fd_sc_hd__or4_2 _604_ (
    .A(\sum_rm[3] ),
    .B(\sum_rm[2] ),
    .C(\sum_rm[1] ),
    .D(\sum_rm[0] ),
    .X(_295_)
  );
  sky130_fd_sc_hd__or3_2 _605_ (
    .A(\sum_rm[5] ),
    .B(\sum_rm[4] ),
    .C(_295_),
    .X(_296_)
  );
  sky130_fd_sc_hd__o21ai_2 _606_ (
    .A1(\sum_rm[4] ),
    .A2(_295_),
    .B1(\sum_rm[5] ),
    .Y(_297_)
  );
  sky130_fd_sc_hd__and2_2 _607_ (
    .A(_296_),
    .B(_297_),
    .X(_298_)
  );
  sky130_fd_sc_hd__and2_2 _608_ (
    .A(\sum_rm[1] ),
    .B(\sum_rm[0] ),
    .X(_299_)
  );
  sky130_fd_sc_hd__nand3_2 _609_ (
    .A(\sum_rm[3] ),
    .B(\sum_rm[2] ),
    .C(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__xor2_2 _610_ (
    .A(\sum_rm[4] ),
    .B(_295_),
    .X(_301_)
  );
  sky130_fd_sc_hd__a21o_2 _611_ (
    .A1(_295_),
    .A2(_300_),
    .B1(_301_),
    .X(_302_)
  );
  sky130_fd_sc_hd__nor2_2 _612_ (
    .A(_298_),
    .B(_302_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__xor2_2 _613_ (
    .A(\sum_rm[6] ),
    .B(_296_),
    .X(_304_)
  );
  sky130_fd_sc_hd__xor2_2 _614_ (
    .A(_303_),
    .B(_304_),
    .X(_305_)
  );
  sky130_fd_sc_hd__and2_2 _615_ (
    .A(_191_),
    .B(RES),
    .X(_306_)
  );
  sky130_fd_sc_hd__and3_2 _616_ (
    .A(\sum_rm[31] ),
    .B(_305_),
    .C(_306_),
    .X(_307_)
  );
  sky130_fd_sc_hd__a22o_2 _617_ (
    .A1(DATA_OUT[6]),
    .A2(_216_),
    .B1(_307_),
    .B2(\sum_rm[6] ),
    .X(_308_)
  );
  sky130_fd_sc_hd__a31o_2 _618_ (
    .A1(_276_),
    .A2(_293_),
    .A3(_294_),
    .B1(_308_),
    .X(_101_)
  );
  sky130_fd_sc_hd__inv_2 _619_ (
    .A(AVE),
    .Y(_309_)
  );
  sky130_fd_sc_hd__o211a_2 _620_ (
    .A1(\sum_in[31] ),
    .A2(\sum_in[6] ),
    .B1(_309_),
    .C1(_291_),
    .X(_310_)
  );
  sky130_fd_sc_hd__a21o_2 _621_ (
    .A1(\REG4[5] ),
    .A2(_274_),
    .B1(_224_),
    .X(_311_)
  );
  sky130_fd_sc_hd__o221a_2 _622_ (
    .A1(\RLAST[5] ),
    .A2(ENA),
    .B1(_310_),
    .B2(_311_),
    .C1(_276_),
    .X(_312_)
  );
  sky130_fd_sc_hd__nand2_2 _623_ (
    .A(\sum_rm[31] ),
    .B(_305_),
    .Y(_313_)
  );
  sky130_fd_sc_hd__o211a_2 _624_ (
    .A1(\sum_rm[31] ),
    .A2(\sum_rm[6] ),
    .B1(_313_),
    .C1(_306_),
    .X(_314_)
  );
  sky130_fd_sc_hd__a211o_2 _625_ (
    .A1(DATA_OUT[5]),
    .A2(_223_),
    .B1(_312_),
    .C1(_314_),
    .X(_100_)
  );
  sky130_fd_sc_hd__and2_2 _626_ (
    .A(_298_),
    .B(_302_),
    .X(_315_)
  );
  sky130_fd_sc_hd__nor2_2 _627_ (
    .A(_303_),
    .B(_315_),
    .Y(_316_)
  );
  sky130_fd_sc_hd__mux2_2 _628_ (
    .A0(\sum_rm[5] ),
    .A1(_316_),
    .S(\sum_rm[31] ),
    .X(_317_)
  );
  sky130_fd_sc_hd__inv_2 _629_ (
    .A(\sum_in[31] ),
    .Y(_318_)
  );
  sky130_fd_sc_hd__and2_2 _630_ (
    .A(_281_),
    .B(_287_),
    .X(_319_)
  );
  sky130_fd_sc_hd__nor2_2 _631_ (
    .A(_288_),
    .B(_319_),
    .Y(_320_)
  );
  sky130_fd_sc_hd__or2_2 _632_ (
    .A(\sum_in[31] ),
    .B(\sum_in[5] ),
    .X(_321_)
  );
  sky130_fd_sc_hd__o211a_2 _633_ (
    .A1(_318_),
    .A2(_320_),
    .B1(_321_),
    .C1(_309_),
    .X(_322_)
  );
  sky130_fd_sc_hd__a21o_2 _634_ (
    .A1(\REG4[4] ),
    .A2(_274_),
    .B1(_224_),
    .X(_323_)
  );
  sky130_fd_sc_hd__o221a_2 _635_ (
    .A1(\RLAST[4] ),
    .A2(ENA),
    .B1(_322_),
    .B2(_323_),
    .C1(_276_),
    .X(_324_)
  );
  sky130_fd_sc_hd__a221o_2 _636_ (
    .A1(DATA_OUT[4]),
    .A2(_223_),
    .B1(_306_),
    .B2(_317_),
    .C1(_324_),
    .X(_099_)
  );
  sky130_fd_sc_hd__a21bo_2 _637_ (
    .A1(_295_),
    .A2(_300_),
    .B1_N(\sum_rm[31] ),
    .X(_325_)
  );
  sky130_fd_sc_hd__mux2_2 _638_ (
    .A0(_301_),
    .A1(\sum_rm[4] ),
    .S(_325_),
    .X(_326_)
  );
  sky130_fd_sc_hd__o21ai_2 _639_ (
    .A1(_284_),
    .A2(_285_),
    .B1(_286_),
    .Y(_327_)
  );
  sky130_fd_sc_hd__a21oi_2 _640_ (
    .A1(_287_),
    .A2(_327_),
    .B1(_318_),
    .Y(_328_)
  );
  sky130_fd_sc_hd__nor2_2 _641_ (
    .A(\sum_in[31] ),
    .B(\sum_in[4] ),
    .Y(_329_)
  );
  sky130_fd_sc_hd__nand2_2 _642_ (
    .A(\REG4[3] ),
    .B(_274_),
    .Y(_330_)
  );
  sky130_fd_sc_hd__o311ai_2 _643_ (
    .A1(_274_),
    .A2(_328_),
    .A3(_329_),
    .B1(_330_),
    .C1(ENA),
    .Y(_331_)
  );
  sky130_fd_sc_hd__o211a_2 _644_ (
    .A1(\RLAST[3] ),
    .A2(ENA),
    .B1(_276_),
    .C1(_331_),
    .X(_332_)
  );
  sky130_fd_sc_hd__a221o_2 _645_ (
    .A1(DATA_OUT[3]),
    .A2(_223_),
    .B1(_306_),
    .B2(_326_),
    .C1(_332_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nor2_2 _646_ (
    .A(_318_),
    .B(_284_),
    .Y(_333_)
  );
  sky130_fd_sc_hd__mux2_2 _647_ (
    .A0(\sum_in[3] ),
    .A1(_285_),
    .S(_333_),
    .X(_334_)
  );
  sky130_fd_sc_hd__mux2_2 _648_ (
    .A0(\REG4[2] ),
    .A1(_334_),
    .S(_309_),
    .X(_335_)
  );
  sky130_fd_sc_hd__mux2_2 _649_ (
    .A0(\RLAST[2] ),
    .A1(_335_),
    .S(ENA),
    .X(_336_)
  );
  sky130_fd_sc_hd__nor2_2 _650_ (
    .A(\sum_rm[1] ),
    .B(\sum_rm[0] ),
    .Y(_337_)
  );
  sky130_fd_sc_hd__mux2_2 _651_ (
    .A0(_337_),
    .A1(_299_),
    .S(\sum_rm[2] ),
    .X(_338_)
  );
  sky130_fd_sc_hd__a21o_2 _652_ (
    .A1(\sum_rm[31] ),
    .A2(_338_),
    .B1(\sum_rm[3] ),
    .X(_339_)
  );
  sky130_fd_sc_hd__and3_2 _653_ (
    .A(_306_),
    .B(_325_),
    .C(_339_),
    .X(_340_)
  );
  sky130_fd_sc_hd__a221o_2 _654_ (
    .A1(DATA_OUT[2]),
    .A2(_223_),
    .B1(_276_),
    .B2(_336_),
    .C1(_340_),
    .X(_097_)
  );
  sky130_fd_sc_hd__nor2_2 _655_ (
    .A(\sum_in[1] ),
    .B(\sum_in[0] ),
    .Y(_341_)
  );
  sky130_fd_sc_hd__o21a_2 _656_ (
    .A1(_341_),
    .A2(_282_),
    .B1(\sum_in[31] ),
    .X(_342_)
  );
  sky130_fd_sc_hd__o221a_2 _657_ (
    .A1(_318_),
    .A2(_284_),
    .B1(_342_),
    .B2(\sum_in[2] ),
    .C1(_309_),
    .X(_343_)
  );
  sky130_fd_sc_hd__a21o_2 _658_ (
    .A1(\REG4[1] ),
    .A2(_274_),
    .B1(_224_),
    .X(_344_)
  );
  sky130_fd_sc_hd__o221a_2 _659_ (
    .A1(\RLAST[1] ),
    .A2(ENA),
    .B1(_343_),
    .B2(_344_),
    .C1(_276_),
    .X(_345_)
  );
  sky130_fd_sc_hd__o21a_2 _660_ (
    .A1(_337_),
    .A2(_299_),
    .B1(\sum_rm[31] ),
    .X(_346_)
  );
  sky130_fd_sc_hd__nand2_2 _661_ (
    .A(\sum_rm[31] ),
    .B(_338_),
    .Y(_347_)
  );
  sky130_fd_sc_hd__o211a_2 _662_ (
    .A1(\sum_rm[2] ),
    .A2(_346_),
    .B1(_347_),
    .C1(_306_),
    .X(_348_)
  );
  sky130_fd_sc_hd__a211o_2 _663_ (
    .A1(DATA_OUT[1]),
    .A2(_223_),
    .B1(_345_),
    .C1(_348_),
    .X(_096_)
  );
  sky130_fd_sc_hd__inv_2 _664_ (
    .A(\sum_in[1] ),
    .Y(_349_)
  );
  sky130_fd_sc_hd__a211oi_2 _665_ (
    .A1(_318_),
    .A2(_349_),
    .B1(_274_),
    .C1(_342_),
    .Y(_350_)
  );
  sky130_fd_sc_hd__a21o_2 _666_ (
    .A1(\REG4[0] ),
    .A2(_274_),
    .B1(_224_),
    .X(_351_)
  );
  sky130_fd_sc_hd__o221a_2 _667_ (
    .A1(\RLAST[0] ),
    .A2(ENA),
    .B1(_350_),
    .B2(_351_),
    .C1(_276_),
    .X(_352_)
  );
  sky130_fd_sc_hd__o21ai_2 _668_ (
    .A1(\sum_rm[31] ),
    .A2(\sum_rm[1] ),
    .B1(_306_),
    .Y(_353_)
  );
  sky130_fd_sc_hd__nor2_2 _669_ (
    .A(_346_),
    .B(_353_),
    .Y(_354_)
  );
  sky130_fd_sc_hd__a211o_2 _670_ (
    .A1(DATA_OUT[0]),
    .A2(_223_),
    .B1(_352_),
    .C1(_354_),
    .X(_095_)
  );
  sky130_fd_sc_hd__or2_2 _671_ (
    .A(\REG4[10] ),
    .B(DATA_IN[7]),
    .X(_355_)
  );
  sky130_fd_sc_hd__nand2_2 _672_ (
    .A(\REG4[10] ),
    .B(DATA_IN[7]),
    .Y(_356_)
  );
  sky130_fd_sc_hd__nand2_2 _673_ (
    .A(_355_),
    .B(_356_),
    .Y(_357_)
  );
  sky130_fd_sc_hd__and2_2 _674_ (
    .A(\REG4[6] ),
    .B(DATA_IN[6]),
    .X(_358_)
  );
  sky130_fd_sc_hd__nor2_2 _675_ (
    .A(\REG4[6] ),
    .B(DATA_IN[6]),
    .Y(_359_)
  );
  sky130_fd_sc_hd__nor2_2 _676_ (
    .A(_358_),
    .B(_359_),
    .Y(_360_)
  );
  sky130_fd_sc_hd__or2_2 _677_ (
    .A(\REG4[5] ),
    .B(DATA_IN[5]),
    .X(_361_)
  );
  sky130_fd_sc_hd__or2_2 _678_ (
    .A(\REG4[3] ),
    .B(DATA_IN[3]),
    .X(_362_)
  );
  sky130_fd_sc_hd__or2_2 _679_ (
    .A(\REG4[1] ),
    .B(DATA_IN[1]),
    .X(_363_)
  );
  sky130_fd_sc_hd__and2_2 _680_ (
    .A(\REG4[1] ),
    .B(DATA_IN[1]),
    .X(_364_)
  );
  sky130_fd_sc_hd__a31o_2 _681_ (
    .A1(\REG4[0] ),
    .A2(DATA_IN[0]),
    .A3(_363_),
    .B1(_364_),
    .X(_365_)
  );
  sky130_fd_sc_hd__or2_2 _682_ (
    .A(\REG4[2] ),
    .B(DATA_IN[2]),
    .X(_366_)
  );
  sky130_fd_sc_hd__nand2_2 _683_ (
    .A(\REG4[2] ),
    .B(DATA_IN[2]),
    .Y(_367_)
  );
  sky130_fd_sc_hd__a21bo_2 _684_ (
    .A1(_365_),
    .A2(_366_),
    .B1_N(_367_),
    .X(_368_)
  );
  sky130_fd_sc_hd__nand2_2 _685_ (
    .A(\REG4[3] ),
    .B(DATA_IN[3]),
    .Y(_369_)
  );
  sky130_fd_sc_hd__a21bo_2 _686_ (
    .A1(_362_),
    .A2(_368_),
    .B1_N(_369_),
    .X(_370_)
  );
  sky130_fd_sc_hd__or2_2 _687_ (
    .A(\REG4[4] ),
    .B(DATA_IN[4]),
    .X(_371_)
  );
  sky130_fd_sc_hd__nand2_2 _688_ (
    .A(\REG4[4] ),
    .B(DATA_IN[4]),
    .Y(_372_)
  );
  sky130_fd_sc_hd__a21bo_2 _689_ (
    .A1(_370_),
    .A2(_371_),
    .B1_N(_372_),
    .X(_373_)
  );
  sky130_fd_sc_hd__nand2_2 _690_ (
    .A(\REG4[5] ),
    .B(DATA_IN[5]),
    .Y(_374_)
  );
  sky130_fd_sc_hd__a21bo_2 _691_ (
    .A1(_361_),
    .A2(_373_),
    .B1_N(_374_),
    .X(_375_)
  );
  sky130_fd_sc_hd__a21oi_2 _692_ (
    .A1(_360_),
    .A2(_375_),
    .B1(_358_),
    .Y(_376_)
  );
  sky130_fd_sc_hd__o211a_2 _693_ (
    .A1(_357_),
    .A2(_376_),
    .B1(_192_),
    .C1(_355_),
    .X(_377_)
  );
  sky130_fd_sc_hd__a21o_2 _694_ (
    .A1(_194_),
    .A2(\sum_in[31] ),
    .B1(_377_),
    .X(_094_)
  );
  sky130_fd_sc_hd__xnor2_2 _695_ (
    .A(_360_),
    .B(_375_),
    .Y(_378_)
  );
  sky130_fd_sc_hd__nor2_2 _696_ (
    .A(_195_),
    .B(\sum_in[6] ),
    .Y(_379_)
  );
  sky130_fd_sc_hd__a21oi_2 _697_ (
    .A1(_195_),
    .A2(_378_),
    .B1(_379_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nand2_2 _698_ (
    .A(_374_),
    .B(_361_),
    .Y(_380_)
  );
  sky130_fd_sc_hd__xnor2_2 _699_ (
    .A(_380_),
    .B(_373_),
    .Y(_381_)
  );
  sky130_fd_sc_hd__mux2_2 _700_ (
    .A0(\sum_in[5] ),
    .A1(_381_),
    .S(_191_),
    .X(_382_)
  );
  sky130_fd_sc_hd__buf_1 _701_ (
    .A(_382_),
    .X(_092_)
  );
  sky130_fd_sc_hd__nand2_2 _702_ (
    .A(_372_),
    .B(_371_),
    .Y(_383_)
  );
  sky130_fd_sc_hd__xnor2_2 _703_ (
    .A(_370_),
    .B(_383_),
    .Y(_384_)
  );
  sky130_fd_sc_hd__mux2_2 _704_ (
    .A0(\sum_in[4] ),
    .A1(_384_),
    .S(_191_),
    .X(_385_)
  );
  sky130_fd_sc_hd__buf_1 _705_ (
    .A(_385_),
    .X(_091_)
  );
  sky130_fd_sc_hd__and3_2 _706_ (
    .A(_369_),
    .B(_362_),
    .C(_368_),
    .X(_386_)
  );
  sky130_fd_sc_hd__a21o_2 _707_ (
    .A1(_369_),
    .A2(_362_),
    .B1(_368_),
    .X(_387_)
  );
  sky130_fd_sc_hd__and3b_2 _708_ (
    .A_N(_386_),
    .B(_387_),
    .C(_192_),
    .X(_388_)
  );
  sky130_fd_sc_hd__a21o_2 _709_ (
    .A1(_168_),
    .A2(\sum_in[3] ),
    .B1(_388_),
    .X(_090_)
  );
  sky130_fd_sc_hd__and3_2 _710_ (
    .A(_367_),
    .B(_365_),
    .C(_366_),
    .X(_389_)
  );
  sky130_fd_sc_hd__a21o_2 _711_ (
    .A1(_367_),
    .A2(_366_),
    .B1(_365_),
    .X(_390_)
  );
  sky130_fd_sc_hd__and3b_2 _712_ (
    .A_N(_389_),
    .B(_390_),
    .C(_192_),
    .X(_391_)
  );
  sky130_fd_sc_hd__a21o_2 _713_ (
    .A1(_168_),
    .A2(\sum_in[2] ),
    .B1(_391_),
    .X(_089_)
  );
  sky130_fd_sc_hd__nand2_2 _714_ (
    .A(\REG4[1] ),
    .B(DATA_IN[1]),
    .Y(_392_)
  );
  sky130_fd_sc_hd__and4_2 _715_ (
    .A(\REG4[0] ),
    .B(DATA_IN[0]),
    .C(_392_),
    .D(_363_),
    .X(_393_)
  );
  sky130_fd_sc_hd__a22o_2 _716_ (
    .A1(\REG4[0] ),
    .A2(DATA_IN[0]),
    .B1(_392_),
    .B2(_363_),
    .X(_394_)
  );
  sky130_fd_sc_hd__and3b_2 _717_ (
    .A_N(_393_),
    .B(_394_),
    .C(_192_),
    .X(_395_)
  );
  sky130_fd_sc_hd__a21o_2 _718_ (
    .A1(_168_),
    .A2(\sum_in[1] ),
    .B1(_395_),
    .X(_088_)
  );
  sky130_fd_sc_hd__xor2_2 _719_ (
    .A(\REG4[0] ),
    .B(DATA_IN[0]),
    .X(_396_)
  );
  sky130_fd_sc_hd__mux2_2 _720_ (
    .A0(\sum_in[0] ),
    .A1(_396_),
    .S(_191_),
    .X(_397_)
  );
  sky130_fd_sc_hd__buf_1 _721_ (
    .A(_397_),
    .X(_087_)
  );
  sky130_fd_sc_hd__buf_1 _722_ (
    .A(RESET),
    .X(_398_)
  );
  sky130_fd_sc_hd__buf_1 _723_ (
    .A(_398_),
    .X(_399_)
  );
  sky130_fd_sc_hd__buf_1 _724_ (
    .A(_399_),
    .X(_400_)
  );
  sky130_fd_sc_hd__inv_2 _725_ (
    .A(_400_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_2 _726_ (
    .A(_400_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_2 _727_ (
    .A(_400_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _728_ (
    .A(_400_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _729_ (
    .A(_400_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _730_ (
    .A(_400_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _731_ (
    .A(_400_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__buf_1 _732_ (
    .A(_399_),
    .X(_401_)
  );
  sky130_fd_sc_hd__inv_2 _733_ (
    .A(_401_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__inv_2 _734_ (
    .A(_401_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _735_ (
    .A(_401_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _736_ (
    .A(_401_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _737_ (
    .A(_401_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _738_ (
    .A(_401_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _739_ (
    .A(_401_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__buf_1 _740_ (
    .A(_398_),
    .X(_402_)
  );
  sky130_fd_sc_hd__inv_2 _741_ (
    .A(_402_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _742_ (
    .A(_402_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _743_ (
    .A(_402_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _744_ (
    .A(_402_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _745_ (
    .A(_402_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__inv_2 _746_ (
    .A(_402_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _747_ (
    .A(_402_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _748_ (
    .A(_402_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _749_ (
    .A(_402_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _750_ (
    .A(_402_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__buf_1 _751_ (
    .A(_398_),
    .X(_403_)
  );
  sky130_fd_sc_hd__inv_2 _752_ (
    .A(_403_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _753_ (
    .A(_403_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _754_ (
    .A(_403_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _755_ (
    .A(_403_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _756_ (
    .A(_403_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _757_ (
    .A(_403_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _758_ (
    .A(_403_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__inv_2 _759_ (
    .A(_403_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__inv_2 _760_ (
    .A(_403_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__inv_2 _761_ (
    .A(_403_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__buf_1 _762_ (
    .A(_398_),
    .X(_404_)
  );
  sky130_fd_sc_hd__inv_2 _763_ (
    .A(_404_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__inv_2 _764_ (
    .A(_404_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__inv_2 _765_ (
    .A(_404_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__inv_2 _766_ (
    .A(_404_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_2 _767_ (
    .A(_404_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_2 _768_ (
    .A(_404_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_2 _769_ (
    .A(_404_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _770_ (
    .A(_404_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _771_ (
    .A(_404_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__inv_2 _772_ (
    .A(_404_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__buf_1 _773_ (
    .A(_398_),
    .X(_405_)
  );
  sky130_fd_sc_hd__inv_2 _774_ (
    .A(_405_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__inv_2 _775_ (
    .A(_405_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_2 _776_ (
    .A(_405_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__inv_2 _777_ (
    .A(_405_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__inv_2 _778_ (
    .A(_405_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__inv_2 _779_ (
    .A(_405_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__inv_2 _780_ (
    .A(_405_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__inv_2 _781_ (
    .A(_405_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__inv_2 _782_ (
    .A(_405_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__inv_2 _783_ (
    .A(_405_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__buf_1 _784_ (
    .A(_398_),
    .X(_406_)
  );
  sky130_fd_sc_hd__inv_2 _785_ (
    .A(_406_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__inv_2 _786_ (
    .A(_406_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__inv_2 _787_ (
    .A(_406_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__inv_2 _788_ (
    .A(_406_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__inv_2 _789_ (
    .A(_406_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__inv_2 _790_ (
    .A(_406_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__inv_2 _791_ (
    .A(_406_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__inv_2 _792_ (
    .A(_406_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__inv_2 _793_ (
    .A(_406_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__inv_2 _794_ (
    .A(_406_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__buf_1 _795_ (
    .A(_398_),
    .X(_407_)
  );
  sky130_fd_sc_hd__inv_2 _796_ (
    .A(_407_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__inv_2 _797_ (
    .A(_407_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__inv_2 _798_ (
    .A(_407_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__inv_2 _799_ (
    .A(_407_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__inv_2 _800_ (
    .A(_407_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__inv_2 _801_ (
    .A(_407_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__inv_2 _802_ (
    .A(_407_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__inv_2 _803_ (
    .A(_407_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__inv_2 _804_ (
    .A(_407_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__inv_2 _805_ (
    .A(_407_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__buf_1 _806_ (
    .A(_398_),
    .X(_408_)
  );
  sky130_fd_sc_hd__inv_2 _807_ (
    .A(_408_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__inv_2 _808_ (
    .A(_408_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__inv_2 _809_ (
    .A(_408_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__inv_2 _810_ (
    .A(_408_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__inv_2 _811_ (
    .A(_408_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__inv_2 _812_ (
    .A(_408_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__inv_2 _813_ (
    .A(_408_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__inv_2 _814_ (
    .A(_408_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__inv_2 _815_ (
    .A(_408_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__inv_2 _816_ (
    .A(_408_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__inv_2 _817_ (
    .A(_399_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__inv_2 _818_ (
    .A(_399_),
    .Y(_086_)
  );
  FI_DFF_DFRTP_FAULTY _819_ (
    .CLK(CLOCK),
    .D(_087_),
    .RESET_B(_001_),
    .fault_en(fault_en[0]),
    .Q(\sum_in[0] )
  );
FI_DFF_DFRTP_FAULTY _820_ (
  .CLK(CLOCK),
  .D(_088_),
  .RESET_B(_002_),
  .fault_en(fault_en[1]),
  .Q(\sum_in[1] )
);
FI_DFF_DFRTP_FAULTY _821_ (
  .CLK(CLOCK),
  .D(_089_),
  .RESET_B(_003_),
  .fault_en(fault_en[2]),
  .Q(\sum_in[2] )
);
FI_DFF_DFRTP_FAULTY _822_ (
  .CLK(CLOCK),
  .D(_090_),
  .RESET_B(_004_),
  .fault_en(fault_en[3]),
  .Q(\sum_in[3] )
);
FI_DFF_DFRTP_FAULTY _823_ (
  .CLK(CLOCK),
  .D(_091_),
  .RESET_B(_005_),
  .fault_en(fault_en[4]),
  .Q(\sum_in[4] )
);
FI_DFF_DFRTP_FAULTY _824_ (
  .CLK(CLOCK),
  .D(_092_),
  .RESET_B(_006_),
  .fault_en(fault_en[5]),
  .Q(\sum_in[5] )
);
FI_DFF_DFRTP_FAULTY _825_ (
  .CLK(CLOCK),
  .D(_093_),
  .RESET_B(_007_),
  .fault_en(fault_en[6]),
  .Q(\sum_in[6] )
);
FI_DFF_DFRTP_FAULTY _826_ (
  .CLK(CLOCK),
  .D(_094_),
  .RESET_B(_008_),
  .fault_en(fault_en[7]),
  .Q(\sum_in[31] )
);
FI_DFF_DFSTP_FAULTY _827_ (
  .CLK(CLOCK),
  .D(_409_),
  .SET_B(_009_),
  .fault_en(fault_en[8]),
  .Q(\stato[0] )
);
FI_DFF_DFRTP_FAULTY _828_ (
  .CLK(CLOCK),
  .D(_000_),
  .RESET_B(_010_),
  .fault_en(fault_en[9]),
  .Q(\stato[1] )
);
FI_DFF_DFRTP_FAULTY _829_ (
  .CLK(CLOCK),
  .D(\stato[0] ),
  .RESET_B(_011_),
  .fault_en(fault_en[10]),
  .Q(\stato[2] )
);
FI_DFF_DFRTP_FAULTY _830_ (
  .CLK(CLOCK),
  .D(_095_),
  .RESET_B(_012_),
  .fault_en(fault_en[11]),
  .Q(DATA_OUT[0])
);
FI_DFF_DFRTP_FAULTY _831_ (
  .CLK(CLOCK),
  .D(_096_),
  .RESET_B(_013_),
  .fault_en(fault_en[12]),
  .Q(DATA_OUT[1])
);
FI_DFF_DFRTP_FAULTY _832_ (
  .CLK(CLOCK),
  .D(_097_),
  .RESET_B(_014_),
  .fault_en(fault_en[13]),
  .Q(DATA_OUT[2])
);
FI_DFF_DFRTP_FAULTY _833_ (
  .CLK(CLOCK),
  .D(_098_),
  .RESET_B(_015_),
  .fault_en(fault_en[14]),
  .Q(DATA_OUT[3])
);
FI_DFF_DFRTP_FAULTY _834_ (
  .CLK(CLOCK),
  .D(_099_),
  .RESET_B(_016_),
  .fault_en(fault_en[15]),
  .Q(DATA_OUT[4])
);
FI_DFF_DFRTP_FAULTY _835_ (
  .CLK(CLOCK),
  .D(_100_),
  .RESET_B(_017_),
  .fault_en(fault_en[16]),
  .Q(DATA_OUT[5])
);
FI_DFF_DFRTP_FAULTY _836_ (
  .CLK(CLOCK),
  .D(_101_),
  .RESET_B(_018_),
  .fault_en(fault_en[17]),
  .Q(DATA_OUT[6])
);
FI_DFF_DFRTP_FAULTY _837_ (
  .CLK(CLOCK),
  .D(_102_),
  .RESET_B(_019_),
  .fault_en(fault_en[18]),
  .Q(DATA_OUT[7])
);
FI_DFF_DFRTP_FAULTY _838_ (
  .CLK(CLOCK),
  .D(_103_),
  .RESET_B(_020_),
  .fault_en(fault_en[19]),
  .Q(\RMAX[0] )
);
FI_DFF_DFRTP_FAULTY _839_ (
  .CLK(CLOCK),
  .D(_104_),
  .RESET_B(_021_),
  .fault_en(fault_en[20]),
  .Q(\RMAX[1] )
);
FI_DFF_DFRTP_FAULTY _840_ (
  .CLK(CLOCK),
  .D(_105_),
  .RESET_B(_022_),
  .fault_en(fault_en[21]),
  .Q(\RMAX[2] )
);
FI_DFF_DFRTP_FAULTY _841_ (
  .CLK(CLOCK),
  .D(_106_),
  .RESET_B(_023_),
  .fault_en(fault_en[22]),
  .Q(\RMAX[3] )
);
FI_DFF_DFRTP_FAULTY _842_ (
  .CLK(CLOCK),
  .D(_107_),
  .RESET_B(_024_),
  .fault_en(fault_en[23]),
  .Q(\RMAX[4] )
);
FI_DFF_DFRTP_FAULTY _843_ (
  .CLK(CLOCK),
  .D(_108_),
  .RESET_B(_025_),
  .fault_en(fault_en[24]),
  .Q(\RMAX[5] )
);
FI_DFF_DFRTP_FAULTY _844_ (
  .CLK(CLOCK),
  .D(_109_),
  .RESET_B(_026_),
  .fault_en(fault_en[25]),
  .Q(\RMAX[6] )
);
FI_DFF_DFRTP_FAULTY _845_ (
  .CLK(CLOCK),
  .D(_110_),
  .RESET_B(_027_),
  .fault_en(fault_en[26]),
  .Q(\RMAX[10] )
);
FI_DFF_DFRTP_FAULTY _846_ (
  .CLK(CLOCK),
  .D(_111_),
  .RESET_B(_028_),
  .fault_en(fault_en[27]),
  .Q(\RMIN[0] )
);
FI_DFF_DFRTP_FAULTY _847_ (
  .CLK(CLOCK),
  .D(_112_),
  .RESET_B(_029_),
  .fault_en(fault_en[28]),
  .Q(\RMIN[1] )
);
FI_DFF_DFRTP_FAULTY _848_ (
  .CLK(CLOCK),
  .D(_113_),
  .RESET_B(_030_),
  .fault_en(fault_en[29]),
  .Q(\RMIN[2] )
);
FI_DFF_DFRTP_FAULTY _849_ (
  .CLK(CLOCK),
  .D(_114_),
  .RESET_B(_031_),
  .fault_en(fault_en[30]),
  .Q(\RMIN[3] )
);
FI_DFF_DFRTP_FAULTY _850_ (
  .CLK(CLOCK),
  .D(_115_),
  .RESET_B(_032_),
  .fault_en(fault_en[31]),
  .Q(\RMIN[4] )
);
FI_DFF_DFRTP_FAULTY _851_ (
  .CLK(CLOCK),
  .D(_116_),
  .RESET_B(_033_),
  .fault_en(fault_en[32]),
  .Q(\RMIN[5] )
);
FI_DFF_DFRTP_FAULTY _852_ (
  .CLK(CLOCK),
  .D(_117_),
  .RESET_B(_034_),
  .fault_en(fault_en[33]),
  .Q(\RMIN[6] )
);
FI_DFF_DFRTP_FAULTY _853_ (
  .CLK(CLOCK),
  .D(_118_),
  .RESET_B(_035_),
  .fault_en(fault_en[34]),
  .Q(\RMIN[10] )
);
FI_DFF_DFRTP_FAULTY _854_ (
  .CLK(CLOCK),
  .D(_119_),
  .RESET_B(_036_),
  .fault_en(fault_en[35]),
  .Q(\RLAST[0] )
);
FI_DFF_DFRTP_FAULTY _855_ (
  .CLK(CLOCK),
  .D(_120_),
  .RESET_B(_037_),
  .fault_en(fault_en[36]),
  .Q(\RLAST[1] )
);
FI_DFF_DFRTP_FAULTY _856_ (
  .CLK(CLOCK),
  .D(_121_),
  .RESET_B(_038_),
  .fault_en(fault_en[37]),
  .Q(\RLAST[2] )
);
FI_DFF_DFRTP_FAULTY _857_ (
  .CLK(CLOCK),
  .D(_122_),
  .RESET_B(_039_),
  .fault_en(fault_en[38]),
  .Q(\RLAST[3] )
);
FI_DFF_DFRTP_FAULTY _858_ (
  .CLK(CLOCK),
  .D(_123_),
  .RESET_B(_040_),
  .fault_en(fault_en[39]),
  .Q(\RLAST[4] )
);
FI_DFF_DFRTP_FAULTY _859_ (
  .CLK(CLOCK),
  .D(_124_),
  .RESET_B(_041_),
  .fault_en(fault_en[40]),
  .Q(\RLAST[5] )
);
FI_DFF_DFRTP_FAULTY _860_ (
  .CLK(CLOCK),
  .D(_125_),
  .RESET_B(_042_),
  .fault_en(fault_en[41]),
  .Q(\RLAST[6] )
);
FI_DFF_DFRTP_FAULTY _861_ (
  .CLK(CLOCK),
  .D(_126_),
  .RESET_B(_043_),
  .fault_en(fault_en[42]),
  .Q(\RLAST[7] )
);
FI_DFF_DFRTP_FAULTY _862_ (
  .CLK(CLOCK),
  .D(_127_),
  .RESET_B(_044_),
  .fault_en(fault_en[43]),
  .Q(\REG1[0] )
);
FI_DFF_DFRTP_FAULTY _863_ (
  .CLK(CLOCK),
  .D(_128_),
  .RESET_B(_045_),
  .fault_en(fault_en[44]),
  .Q(\REG1[1] )
);
FI_DFF_DFRTP_FAULTY _864_ (
  .CLK(CLOCK),
  .D(_129_),
  .RESET_B(_046_),
  .fault_en(fault_en[45]),
  .Q(\REG1[2] )
);
FI_DFF_DFRTP_FAULTY _865_ (
  .CLK(CLOCK),
  .D(_130_),
  .RESET_B(_047_),
  .fault_en(fault_en[46]),
  .Q(\REG1[3] )
);
FI_DFF_DFRTP_FAULTY _866_ (
  .CLK(CLOCK),
  .D(_131_),
  .RESET_B(_048_),
  .fault_en(fault_en[47]),
  .Q(\REG1[4] )
);
FI_DFF_DFRTP_FAULTY _867_ (
  .CLK(CLOCK),
  .D(_132_),
  .RESET_B(_049_),
  .fault_en(fault_en[48]),
  .Q(\REG1[5] )
);
FI_DFF_DFRTP_FAULTY _868_ (
  .CLK(CLOCK),
  .D(_133_),
  .RESET_B(_050_),
  .fault_en(fault_en[49]),
  .Q(\REG1[6] )
);
FI_DFF_DFRTP_FAULTY _869_ (
  .CLK(CLOCK),
  .D(_134_),
  .RESET_B(_051_),
  .fault_en(fault_en[50]),
  .Q(\REG1[10] )
);
FI_DFF_DFRTP_FAULTY _870_ (
  .CLK(CLOCK),
  .D(_135_),
  .RESET_B(_052_),
  .fault_en(fault_en[51]),
  .Q(\REG2[0] )
);
FI_DFF_DFRTP_FAULTY _871_ (
  .CLK(CLOCK),
  .D(_136_),
  .RESET_B(_053_),
  .fault_en(fault_en[52]),
  .Q(\REG2[1] )
);
FI_DFF_DFRTP_FAULTY _872_ (
  .CLK(CLOCK),
  .D(_137_),
  .RESET_B(_054_),
  .fault_en(fault_en[53]),
  .Q(\REG2[2] )
);
FI_DFF_DFRTP_FAULTY _873_ (
  .CLK(CLOCK),
  .D(_138_),
  .RESET_B(_055_),
  .fault_en(fault_en[54]),
  .Q(\REG2[3] )
);
FI_DFF_DFRTP_FAULTY _874_ (
  .CLK(CLOCK),
  .D(_139_),
  .RESET_B(_056_),
  .fault_en(fault_en[55]),
  .Q(\REG2[4] )
);
FI_DFF_DFRTP_FAULTY _875_ (
  .CLK(CLOCK),
  .D(_140_),
  .RESET_B(_057_),
  .fault_en(fault_en[56]),
  .Q(\REG2[5] )
);
FI_DFF_DFRTP_FAULTY _876_ (
  .CLK(CLOCK),
  .D(_141_),
  .RESET_B(_058_),
  .fault_en(fault_en[57]),
  .Q(\REG2[6] )
);
FI_DFF_DFRTP_FAULTY _877_ (
  .CLK(CLOCK),
  .D(_142_),
  .RESET_B(_059_),
  .fault_en(fault_en[58]),
  .Q(\REG2[10] )
);
FI_DFF_DFRTP_FAULTY _878_ (
  .CLK(CLOCK),
  .D(_143_),
  .RESET_B(_060_),
  .fault_en(fault_en[59]),
  .Q(\REG3[0] )
);
FI_DFF_DFRTP_FAULTY _879_ (
  .CLK(CLOCK),
  .D(_144_),
  .RESET_B(_061_),
  .fault_en(fault_en[60]),
  .Q(\REG3[1] )
);
FI_DFF_DFRTP_FAULTY _880_ (
  .CLK(CLOCK),
  .D(_145_),
  .RESET_B(_062_),
  .fault_en(fault_en[61]),
  .Q(\REG3[2] )
);
FI_DFF_DFRTP_FAULTY _881_ (
  .CLK(CLOCK),
  .D(_146_),
  .RESET_B(_063_),
  .fault_en(fault_en[62]),
  .Q(\REG3[3] )
);
FI_DFF_DFRTP_FAULTY _882_ (
  .CLK(CLOCK),
  .D(_147_),
  .RESET_B(_064_),
  .fault_en(fault_en[63]),
  .Q(\REG3[4] )
);
FI_DFF_DFRTP_FAULTY _883_ (
  .CLK(CLOCK),
  .D(_148_),
  .RESET_B(_065_),
  .fault_en(fault_en[64]),
  .Q(\REG3[5] )
);
FI_DFF_DFRTP_FAULTY _884_ (
  .CLK(CLOCK),
  .D(_149_),
  .RESET_B(_066_),
  .fault_en(fault_en[65]),
  .Q(\REG3[6] )
);
FI_DFF_DFRTP_FAULTY _885_ (
  .CLK(CLOCK),
  .D(_150_),
  .RESET_B(_067_),
  .fault_en(fault_en[66]),
  .Q(\REG3[10] )
);
FI_DFF_DFRTP_FAULTY _886_ (
  .CLK(CLOCK),
  .D(RESTART),
  .RESET_B(_068_),
  .fault_en(fault_en[67]),
  .Q(RES)
);
FI_DFF_DFRTP_FAULTY _887_ (
  .CLK(CLOCK),
  .D(AVERAGE),
  .RESET_B(_069_),
  .fault_en(fault_en[68]),
  .Q(AVE)
);
FI_DFF_DFRTP_FAULTY _888_ (
  .CLK(CLOCK),
  .D(ENABLE),
  .RESET_B(_070_),
  .fault_en(fault_en[69]),
  .Q(ENA)
);
FI_DFF_DFRTP_FAULTY _889_ (
  .CLK(CLOCK),
  .D(_151_),
  .RESET_B(_071_),
  .fault_en(fault_en[70]),
  .Q(\REG4[0] )
);
FI_DFF_DFRTP_FAULTY _890_ (
  .CLK(CLOCK),
  .D(_152_),
  .RESET_B(_072_),
  .fault_en(fault_en[71]),
  .Q(\REG4[1] )
);
FI_DFF_DFRTP_FAULTY _891_ (
  .CLK(CLOCK),
  .D(_153_),
  .RESET_B(_073_),
  .fault_en(fault_en[72]),
  .Q(\REG4[2] )
);
FI_DFF_DFRTP_FAULTY _892_ (
  .CLK(CLOCK),
  .D(_154_),
  .RESET_B(_074_),
  .fault_en(fault_en[73]),
  .Q(\REG4[3] )
);
FI_DFF_DFRTP_FAULTY _893_ (
  .CLK(CLOCK),
  .D(_155_),
  .RESET_B(_075_),
  .fault_en(fault_en[74]),
  .Q(\REG4[4] )
);
FI_DFF_DFRTP_FAULTY _894_ (
  .CLK(CLOCK),
  .D(_156_),
  .RESET_B(_076_),
  .fault_en(fault_en[75]),
  .Q(\REG4[5] )
);
FI_DFF_DFRTP_FAULTY _895_ (
  .CLK(CLOCK),
  .D(_157_),
  .RESET_B(_077_),
  .fault_en(fault_en[76]),
  .Q(\REG4[6] )
);
FI_DFF_DFRTP_FAULTY _896_ (
  .CLK(CLOCK),
  .D(_158_),
  .RESET_B(_078_),
  .fault_en(fault_en[77]),
  .Q(\REG4[10] )
);
FI_DFF_DFRTP_FAULTY _897_ (
  .CLK(CLOCK),
  .D(_159_),
  .RESET_B(_079_),
  .fault_en(fault_en[78]),
  .Q(\sum_rm[0] )
);
FI_DFF_DFRTP_FAULTY _898_ (
  .CLK(CLOCK),
  .D(_160_),
  .RESET_B(_080_),
  .fault_en(fault_en[79]),
  .Q(\sum_rm[1] )
);
FI_DFF_DFRTP_FAULTY _899_ (
  .CLK(CLOCK),
  .D(_161_),
  .RESET_B(_081_),
  .fault_en(fault_en[80]),
  .Q(\sum_rm[2] )
);
FI_DFF_DFRTP_FAULTY _900_ (
  .CLK(CLOCK),
  .D(_162_),
  .RESET_B(_082_),
  .fault_en(fault_en[81]),
  .Q(\sum_rm[3] )
);
FI_DFF_DFRTP_FAULTY _901_ (
  .CLK(CLOCK),
  .D(_163_),
  .RESET_B(_083_),
  .fault_en(fault_en[82]),
  .Q(\sum_rm[4] )
);
FI_DFF_DFRTP_FAULTY _902_ (
  .CLK(CLOCK),
  .D(_164_),
  .RESET_B(_084_),
  .fault_en(fault_en[83]),
  .Q(\sum_rm[5] )
);
FI_DFF_DFRTP_FAULTY _903_ (
  .CLK(CLOCK),
  .D(_165_),
  .RESET_B(_085_),
  .fault_en(fault_en[84]),
  .Q(\sum_rm[6] )
);
FI_DFF_DFRTP_FAULTY _904_ (
  .CLK(CLOCK),
  .D(_166_),
  .RESET_B(_086_),
  .fault_en(fault_en[85]),
  .Q(\sum_rm[31] )
);
sky130_fd_sc_hd__conb_1 _905_ (
    .LO(_409_)
  );
endmodule
