// Auto-generated mapped fault enables:
//   fault_en[0] -> _197_ -> stato[0] (RTL)
//   fault_en[1] -> _198_ -> stato[1] (RTL)
//   fault_en[2] -> _199_ -> stato[2] (RTL)
//   fault_en[3] -> _200_ -> stato[3] (RTL)
//   fault_en[4] -> _201_ -> stato[4] (GL_ONLY)
//   fault_en[5] -> _202_ -> stato[5] (GL_ONLY)
//   fault_en[6] -> _203_ -> stato[6] (GL_ONLY)
//   fault_en[7] -> _204_ -> stato[7] (GL_ONLY)
//   fault_en[8] -> _205_ -> stato[8] (GL_ONLY)
//   fault_en[9] -> _206_ -> stato[9] (GL_ONLY)
//   fault_en[10] -> _207_ -> stato[10] (GL_ONLY)
//   fault_en[11] -> _208_ -> ctr[0] (RTL)
//   fault_en[12] -> _209_ -> sign[3] (RTL)
//   fault_en[13] -> _210_ -> v_out[0] (RTL)
//   fault_en[14] -> _211_ -> v_out[1] (RTL)
//   fault_en[15] -> _212_ -> v_out[2] (RTL)
//   fault_en[16] -> _213_ -> v_out[3] (RTL)
//   fault_en[17] -> _214_ -> voto0[0] (RTL)
//   fault_en[18] -> _215_ -> voto1[0] (RTL)
//   fault_en[19] -> _216_ -> voto2[0] (RTL)
//   fault_en[20] -> _217_ -> voto3[0] (RTL)
//   fault_en[21] -> _218_ -> last_g[0] (RTL)
//   fault_en[22] -> _219_ -> last_r[0] (RTL)
//   fault_en[23] -> _220_ -> cts[0] (RTL)

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b10(r_button, g_button, key, start, reset, test, cts, ctr, rts, rtr, clock, v_in, v_out, fault_en);
  input [23:0] fault_en;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  input clock;
  wire clock;
  output ctr;
  wire ctr;
  output cts;
  wire cts;
  input g_button;
  wire g_button;
  input key;
  wire key;
  wire last_g;
  wire last_r;
  input r_button;
  wire r_button;
  input reset;
  wire reset;
  input rtr;
  wire rtr;
  input rts;
  wire rts;
  wire \sign[3] ;
  input start;
  wire start;
  wire \stato[0] ;
  wire \stato[10] ;
  wire \stato[1] ;
  wire \stato[2] ;
  wire \stato[3] ;
  wire \stato[4] ;
  wire \stato[5] ;
  wire \stato[6] ;
  wire \stato[7] ;
  wire \stato[8] ;
  wire \stato[9] ;
  input test;
  wire test;
  input [3:0] v_in;
  wire [3:0] v_in;
  output [3:0] v_out;
  wire [3:0] v_out;
  wire voto0;
  wire voto1;
  wire voto2;
  wire voto3;
  sky130_fd_sc_hd__a21o_2 _099_ (
    .A1(\stato[6] ),
    .A2(rtr),
    .B1(\stato[2] ),
    .X(_085_)
  );
  sky130_fd_sc_hd__or2_2 _100_ (
    .A(\stato[10] ),
    .B(\stato[1] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__inv_2 _101_ (
    .A(\stato[2] ),
    .Y(_087_)
  );
  sky130_fd_sc_hd__o31ai_2 _102_ (
    .A1(\stato[6] ),
    .A2(\stato[0] ),
    .A3(_086_),
    .B1(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_2 _103_ (
    .A(rtr),
    .B(\stato[2] ),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a22o_2 _104_ (
    .A1(rtr),
    .A2(_086_),
    .B1(_088_),
    .B2(_089_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_2 _105_ (
    .A0(_085_),
    .A1(cts),
    .S(_090_),
    .X(_091_)
  );
  sky130_fd_sc_hd__buf_1 _106_ (
    .A(_091_),
    .X(_046_)
  );
  sky130_fd_sc_hd__and3_2 _107_ (
    .A(key),
    .B(\stato[3] ),
    .C(start),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_2 _108_ (
    .A0(last_r),
    .A1(r_button),
    .S(_092_),
    .X(_093_)
  );
  sky130_fd_sc_hd__buf_1 _109_ (
    .A(_093_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_2 _110_ (
    .A0(last_g),
    .A1(g_button),
    .S(_092_),
    .X(_094_)
  );
  sky130_fd_sc_hd__buf_1 _111_ (
    .A(_094_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_2 _112_ (
    .A(voto2),
    .B(voto1),
    .Y(_095_)
  );
  sky130_fd_sc_hd__xnor2_2 _113_ (
    .A(voto0),
    .B(_095_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__or2_2 _114_ (
    .A(\stato[7] ),
    .B(\stato[5] ),
    .X(_097_)
  );
  sky130_fd_sc_hd__a22o_2 _115_ (
    .A1(\stato[9] ),
    .A2(_096_),
    .B1(_097_),
    .B2(v_in[3]),
    .X(_047_)
  );
  sky130_fd_sc_hd__or4_2 _116_ (
    .A(\stato[6] ),
    .B(\stato[3] ),
    .C(\stato[0] ),
    .D(_097_),
    .X(_048_)
  );
  sky130_fd_sc_hd__inv_2 _117_ (
    .A(rts),
    .Y(_049_)
  );
  sky130_fd_sc_hd__and2b_2 _118_ (
    .A_N(start),
    .B(\stato[3] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__buf_1 _119_ (
    .A(_050_),
    .X(_003_)
  );
  sky130_fd_sc_hd__and2b_2 _120_ (
    .A_N(start),
    .B(\stato[6] ),
    .X(_051_)
  );
  sky130_fd_sc_hd__a211oi_2 _121_ (
    .A1(\stato[5] ),
    .A2(_049_),
    .B1(_003_),
    .C1(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__inv_2 _122_ (
    .A(_092_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__o211a_2 _123_ (
    .A1(\stato[9] ),
    .A2(_048_),
    .B1(_052_),
    .C1(_053_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_2 _124_ (
    .A0(voto3),
    .A1(_047_),
    .S(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__buf_1 _125_ (
    .A(_055_),
    .X(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _126_ (
    .A(key),
    .B(\stato[3] ),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _127_ (
    .A1_N(voto2),
    .A2_N(_056_),
    .B1(_097_),
    .B2(v_in[2]),
    .X(_057_)
  );
  sky130_fd_sc_hd__and2b_2 _128_ (
    .A_N(last_r),
    .B(r_button),
    .X(_058_)
  );
  sky130_fd_sc_hd__o211a_2 _129_ (
    .A1(_053_),
    .A2(_058_),
    .B1(_052_),
    .C1(_048_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_2 _130_ (
    .A0(voto2),
    .A1(_057_),
    .S(_059_),
    .X(_060_)
  );
  sky130_fd_sc_hd__buf_1 _131_ (
    .A(_060_),
    .X(_042_)
  );
  sky130_fd_sc_hd__a2bb2o_2 _132_ (
    .A1_N(voto1),
    .A2_N(_056_),
    .B1(_097_),
    .B2(v_in[1]),
    .X(_061_)
  );
  sky130_fd_sc_hd__and2b_2 _133_ (
    .A_N(last_g),
    .B(g_button),
    .X(_062_)
  );
  sky130_fd_sc_hd__o211a_2 _134_ (
    .A1(_053_),
    .A2(_062_),
    .B1(_052_),
    .C1(_048_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_2 _135_ (
    .A0(voto1),
    .A1(_061_),
    .S(_063_),
    .X(_064_)
  );
  sky130_fd_sc_hd__buf_1 _136_ (
    .A(_064_),
    .X(_041_)
  );
  sky130_fd_sc_hd__and2b_2 _137_ (
    .A_N(\sign[3] ),
    .B(\stato[4] ),
    .X(_065_)
  );
  sky130_fd_sc_hd__a221o_2 _138_ (
    .A1(key),
    .A2(\stato[3] ),
    .B1(v_in[0]),
    .B2(_097_),
    .C1(_065_),
    .X(_066_)
  );
  sky130_fd_sc_hd__o31a_2 _139_ (
    .A1(\stato[9] ),
    .A2(\stato[4] ),
    .A3(_048_),
    .B1(_052_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_2 _140_ (
    .A0(voto0),
    .A1(_066_),
    .S(_067_),
    .X(_068_)
  );
  sky130_fd_sc_hd__buf_1 _141_ (
    .A(_068_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_2 _142_ (
    .A0(voto3),
    .A1(v_out[3]),
    .S(_089_),
    .X(_069_)
  );
  sky130_fd_sc_hd__buf_1 _143_ (
    .A(_069_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_2 _144_ (
    .A0(voto2),
    .A1(v_out[2]),
    .S(_089_),
    .X(_070_)
  );
  sky130_fd_sc_hd__buf_1 _145_ (
    .A(_070_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_2 _146_ (
    .A0(voto1),
    .A1(v_out[1]),
    .S(_089_),
    .X(_071_)
  );
  sky130_fd_sc_hd__buf_1 _147_ (
    .A(_071_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_2 _148_ (
    .A0(voto0),
    .A1(v_out[0]),
    .S(_089_),
    .X(_072_)
  );
  sky130_fd_sc_hd__buf_1 _149_ (
    .A(_072_),
    .X(_036_)
  );
  sky130_fd_sc_hd__nand2_2 _150_ (
    .A(\stato[0] ),
    .B(test),
    .Y(_073_)
  );
  sky130_fd_sc_hd__or2b_2 _151_ (
    .A(test),
    .B_N(\stato[0] ),
    .X(_074_)
  );
  sky130_fd_sc_hd__a22o_2 _152_ (
    .A1(\stato[7] ),
    .A2(_073_),
    .B1(_074_),
    .B2(\sign[3] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__or3_2 _153_ (
    .A(\stato[8] ),
    .B(\stato[5] ),
    .C(\stato[0] ),
    .X(_075_)
  );
  sky130_fd_sc_hd__a21bo_2 _154_ (
    .A1(\stato[5] ),
    .A2(_049_),
    .B1_N(_075_),
    .X(_076_)
  );
  sky130_fd_sc_hd__nor2_2 _155_ (
    .A(rts),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o22a_2 _156_ (
    .A1(\stato[8] ),
    .A2(_076_),
    .B1(_077_),
    .B2(ctr),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand4_2 _157_ (
    .A(voto3),
    .B(voto2),
    .C(voto1),
    .D(voto0),
    .Y(_078_)
  );
  sky130_fd_sc_hd__a21bo_2 _158_ (
    .A1(\stato[7] ),
    .A2(_078_),
    .B1_N(_074_),
    .X(_008_)
  );
  sky130_fd_sc_hd__o21a_2 _159_ (
    .A1(\stato[8] ),
    .A2(\stato[5] ),
    .B1(_049_),
    .X(_002_)
  );
  sky130_fd_sc_hd__inv_2 _160_ (
    .A(\stato[7] ),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_2 _161_ (
    .A(_079_),
    .B(_078_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21a_2 _162_ (
    .A1(\stato[6] ),
    .A2(\stato[3] ),
    .B1(start),
    .X(_000_)
  );
  sky130_fd_sc_hd__a22o_2 _163_ (
    .A1(\stato[5] ),
    .A2(rts),
    .B1(\stato[10] ),
    .B2(rtr),
    .X(_004_)
  );
  sky130_fd_sc_hd__or4bb_2 _164_ (
    .A(voto3),
    .B(voto0),
    .C_N(voto1),
    .D_N(voto2),
    .X(_080_)
  );
  sky130_fd_sc_hd__a32o_2 _165_ (
    .A1(rtr),
    .A2(\stato[2] ),
    .A3(_080_),
    .B1(rts),
    .B2(\stato[8] ),
    .X(_009_)
  );
  sky130_fd_sc_hd__o2bb2ai_2 _166_ (
    .A1_N(rtr),
    .A2_N(\stato[1] ),
    .B1(_089_),
    .B2(_080_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _167_ (
    .A(rtr),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a221o_2 _168_ (
    .A1(_081_),
    .A2(\stato[1] ),
    .B1(test),
    .B2(\stato[0] ),
    .C1(_051_),
    .X(_007_)
  );
  sky130_fd_sc_hd__or2_2 _169_ (
    .A(\stato[2] ),
    .B(\stato[10] ),
    .X(_082_)
  );
  sky130_fd_sc_hd__a211o_2 _170_ (
    .A1(_081_),
    .A2(_082_),
    .B1(\stato[4] ),
    .C1(\stato[9] ),
    .X(_006_)
  );
  sky130_fd_sc_hd__buf_1 _171_ (
    .A(reset),
    .X(_083_)
  );
  sky130_fd_sc_hd__inv_2 _172_ (
    .A(_083_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__inv_2 _173_ (
    .A(_083_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__inv_2 _174_ (
    .A(_083_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _175_ (
    .A(_083_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _176_ (
    .A(_083_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__inv_2 _177_ (
    .A(_083_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _178_ (
    .A(_083_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _179_ (
    .A(_083_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__inv_2 _180_ (
    .A(_083_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__inv_2 _181_ (
    .A(_083_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__buf_1 _182_ (
    .A(reset),
    .X(_084_)
  );
  sky130_fd_sc_hd__inv_2 _183_ (
    .A(_084_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__inv_2 _184_ (
    .A(_084_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__inv_2 _185_ (
    .A(_084_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__inv_2 _186_ (
    .A(_084_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _187_ (
    .A(_084_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__inv_2 _188_ (
    .A(_084_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__inv_2 _189_ (
    .A(_084_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _190_ (
    .A(_084_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _191_ (
    .A(_084_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _192_ (
    .A(_084_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _193_ (
    .A(reset),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _194_ (
    .A(reset),
    .Y(_031_)
  );
  sky130_fd_sc_hd__inv_2 _195_ (
    .A(reset),
    .Y(_032_)
  );
  sky130_fd_sc_hd__inv_2 _196_ (
    .A(reset),
    .Y(_033_)
  );
  FI_DFF_DFSTP_FAULTY _197_ (
    .CLK(clock),
    .D(_098_),
    .SET_B(_010_),
    .fault_en(fault_en[0]),
    .Q(\stato[0] )
  );
FI_DFF_DFRTP_FAULTY _198_ (
  .CLK(clock),
  .D(_005_),
  .RESET_B(_011_),
  .fault_en(fault_en[1]),
  .Q(\stato[1] )
);
FI_DFF_DFRTP_FAULTY _199_ (
  .CLK(clock),
  .D(_006_),
  .RESET_B(_012_),
  .fault_en(fault_en[2]),
  .Q(\stato[2] )
);
FI_DFF_DFRTP_FAULTY _200_ (
  .CLK(clock),
  .D(_000_),
  .RESET_B(_013_),
  .fault_en(fault_en[3]),
  .Q(\stato[3] )
);
FI_DFF_DFRTP_FAULTY _201_ (
  .CLK(clock),
  .D(_001_),
  .RESET_B(_014_),
  .fault_en(fault_en[4]),
  .Q(\stato[4] )
);
FI_DFF_DFRTP_FAULTY _202_ (
  .CLK(clock),
  .D(_002_),
  .RESET_B(_015_),
  .fault_en(fault_en[5]),
  .Q(\stato[5] )
);
FI_DFF_DFRTP_FAULTY _203_ (
  .CLK(clock),
  .D(_007_),
  .RESET_B(_016_),
  .fault_en(fault_en[6]),
  .Q(\stato[6] )
);
FI_DFF_DFRTP_FAULTY _204_ (
  .CLK(clock),
  .D(_008_),
  .RESET_B(_017_),
  .fault_en(fault_en[7]),
  .Q(\stato[7] )
);
FI_DFF_DFRTP_FAULTY _205_ (
  .CLK(clock),
  .D(_009_),
  .RESET_B(_018_),
  .fault_en(fault_en[8]),
  .Q(\stato[8] )
);
FI_DFF_DFRTP_FAULTY _206_ (
  .CLK(clock),
  .D(_003_),
  .RESET_B(_019_),
  .fault_en(fault_en[9]),
  .Q(\stato[9] )
);
FI_DFF_DFRTP_FAULTY _207_ (
  .CLK(clock),
  .D(_004_),
  .RESET_B(_020_),
  .fault_en(fault_en[10]),
  .Q(\stato[10] )
);
FI_DFF_DFRTP_FAULTY _208_ (
  .CLK(clock),
  .D(_034_),
  .RESET_B(_021_),
  .fault_en(fault_en[11]),
  .Q(ctr)
);
FI_DFF_DFRTP_FAULTY _209_ (
  .CLK(clock),
  .D(_035_),
  .RESET_B(_022_),
  .fault_en(fault_en[12]),
  .Q(\sign[3] )
);
FI_DFF_DFRTP_FAULTY _210_ (
  .CLK(clock),
  .D(_036_),
  .RESET_B(_023_),
  .fault_en(fault_en[13]),
  .Q(v_out[0])
);
FI_DFF_DFRTP_FAULTY _211_ (
  .CLK(clock),
  .D(_037_),
  .RESET_B(_024_),
  .fault_en(fault_en[14]),
  .Q(v_out[1])
);
FI_DFF_DFRTP_FAULTY _212_ (
  .CLK(clock),
  .D(_038_),
  .RESET_B(_025_),
  .fault_en(fault_en[15]),
  .Q(v_out[2])
);
FI_DFF_DFRTP_FAULTY _213_ (
  .CLK(clock),
  .D(_039_),
  .RESET_B(_026_),
  .fault_en(fault_en[16]),
  .Q(v_out[3])
);
FI_DFF_DFRTP_FAULTY _214_ (
  .CLK(clock),
  .D(_040_),
  .RESET_B(_027_),
  .fault_en(fault_en[17]),
  .Q(voto0)
);
FI_DFF_DFRTP_FAULTY _215_ (
  .CLK(clock),
  .D(_041_),
  .RESET_B(_028_),
  .fault_en(fault_en[18]),
  .Q(voto1)
);
FI_DFF_DFRTP_FAULTY _216_ (
  .CLK(clock),
  .D(_042_),
  .RESET_B(_029_),
  .fault_en(fault_en[19]),
  .Q(voto2)
);
FI_DFF_DFRTP_FAULTY _217_ (
  .CLK(clock),
  .D(_043_),
  .RESET_B(_030_),
  .fault_en(fault_en[20]),
  .Q(voto3)
);
FI_DFF_DFRTP_FAULTY _218_ (
  .CLK(clock),
  .D(_044_),
  .RESET_B(_031_),
  .fault_en(fault_en[21]),
  .Q(last_g)
);
FI_DFF_DFRTP_FAULTY _219_ (
  .CLK(clock),
  .D(_045_),
  .RESET_B(_032_),
  .fault_en(fault_en[22]),
  .Q(last_r)
);
FI_DFF_DFRTP_FAULTY _220_ (
  .CLK(clock),
  .D(_046_),
  .RESET_B(_033_),
  .fault_en(fault_en[23]),
  .Q(cts)
);
sky130_fd_sc_hd__conb_1 _221_ (
    .LO(_098_)
  );
endmodule
