// Auto-generated mapped fault enables:
//   fault_en[0] -> _62_ -> outp[0]
//   fault_en[1] -> _63_ -> overflw[0]
//   fault_en[2] -> _64_ -> stato[0]
//   fault_en[3] -> _65_ -> stato[1]
//   fault_en[4] -> _66_ -> stato[2]

/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module b01(line1, line2, reset, outp, overflw, clock, fault_en);
    input [4:0] fault_en;
wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  input clock;
  wire clock;
  input line1;
  wire line1;
  input line2;
  wire line2;
  output outp;
  wire outp;
  output overflw;
  wire overflw;
  input reset;
  wire reset;
  wire \stato[0] ;
  wire \stato[1] ;
  wire \stato[2] ;
  sky130_fd_sc_hd__nor2_2 _31_ (
    .A(line2),
    .B(line1),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and2_2 _32_ (
    .A(line2),
    .B(line1),
    .X(_08_)
  );
  sky130_fd_sc_hd__or2_2 _33_ (
    .A(_07_),
    .B(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__and2b_2 _34_ (
    .A_N(\stato[0] ),
    .B(\stato[1] ),
    .X(_10_)
  );
  sky130_fd_sc_hd__and2b_2 _35_ (
    .A_N(_10_),
    .B(\stato[2] ),
    .X(_11_)
  );
  sky130_fd_sc_hd__xnor2_2 _36_ (
    .A(_09_),
    .B(_11_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__or2_2 _37_ (
    .A(line2),
    .B(line1),
    .X(_12_)
  );
  sky130_fd_sc_hd__nor2_2 _38_ (
    .A(\stato[0] ),
    .B(\stato[1] ),
    .Y(_13_)
  );
  sky130_fd_sc_hd__and2b_2 _39_ (
    .A_N(\stato[1] ),
    .B(\stato[0] ),
    .X(_14_)
  );
  sky130_fd_sc_hd__and3b_2 _40_ (
    .A_N(\stato[2] ),
    .B(_08_),
    .C(_14_),
    .X(_15_)
  );
  sky130_fd_sc_hd__a31o_2 _41_ (
    .A1(\stato[2] ),
    .A2(_12_),
    .A3(_13_),
    .B1(_15_),
    .X(_16_)
  );
  sky130_fd_sc_hd__and2_2 _42_ (
    .A(\stato[0] ),
    .B(\stato[1] ),
    .X(_17_)
  );
  sky130_fd_sc_hd__a32o_2 _43_ (
    .A1(\stato[2] ),
    .A2(_12_),
    .A3(_17_),
    .B1(_10_),
    .B2(_08_),
    .X(_18_)
  );
  sky130_fd_sc_hd__nor3_2 _44_ (
    .A(\stato[2] ),
    .B(_10_),
    .C(_14_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a31o_2 _45_ (
    .A1(\stato[2] ),
    .A2(_12_),
    .A3(_14_),
    .B1(_19_),
    .X(_20_)
  );
  sky130_fd_sc_hd__nand2_2 _46_ (
    .A(_08_),
    .B(_19_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__o31a_2 _47_ (
    .A1(_16_),
    .A2(_18_),
    .A3(_20_),
    .B1(_21_),
    .X(_28_)
  );
  sky130_fd_sc_hd__mux2_2 _48_ (
    .A0(_10_),
    .A1(_14_),
    .S(\stato[2] ),
    .X(_22_)
  );
  sky130_fd_sc_hd__and3_2 _49_ (
    .A(\stato[2] ),
    .B(_07_),
    .C(_13_),
    .X(_23_)
  );
  sky130_fd_sc_hd__or3b_2 _50_ (
    .A(\stato[2] ),
    .B(_08_),
    .C_N(_14_),
    .X(_24_)
  );
  sky130_fd_sc_hd__or4b_2 _51_ (
    .A(_18_),
    .B(_22_),
    .C(_23_),
    .D_N(_24_),
    .X(_25_)
  );
  sky130_fd_sc_hd__buf_1 _52_ (
    .A(_25_),
    .X(_29_)
  );
  sky130_fd_sc_hd__or3b_2 _53_ (
    .A(_16_),
    .B(_22_),
    .C_N(_21_),
    .X(_26_)
  );
  sky130_fd_sc_hd__buf_1 _54_ (
    .A(_26_),
    .X(_30_)
  );
  sky130_fd_sc_hd__and2b_2 _55_ (
    .A_N(\stato[2] ),
    .B(_17_),
    .X(_27_)
  );
  sky130_fd_sc_hd__buf_1 _56_ (
    .A(_27_),
    .X(_01_)
  );
  sky130_fd_sc_hd__inv_2 _57_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__inv_2 _58_ (
    .A(reset),
    .Y(_03_)
  );
  sky130_fd_sc_hd__inv_2 _59_ (
    .A(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__inv_2 _60_ (
    .A(reset),
    .Y(_05_)
  );
  sky130_fd_sc_hd__inv_2 _61_ (
    .A(reset),
    .Y(_06_)
  );
  FI_DFF_DFRTP_FAULTY _62_ (
    .CLK(clock),
    .D(_00_),
    .RESET_B(_02_),
    .fault_en(fault_en[0]),
    .Q(outp)
  );
FI_DFF_DFRTP_FAULTY _63_ (
  .CLK(clock),
  .D(_01_),
  .RESET_B(_03_),
  .fault_en(fault_en[1]),
  .Q(overflw)
);
FI_DFF_DFRTP_FAULTY _64_ (
  .CLK(clock),
  .D(_28_),
  .RESET_B(_04_),
  .fault_en(fault_en[2]),
  .Q(\stato[0] )
);
FI_DFF_DFRTP_FAULTY _65_ (
  .CLK(clock),
  .D(_29_),
  .RESET_B(_05_),
  .fault_en(fault_en[3]),
  .Q(\stato[1] )
);
FI_DFF_DFRTP_FAULTY _66_ (
  .CLK(clock),
  .D(_30_),
  .RESET_B(_06_),
  .fault_en(fault_en[4]),
  .Q(\stato[2] )
);
endmodule

